# -*- coding: utf-8 -*-
# =====================================
#  tia_constants_map.py  (rebuilt clean)
# =====================================

# Costanti base

# ===============================
# 📌 LEGGENDA TYPE_AXISPARAM
# ===============================
AXIS_BOOL_LABELS = [
    "ASSE_BOOL_CONFIG",
    "ASSE_BOOL_BP1",
    "ASSE_BOOL_BP2",
    "ASSE_BOOL_BP3",
    "ASSE_BOOL_BP4",
    "ASSE_BOOL_BP5",
    "ASSE_BOOL_BP6",
    "ASSE_BOOL_BP7",
    "ASSE_BOOL_BP8",
    "ASSE_BOOL_BP9",
    "ASSE_BOOL_BP10",
    "ASSE_BOOL_BP11",
    "ASSE_BOOL_BP12",
    "ASSE_BOOL_FLAGCOUPMAX",
    "ASSE_BOOL_SHOWMAN",
    "ASSE_BOOL_SHOWAUTO",
    "ASSE_BOOL_ENABAXIS",
    "ASSE_BOOL_ENABINTERP",
    "ASSE_BOOL_ENABTEACH",
    "ASSE_BOOL_ENABSMAX",
    "ASSE_BOOL_ENABSMIN",
    "ASSE_BOOL_ENABSHH",
    "ASSE_BOOL_ENABSH",
    "ASSE_BOOL_ENABSL",
    "ASSE_BOOL_ENABSLL",
    "ASSE_BOOL_CONFIGUP",
    "ASSE_BOOL_CONFIGDOWN",
    "ASSE_BOOL_FLAGINV",
    "ASSE_BOOL_CHECKSTOPDISABLED",
    "ASSE_BOOL_SHOWDELTA",
    "ASSE_BOOL_DISABLEDELTA",
    "ASSE_BOOL_ENABSH0",
    "ASSE_BOOL_ENABSL0",
    "ASSE_BOOL_MANSPUP",
    "ASSE_BOOL_MANSPDOWN",
    "ASSE_BOOL_SHOWDELTATAB",
    "ASSE_BOOL_NOMACHINESTARTED",
    "ASSE_BOOL_AXISNOMOVE",
    "ASSE_BOOL_COUPCALC",
    "ASSE_BOOL_FREE_39",
    "ASSE_BOOL_FREE_40",
]

AXIS_INT_LABELS = [
    "ASSE_INT_MASTER",
    "ASSE_INT_FEEDBACK",
    "ASSE_INT_INPUT",
    "ASSE_INT_INPUT2",
    "ASSE_INT_INPUT3",
    "ASSE_INT_INPUT4",
    "ASSE_INT_OUTPUT1",
    "ASSE_INT_OUTPUT2",
    "ASSE_INT_OUTPUT3",
    "ASSE_INT_OUTPUT4",
    "ASSE_INT_LABELTYPE",
    "ASSE_INT_LABELROW",
    "ASSE_INT_LABELCOL",
    "ASSE_INT_LABELNTOT",
    "ASSE_INT_LABELNDEC",
    "ASSE_INT_LABELROWIMP",
    "ASSE_INT_LABELCOLIMP",
    "ASSE_INT_LABELNTOTIMP",
    "ASSE_INT_LABELNDECIMP",
    "ASSE_INT_SUPLSIND",
    "ASSE_INT_INFLSIND",
    "ASSE_INT_P1",
    "ASSE_INT_P2",
    "ASSE_INT_TIMEOUT1",
    "ASSE_INT_TIMEOUT2",
    "ASSE_INT_BOOSTVAL",
    "ASSE_INT_TIPOMISURA",
    "ASSE_INT_DEFSPEED",
    "ASSE_INT_MOVEMODE",
    "ASSE_INT_INTERPGROUP",
    "ASSE_INT_ALTFB",
    "ASSE_INT_ALTFBDIG",
    "ASSE_INT_INDSHH",
    "ASSE_INT_INDSH",
    "ASSE_INT_INDSL",
    "ASSE_INT_INDSLL",
    "ASSE_INT_SAFETYUPIND1",
    "ASSE_INT_SAFETYUPIND2",
    "ASSE_INT_SAFETYUPIND3",
    "ASSE_INT_SAFETYUPIND4",
    "ASSE_INT_SAFETYUPIND5",
    "ASSE_INT_SAFETYUPIND6",
    "ASSE_INT_INDSH0",
    "ASSE_INT_INDSL0",
    "ASSE_INT_INDMEM",
    "ASSE_INT_PERACQ",
    "ASSE_INT_NUMTIMEOUT",
    "ASSE_INT_PERVELAVG",
    "ASSE_INT_SAFETYDOWNIND1",
    "ASSE_INT_SAFETYDOWNIND2",
    "ASSE_INT_SAFETYDOWNIND3",
    "ASSE_INT_SAFETYDOWNIND4",
    "ASSE_INT_SAFETYDOWNIND5",
    "ASSE_INT_SAFETYDOWNIND6",
    "ASSE_INT_DELAYUP",
    "ASSE_INT_DELAYDOWN",
    "ASSE_INT_MAXVELPERC",
    "ASSE_INT_DECOUPMASTER",
    "ASSE_INT_DECOUPMASTER2",
    "ASSE_INT_DECOUPMASTER3",
    "ASSE_INT_DECOUPMASTER4",
    "ASSE_INT_DECOUPMASTER5",
    "ASSE_INT_DECOUPMASTER6",
    "ASSE_INT_PS",
    "ASSE_INT_BWVSLOW",
    "ASSE_INT_FWVSLOW",
    "ASSE_INT_PS2",
    "ASSE_INT_PS3",
    "ASSE_INT_AXISCOUPCHECK",
    "ASSE_INT_TEACHMINMULT",
    "ASSE_INT_FREE_70",
    "ASSE_INT_FREE_71",
    "ASSE_INT_PID",
    "ASSE_INT_GRAFIND",
    "ASSE_INT_DELTA1",
    "ASSE_INT_OPTPARAMIND",
    "ASSE_INT_DISABLEBP1",
    "ASSE_INT_DISABLEBP2",
    "ASSE_INT_DISABLEBP3",
    "ASSE_INT_DISABLEBP4",
    "ASSE_INT_DISABLEBP5",
    "ASSE_INT_DISABLEBP6",
    "ASSE_INT_DISABLEBP7",
    "ASSE_INT_DISABLEBP8",
    "ASSE_INT_DISABLEBP9",
    "ASSE_INT_DISABLEBP10",
    "ASSE_INT_DISABLEBP11",
    "ASSE_INT_DISABLEBP12",
    "ASSE_INT_OPTPARAM1",
    "ASSE_INT_OPTPARAM2",
    "ASSE_INT_OPTPARAM3",
    "ASSE_INT_HOLDTORUNTYPE",
    "ASSE_INT_FREE_92",
    "ASSE_INT_FREE_93",
    "ASSE_INT_FREE_94",
]

AXIS_REAL_LABELS = [
    "ASSE_REAL_SRTUP",
    "ASSE_REAL_SRTDOWN",
    "ASSE_REAL_COEFFUP",
    "ASSE_REAL_COEFFDOWN",
    "ASSE_REAL_P1UP",
    "ASSE_REAL_P1DOWN",
    "ASSE_REAL_P2UP",
    "ASSE_REAL_P2DOWN",
    "ASSE_REAL_SYSPRESSUP1",
    "ASSE_REAL_SYSPRESSDOWN1",
    "ASSE_REAL_SYSPRESSUP2",
    "ASSE_REAL_SYSPRESSDOWN2",
    "ASSE_REAL_SYSPRESSUP3",
    "ASSE_REAL_SYSPRESSDOWN3",
    "ASSE_REAL_BWVMAX",
    "ASSE_REAL_DSMAXDOWN",
    "ASSE_REAL_DSMAXUP",
    "ASSE_REAL_FWVMAX",
    "ASSE_REAL_SMAX",
    "ASSE_REAL_SMIN",
    "ASSE_REAL_SSUP",
    "ASSE_REAL_SINF",
    "ASSE_REAL_VMINSTARTED",
    "ASSE_REAL_SHH",
    "ASSE_REAL_SH",
    "ASSE_REAL_SL",
    "ASSE_REAL_SLL",
    "ASSE_REAL_TILTMAX",
    "ASSE_REAL_MASTERMULT",
    "ASSE_REAL_MASTERDELTAMIN",
    "ASSE_REAL_MASTERKSRS",
    "ASSE_REAL_SLAVEVRESET",
    "ASSE_REAL_SLAVEVMIN",
    "ASSE_REAL_SLAVEDELTATSTART",
    "ASSE_REAL_OUTKP",
    "ASSE_REAL_OUTDELTAT",
    "ASSE_REAL_SH0",
    "ASSE_REAL_SL0",
    "ASSE_REAL_TILTMAXDOWN",
    "ASSE_REAL_FREE_39",
    "ASSE_REAL_DELTAMOVINGUP",
    "ASSE_REAL_DELTAMOVINGDOWN",
    "ASSE_REAL_DELTADIV",
    "ASSE_REAL_DELTAMOVINGSUPUP",
    "ASSE_REAL_DELTAMOVINGINFUP",
    "ASSE_REAL_DELTAMOVINGSUPDOWN",
    "ASSE_REAL_DELTAMOVINGINFDOWN",
    "ASSE_REAL_DELTAAUTO",
    "ASSE_REAL_BWACCMAX",
    "ASSE_REAL_FWACCMAX",
    "ASSE_REAL_OPTPARAM1",
    "ASSE_REAL_OPTPARAM2",
    "ASSE_REAL_OPTPARAM3",
    "ASSE_REAL_AXISCOUPMIN",
    "ASSE_REAL_FREE_54",
]

# ===============================
# 📌 LEGGENDA TYPE_TOOLSETOUTPUTPARAM
# ===============================

TOOLSETOUTPUT_INT_LABELS = [
    "TOOLSETOUTPUT_INT_AXIS",   # intval[0]
    "TOOLSETOUTPUT_INT_IND",    # intval[1]
]

TOOLSETOUTPUT_DINT_LABELS = [
    "TOOLSETOUTPUT_DINT_SCALEMIN1",   # dintval[0]
    "TOOLSETOUTPUT_DINT_SCALEMAX1",   # dintval[1]
    "TOOLSETOUTPUT_DINT_SCALEMIN2",   # dintval[2]
    "TOOLSETOUTPUT_DINT_SCALEMAX2",   # dintval[3]
    "TOOLSETOUTPUT_DINT_SCALEMIN1H",  # dintval[4]
    "TOOLSETOUTPUT_DINT_SCALEMAX1H",  # dintval[5]
    "TOOLSETOUTPUT_DINT_SCALEMIN2H",  # dintval[6]
    "TOOLSETOUTPUT_DINT_SCALEMAX2H",  # dintval[7]
]


# ===============================
# 📌 IN/OUT INDEX MAPS
# ===============================

IN_IND_MAP = [
    {"label": "BOOL_IND_AUTOMODESEL", "display": "AUTO SEL DI", "origin": "Params>Configuration>Main>SEL IO"},
    {"label": "BOOL_IND_TEACHMODESEL", "display": "AUTO TEACH DI", "origin": "Params>Configuration>Main>SEL IO"},
    {"label": "BOOL_IND_CYCLEMODESEL", "display": "CYCLE SEL DI", "origin": "Params>Configuration>Main>SEL IO"},
    {"label": "BOOL_IND_STARTRESET", "display": "BOOL_IND_STARTRESET", "origin": "Params>Configuration>Main>CMD IO"},
    {"label": "BOOL_IND_REMOTEMODESEL", "display": "REMOTE SEL DI", "origin": "Params>Configuration>Main>SEL IO"},
    {"label": "BOOL_IND_EMGCYPB", "display": "EMGCY PB DI", "origin": "Params>Configuration>Safety"},
    {"label": "BOOL_IND_CONSOLE2MODESEL", "display": "CONSOLE 2 SEL DI", "origin": "Params>Configuration>Main>SEL IO"},
    {"label": "BOOL_IND_CHROLLMODESEL", "display": "CHROLL SEL DI", "origin": "Params>Configuration>Main>SEL IO"},
    {"label": "BOOL_IND_INENABLED", "display": "BOOL_IND_INENABLED", "origin": "??"},
    {"label": "BOOL_IND_DEBALNOTPRESS", "display": "DEBALNOTPRESS DI", "origin": "Params>Configuration>Main>STATUS IO"},
    {"label": "BOOL_IND_CONSOLE1MODESEL", "display": "CONSOLE 1 SEL DI", "origin": "Params>Configuration>Main>SEL IO"},
    {"label": "BOOL_IND_SINGMOVSEL", "display": "SINGMOV SEL DI", "origin": "Params>Configuration>Main>SEL IO"},
    {"label": "BOOL_IND_STARTIN", "display": "STARTIN DI", "origin": "Params>Configuration>Main>CMD IO"},
    {"label": "BOOL_IND_STOPIN", "display": "STOPIN DI", "origin": "Params>Configuration>Main>CMD IO"},
    {"label": "BOOL_IND_STARTEDIN", "display": "MAC.STARTED IN DI", "origin": "Params>Configuration>Main>STATUS IO"},
    {"label": "BOOL_IND_HOLDTORUN", "display": "HOLDTORUN DI", "origin": "Params>Configuration>Safety"},
    {"label": "BOOL_IND_RTCOUPLED", "display": "RTCOUPLED DI", "origin": "Params>Configuration>RT"},
    {"label": "BOOL_IND_LEFTSEL", "display": "RC LEFT SEL DI", "origin": "Params>Configuration>Radio Control"},
    {"label": "BOOL_IND_PINCHPRESS", "display": "PINCHPRESS DI", "origin": "Params>Pinch Preload"},
    {"label": "BOOL_IND_RIGHTSEL", "display": "RC RIGHT SEL", "origin": "Params>Configuration>Radio Control"},
    {"label": "BOOL_IND_STARTSENSOR", "display": "START SENSOR IN DI", "origin": "Params>Configuration>Main>STATUS IO"},
    {"label": "BOOL_IND_MAINTRESET", "display": "MAINTRESET DI", "origin": "Params>Configuration>Main>CMD IO"},
    {"label": "BOOL_IND_MANMODESEL", "display": "MAN SEL DI", "origin": "Params>Configuration>Main>SEL IO"},
    {"label": "BOOL_IND_TESTMODESEL", "display": "TEST SEL DI", "origin": "Params>Configuration>Main>SEL IO"},
    {"label": "BOOL_IND_SEMIAUTOMODESEL", "display": "SEMIAUTO SEL DI", "origin": "Params>Configuration>Main>SEL IO"},
    {"label": "BOOL_IND_HOLDTORUN2", "display": "HOLDTORUN2 DI", "origin": "Params>Configuration>Safety"},
    {"label": "BOOL_IND_DISABLEBP1", "display": "DISABLEBP1 DI", "origin": "Params>Configuration>BP"},
    {"label": "BOOL_IND_DISABLEBP2", "display": "DISABLEBP2 DI", "origin": "Params>Configuration>BP"},
    {"label": "BOOL_IND_DISABLEBP3", "display": "DISABLEBP3 DI", "origin": "Params>Configuration>BP"},
    {"label": "BOOL_IND_DISABLEBP4", "display": "DISABLEBP4 DI", "origin": "Params>Configuration>BP"},
    {"label": "BOOL_IND_DISABLEBP5", "display": "DISABLEBP5 DI", "origin": "Params>Configuration>BP"},
    {"label": "BOOL_IND_DISABLEBP6", "display": "DISABLEBP6 DI", "origin": "Params>Configuration>BP"},
    {"label": "BOOL_IND_DISABLEBP7", "display": "DISABLEBP7 DI", "origin": "Params>Configuration>BP"},
    {"label": "BOOL_IND_DISABLEBP8", "display": "DISABLEBP8 DI", "origin": "Params>Configuration>BP"},
    {"label": "BOOL_IND_DISABLEBP9", "display": "DISABLEBP9 DI", "origin": "Params>Configuration>BP"},
    {"label": "BOOL_IND_DISABLEBP10", "display": "DISABLEBP10 DI", "origin": "Params>Configuration>BP"},
    {"label": "BOOL_IND_DISABLEBP11", "display": "DISABLEBP11 DI", "origin": "Params>Configuration>BP"},
    {"label": "BOOL_IND_DISABLEBP12", "display": "DISABLEBP12 DI", "origin": "Params>Configuration>BP"},
    {"label": "BOOL_IND_AUTOMODE", "display": "AUTO MODE DI", "origin": "Params>Configuration>Main>MODE IO"},
    {"label": "BOOL_IND_AUTOCYCLEMODE", "display": "AUTOCYCLE MODE DI", "origin": "Params>Configuration>Main>MODE IO"},
    {"label": "BOOL_IND_AUTOSTEPMODE", "display": "AUTOSTEP MODE DI", "origin": "Params>Configuration>Main>MODE IO"},
    {"label": "BOOL_IND_SEMIAUTOMODE", "display": "SEMIAUTO MODE DI", "origin": "Params>Configuration>Main>MODE IO"},
    {"label": "BOOL_IND_TEACHMODE", "display": "TEACH MODE DI", "origin": "Params>Configuration>Main>MODE IO"},
    {"label": "BOOL_IND_MANMODE", "display": "MAN MODE DI", "origin": "Params>Configuration>Main>MODE IO"},
    {"label": "BOOL_IND_CONSOLE1MODE", "display": "CONSOLE 1 MODE DI", "origin": "Params>Configuration>Main>MODE IO"},
    {"label": "BOOL_IND_CONSOLE2MODE", "display": "CONSOLE 2 MODE DI", "origin": "Params>Configuration>Main>MODE IO"},
    {"label": "BOOL_IND_REMOTEMODE", "display": "REMOTE MODE DI", "origin": "Params>Configuration>Main>MODE IO"},
    {"label": "BOOL_IND_CHROLLMODE", "display": "CHROLL MODE DI", "origin": "Params>Configuration>Main>MODE IO"},
    {"label": "BOOL_IND_SINGMOVMODE", "display": "SINGMOV MODE DI", "origin": "Params>Configuration>Main>MODE IO"},
    {"label": "BOOL_IND_MACHINESTARTED", "display": "MACHINE STARTED DI", "origin": "Params>Configuration>Main>RSM IO"},
    {"label": "BOOL_IND_OUTSWENAB", "display": "BOOL_IND_OUTSWENAB", "origin": "??"},
    {"label": "BOOL_IND_GREASEPUMPON", "display": "PUMP ON CALC DI", "origin": "Params>Configuration>Main>Grease"},
    {"label": "BOOL_IND_GREASEALARM", "display": "GREASE ALARM CALC DI", "origin": "Params>Configuration>Main>Grease"},
    {"label": "BOOL_IND_GREASEPUMPALARM", "display": "PUMP ALARM (CALC) DI", "origin": "Params>Configuration>Main>Grease"},
    {"label": "BOOL_IND_WAITINGFORSTART", "display": "BOOL_IND_WAITINGFORSTART", "origin": "??"},
    {"label": "BOOL_IND_POWEROFFFLAG", "display": "BOOL_IND_POWEROFFFLAG", "origin": "??"},
    {"label": "BOOL_IND_ALARMON", "display": "ALARM ON DI", "origin": "Params>Configuration>Main>RSM IO"},
    {"label": "BOOL_IND_STARTCMD", "display": "BOOL_IND_STARTCMD", "origin": "??"},
    {"label": "BOOL_IND_ALARMSTOP", "display": "ALARM STOP DI", "origin": "Params>Configuration>Main>RSM IO"},
    {"label": "BOOL_IND_MAINTON", "display": "MAINTON DI", "origin": "Params>Configuration>Main>RSM IO"},
    {"label": "BOOL_IND_RTFWDISABLED", "display": "RTFW DISABLED DI", "origin": "Params>Configuration>Main>STATUS IO"},
    {"label": "BOOL_IND_LEFTMEM", "display": "RC LEFT MEM DI", "origin": "Params>Configuration>Radio Control"},
    {"label": "BOOL_IND_RESETFLAG", "display": "BOOL_IND_RESETFLAG", "origin": "??"},
    {"label": "BOOL_IND_RIGHTMEM", "display": "RC RIGHT MEM DI", "origin": "Params>Configuration>Radio Control"},
    {"label": "BOOL_IND_OUTENABLED", "display": "HOLDTORUN ERROR DI", "origin": "Params>Configuration>Safety"},
    {"label": "BOOL_IND_STOPCMD", "display": "BOOL_IND_STOPCMD", "origin": "??"},
    {"label": "BOOL_IND_QUALITYENAB", "display": "BOOL_IND_QUALITYENAB", "origin": "??"},
    {"label": "BOOL_IND_TELESERVICEREQ", "display": "BOOL_IND_TELESERVICEREQ", "origin": "??"},
    {"label": "BOOL_IND_MICROMODESEL", "display": "MICRO SEL DI", "origin": "Params>Configuration>Main>SEL IO"},
    {"label": "BOOL_IND_APPLY", "display": "BOOL_IND_APPLY", "origin": "??"},
    {"label": "BOOL_IND_QUALITYEND", "display": "QUALITY END DI", "origin": "Params>Configuration>Main>RSM IO"},
    {"label": "BOOL_IND_AUTOSTARTINGBLINK", "display": "AUTOSTARTI BLINK DI", "origin": "Params>Configuration>Main>STATUS IO"},
    {"label": "BOOL_IND_QUALITYGOOD", "display": "QUALITY GOOD DI", "origin": "Params>Configuration>Main>RSM IO"},
    {"label": "BOOL_IND_PARTEND", "display": "PART END DI", "origin": "Params>Configuration>Main>RSM IO"},
    {"label": "BOOL_IND_AUTOCORR", "display": "BOOL_IND_AUTOCORR", "origin": "??"},
    {"label": "BOOL_IND_PARTBEGIN", "display": "PART BEGIN DI", "origin": "Params>Configuration>Main>RSM IO"},
    {"label": "BOOL_IND_AUTOCORRSTARTED", "display": "BOOL_IND_AUTOCORRSTARTED", "origin": "??"},
    {"label": "BOOL_IND_TILTDISABLED", "display": "TILT DISABLE DI", "origin": "Params>Configuration>Main>CMD IO"},
    {"label": "BOOL_IND_EYEBENDON", "display": "BOOL_IND_EYEBENDON", "origin": "??"},
    {"label": "BOOL_IND_BP1", "display": "BOOL_IND_BP1", "origin": "??"},
    {"label": "BOOL_IND_BP2", "display": "BOOL_IND_BP2", "origin": "??"},
    {"label": "BOOL_IND_BP3", "display": "BOOL_IND_BP3", "origin": "??"},
    {"label": "BOOL_IND_BP4", "display": "BOOL_IND_BP4", "origin": "??"},
    {"label": "BOOL_IND_BP5", "display": "BOOL_IND_BP5", "origin": "??"},
    {"label": "BOOL_IND_BP6", "display": "BOOL_IND_BP6", "origin": "??"},
    {"label": "BOOL_IND_BP7", "display": "BOOL_IND_BP7", "origin": "??"},
    {"label": "BOOL_IND_BP8", "display": "BOOL_IND_BP8", "origin": "??"},
    {"label": "BOOL_IND_BP9", "display": "BOOL_IND_BP9", "origin": "??"},
    {"label": "BOOL_IND_BP10", "display": "BOOL_IND_BP10", "origin": "??"},
    {"label": "BOOL_IND_BP11", "display": "BOOL_IND_BP11", "origin": "??"},
    {"label": "BOOL_IND_BP12", "display": "BOOL_IND_BP12", "origin": "??"},
    {"label": "BOOL_IND_RCV0", "display": "RC V0 DI", "origin": "Params>Configuration>Main>Radio Control"},
    {"label": "BOOL_IND_RCV1", "display": "RC V1 DI", "origin": "Params>Configuration>Main>Radio Control"},
    {"label": "BOOL_IND_RCV2", "display": "RC V2 DI", "origin": "Params>Configuration>Main>Radio Control"},
    {"label": "BOOL_IND_RCV3", "display": "RC V3 DI", "origin": "Params>Configuration>Main>Radio Control"},
    {"label": "BOOL_IND_RCV4", "display": "RC V4 DI", "origin": "Params>Configuration>Main>Radio Control"},
    {"label": "BOOL_IND_RCUM", "display": "BOOL_IND_RCUM", "origin": "??"},
    {"label": "BOOL_IND_RCLUP", "display": "BOOL_IND_RCLUP", "origin": "??"},
    {"label": "BOOL_IND_RCLDOWN", "display": "BOOL_IND_RCLDOWN", "origin": "??"},
    {"label": "BOOL_IND_RCRUP", "display": "BOOL_IND_RCRUP", "origin": "??"},
    {"label": "BOOL_IND_RCRDOWN", "display": "BOOL_IND_RCRDOWN", "origin": "??"},
    {"label": "BOOL_IND_RCBUP", "display": "BOOL_IND_RCBUP", "origin": "??"},
    {"label": "BOOL_IND_RCBDOWN", "display": "BOOL_IND_RCBDOWN", "origin": "??"},
    {"label": "BOOL_IND_RCTLEFT", "display": "BOOL_IND_RCTLEFT", "origin": "??"},
    {"label": "BOOL_IND_RCTRIGHT", "display": "BOOL_IND_RCTRIGHT", "origin": "??"},
    {"label": "BOOL_IND_EMGCYRESETBTN", "display": "EMGCY RESET BTN DI", "origin": "Params>Configuration>Safety"},
    {"label": "BOOL_IND_RCALARM", "display": "BOOL_IND_RCALARM", "origin": "??"},
    {"label": "BOOL_IND_EMGCYRESET", "display": "BOOL_IND_EMGCYRESET", "origin": "??"},
    {"label": "BOOL_IND_INVERTERRESET", "display": "INVERTER RESET DI", "origin": "Params>Configuration>Main>STATUS IO"},
    {"label": "BOOL_IND_INVERTERALARM", "display": "INVERTER ALARM DI", "origin": "Params>Configuration>Main>STATUS IO"},
    {"label": "BOOL_IND_AUTOSTARTING", "display": "AUTO STARTING DI", "origin": "Params>Configuration>Main>STATUS IO"},
    {"label": "BOOL_IND_PINCHPRESSFRONTREAR", "display": "BOOL_IND_PINCHPRESSFRONTREAR", "origin": "??"},
    {"label": "BOOL_IND_PINCHPRESSFRONTREAR2", "display": "BOOL_IND_PINCHPRESSFRONTREAR2", "origin": "??"},
    {"label": "BOOL_IND_HOLDTORUNRC", "display": "HOLDTORUN RC DI", "origin": "Params>Configuration>Safety"},
    {"label": "BOOL_IND_PRELOADUP", "display": "PRELOAD UP DI", "origin": "Params>Configuration>Pinch Preload"},
    {"label": "BOOL_IND_PRELOADPINCHDISABLED", "display": "PRELOAD PINCH DISAB DI", "origin": "Params>Configuration>Pinch Preload"},
    {"label": "BOOL_IND_PARTMAN", "display": "BOOL_IND_PARTMAN", "origin": "??"},
    {"label": "BOOL_IND_PARTMANBEGIN", "display": "BOOL_IND_PARTMANBEGIN", "origin": "??"},
    {"label": "BOOL_IND_PARTMANEND", "display": "BOOL_IND_PARTMANEND", "origin": "??"},
    {"label": "BOOL_IND_PARTMANRUNNING", "display": "BOOL_IND_PARTMANRUNNING", "origin": "??"},
    {"label": "BOOL_IND_UNBALLEFT", "display": "UNBAL LEFT DI", "origin": "Params>Configuration>Main>CMD IO"},
    {"label": "BOOL_IND_UNBALRIGHT", "display": "UNBAL RIGHT DI", "origin": "Params>Configuration>Main>CMD IO"},
    {"label": "BOOL_IND_INVERTEROVERLOAD", "display": "INVERTER OVERLOAD DI", "origin": "Params>Configuration>Main>STATUS IO"},
    {"label": "BOOL_IND_LEFTSUPPINTERLOCK", "display": "LEFT SUPP INTERL. DI", "origin": "Params>Configuration>Main>STATUS IO"},
    {"label": "BOOL_IND_GREASELEVEL", "display": "GREASE LEVEL DI", "origin": "Params>Configuration>Main>Grease"},
    {"label": "BOOL_IND_GREASETR", "display": "GREASE TR DI", "origin": "Params>Configuration>Main>Grease"},
    {"label": "BOOL_IND_STARTSENSOR2", "display": "START SENSOR 2 IN DI", "origin": "Params>Configuration>Main>STATUS IO"},
    {"label": "BOOL_IND_HOLDTORUNRC2", "display": "HOLDTORUN RC2 DI", "origin": "Params>Configuration>Safety"},
    {"label": "BOOL_IND_TILTBAL", "display": "ROLLTILTBALANCED DI", "origin": "Params>Configuration>Main>STATUS IO"},
    {"label": "BOOL_IND_SDOSTART", "display": "BOOL_IND_SDOSTART", "origin": "??"},
    {"label": "BOOL_IND_SDOBUSY", "display": "BOOL_IND_SDOBUSY", "origin": "??"},
    {"label": "BOOL_IND_SDOOK", "display": "BOOL_IND_SDOOK", "origin": "??"},
    {"label": "BOOL_IND_RIGHTSUPPINTERLOCK", "display": "RIGHT SUPP INTERL. DI", "origin": "Params>Configuration>Main>STATUS IO"},
    {"label": "BOOL_IND_APPLYROT", "display": "BOOL_IND_APPLYROT", "origin": "??"},
    {"label": "BOOL_IND_REPEATEND", "display": "BOOL_IND_REPEATEND", "origin": "??"},
    {"label": "BOOL_IND_SYNCLOADIN", "display": "SYNC LOAD IN DI", "origin": "Params>Configuration>Main>SYNC IO"},
    {"label": "BOOL_IND_SYNCLOADOUT", "display": "BOOL_IND_SYNCLOADOUT", "origin": "??"},
    {"label": "BOOL_IND_SYNCUNLOADIN", "display": "SYNC UNLOAD IN DI", "origin": "Params>Configuration>Main>SYNC IO"},
    {"label": "BOOL_IND_SYNCUNLOADOUT", "display": "BOOL_IND_SYNCUNLOADOUT", "origin": "??"},
    {"label": "BOOL_IND_SYNCSTARTIN", "display": "SYNC START IN DI", "origin": "Params>Configuration>Main>SYNC IO"},
    {"label": "BOOL_IND_SYNCSTARTOUT", "display": "BOOL_IND_SYNCSTARTOUT", "origin": "??"},
    {"label": "BOOL_IND_FREE_141", "display": "BOOL_IND_FREE_141", "origin": "??"},
    {"label": "BOOL_IND_FREE_142", "display": "BOOL_IND_FREE_142", "origin": "??"},
    {"label": "BOOL_IND_FREE_143", "display": "BOOL_IND_FREE_143", "origin": "??"}
]
IN_IND_LABELS = [e["label"] for e in IN_IND_MAP]  # retrocompatibilità

OUT_IND_MAP = [
    {"label": "BOOL_IND_AUTOMODESEL", "display": "BOOL_IND_AUTOMODESEL", "origin": "??"},
    {"label": "BOOL_IND_TEACHMODESEL", "display": "BOOL_IND_TEACHMODESEL", "origin": "??"},
    {"label": "BOOL_IND_CYCLEMODESEL", "display": "BOOL_IND_CYCLEMODESEL", "origin": "??"},
    {"label": "BOOL_IND_STARTRESET", "display": "BOOL_IND_STARTRESET", "origin": "??"},
    {"label": "BOOL_IND_REMOTEMODESEL", "display": "BOOL_IND_REMOTEMODESEL", "origin": "??"},
    {"label": "BOOL_IND_EMGCYPB", "display": "BOOL_IND_EMGCYPB", "origin": "??"},
    {"label": "BOOL_IND_CONSOLE2MODESEL", "display": "BOOL_IND_CONSOLE2MODESEL", "origin": "??"},
    {"label": "BOOL_IND_CHROLLMODESEL", "display": "BOOL_IND_CHROLLMODESEL", "origin": "??"},
    {"label": "BOOL_IND_INENABLED", "display": "BOOL_IND_INENABLED", "origin": "??"},
    {"label": "BOOL_IND_DEBALNOTPRESS", "display": "BOOL_IND_DEBALNOTPRESS", "origin": "??"},
    {"label": "BOOL_IND_CONSOLE1MODESEL", "display": "BOOL_IND_CONSOLE1MODESEL", "origin": "??"},
    {"label": "BOOL_IND_SINGMOVSEL", "display": "BOOL_IND_SINGMOVSEL", "origin": "??"},
    {"label": "BOOL_IND_STARTIN", "display": "BOOL_IND_STARTIN", "origin": "??"},
    {"label": "BOOL_IND_STOPIN", "display": "BOOL_IND_STOPIN", "origin": "??"},
    {"label": "BOOL_IND_STARTEDIN", "display": "BOOL_IND_STARTEDIN", "origin": "??"},
    {"label": "BOOL_IND_HOLDTORUN", "display": "BOOL_IND_HOLDTORUN", "origin": "??"},
    {"label": "BOOL_IND_RTCOUPLED", "display": "BOOL_IND_RTCOUPLED", "origin": "??"},
    {"label": "BOOL_IND_LEFTSEL", "display": "BOOL_IND_LEFTSEL", "origin": "??"},
    {"label": "BOOL_IND_PINCHPRESS", "display": "BOOL_IND_PINCHPRESS", "origin": "??"},
    {"label": "BOOL_IND_RIGHTSEL", "display": "BOOL_IND_RIGHTSEL", "origin": "??"},
    {"label": "BOOL_IND_STARTSENSOR", "display": "BOOL_IND_STARTSENSOR", "origin": "??"},
    {"label": "BOOL_IND_MAINTRESET", "display": "BOOL_IND_MAINTRESET", "origin": "??"},
    {"label": "BOOL_IND_MANMODESEL", "display": "BOOL_IND_MANMODESEL", "origin": "??"},
    {"label": "BOOL_IND_TESTMODESEL", "display": "BOOL_IND_TESTMODESEL", "origin": "??"},
    {"label": "BOOL_IND_SEMIAUTOMODESEL", "display": "BOOL_IND_SEMIAUTOMODESEL", "origin": "??"},
    {"label": "BOOL_IND_HOLDTORUN2", "display": "BOOL_IND_HOLDTORUN2", "origin": "??"},
    {"label": "BOOL_IND_DISABLEBP1", "display": "BOOL_IND_DISABLEBP1", "origin": "??"},
    {"label": "BOOL_IND_DISABLEBP2", "display": "BOOL_IND_DISABLEBP2", "origin": "??"},
    {"label": "BOOL_IND_DISABLEBP3", "display": "BOOL_IND_DISABLEBP3", "origin": "??"},
    {"label": "BOOL_IND_DISABLEBP4", "display": "BOOL_IND_DISABLEBP4", "origin": "??"},
    {"label": "BOOL_IND_DISABLEBP5", "display": "BOOL_IND_DISABLEBP5", "origin": "??"},
    {"label": "BOOL_IND_DISABLEBP6", "display": "BOOL_IND_DISABLEBP6", "origin": "??"},
    {"label": "BOOL_IND_DISABLEBP7", "display": "BOOL_IND_DISABLEBP7", "origin": "??"},
    {"label": "BOOL_IND_DISABLEBP8", "display": "BOOL_IND_DISABLEBP8", "origin": "??"},
    {"label": "BOOL_IND_DISABLEBP9", "display": "BOOL_IND_DISABLEBP9", "origin": "??"},
    {"label": "BOOL_IND_DISABLEBP10", "display": "BOOL_IND_DISABLEBP10", "origin": "??"},
    {"label": "BOOL_IND_DISABLEBP11", "display": "BOOL_IND_DISABLEBP11", "origin": "??"},
    {"label": "BOOL_IND_DISABLEBP12", "display": "BOOL_IND_DISABLEBP12", "origin": "??"},
    {"label": "BOOL_IND_AUTOMODE", "display": "BOOL_IND_AUTOMODE", "origin": "??"},
    {"label": "BOOL_IND_AUTOCYCLEMODE", "display": "BOOL_IND_AUTOCYCLEMODE", "origin": "??"},
    {"label": "BOOL_IND_AUTOSTEPMODE", "display": "BOOL_IND_AUTOSTEPMODE", "origin": "??"},
    {"label": "BOOL_IND_SEMIAUTOMODE", "display": "BOOL_IND_SEMIAUTOMODE", "origin": "??"},
    {"label": "BOOL_IND_TEACHMODE", "display": "BOOL_IND_TEACHMODE", "origin": "??"},
    {"label": "BOOL_IND_MANMODE", "display": "BOOL_IND_MANMODE", "origin": "??"},
    {"label": "BOOL_IND_CONSOLE1MODE", "display": "BOOL_IND_CONSOLE1MODE", "origin": "??"},
    {"label": "BOOL_IND_CONSOLE2MODE", "display": "BOOL_IND_CONSOLE2MODE", "origin": "??"},
    {"label": "BOOL_IND_REMOTEMODE", "display": "BOOL_IND_REMOTEMODE", "origin": "??"},
    {"label": "BOOL_IND_CHROLLMODE", "display": "BOOL_IND_CHROLLMODE", "origin": "??"},
    {"label": "BOOL_IND_SINGMOVMODE", "display": "BOOL_IND_SINGMOVMODE", "origin": "??"},
    {"label": "BOOL_IND_MACHINESTARTED", "display": "MAC.START LIGHT DO", "origin": "Params>Configuration>Main>CMD IO"},
    {"label": "BOOL_IND_OUTSWENAB", "display": "BOOL_IND_OUTSWENAB", "origin": "??"},
    {"label": "BOOL_IND_GREASEPUMPON", "display": "BOOL_IND_GREASEPUMPON", "origin": "??"},
    {"label": "BOOL_IND_GREASEALARM", "display": "BOOL_IND_GREASEALARM", "origin": "??"},
    {"label": "BOOL_IND_GREASEPUMPALARM", "display": "BOOL_IND_GREASEPUMPALARM", "origin": "??"},
    {"label": "BOOL_IND_WAITINGFORSTART", "display": "MAC.READY LIGHT DO", "origin": "Params>Configuration>Main>CMD IO"},
    {"label": "BOOL_IND_POWEROFFFLAG", "display": "BOOL_IND_POWEROFFFLAG", "origin": "??"},
    {"label": "BOOL_IND_ALARMON", "display": "BOOL_IND_ALARMON", "origin": "??"},
    {"label": "BOOL_IND_STARTCMD", "display": "START CMD DO", "origin": "Params>Configuration>Main>CMD IO"},
    {"label": "BOOL_IND_ALARMSTOP", "display": "BOOL_IND_ALARMSTOP", "origin": "??"},
    {"label": "BOOL_IND_MAINTON", "display": "BOOL_IND_MAINTON", "origin": "??"},
    {"label": "BOOL_IND_RTFWDISABLED", "display": "BOOL_IND_RTFWDISABLED", "origin": "??"},
    {"label": "BOOL_IND_LEFTMEM", "display": "BOOL_IND_LEFTMEM", "origin": "??"},
    {"label": "BOOL_IND_RESETFLAG", "display": "BOOL_IND_RESETFLAG", "origin": "??"},
    {"label": "BOOL_IND_RIGHTMEM", "display": "BOOL_IND_RIGHTMEM", "origin": "??"},
    {"label": "BOOL_IND_OUTENABLED", "display": "BOOL_IND_OUTENABLED", "origin": "??"},
    {"label": "BOOL_IND_STOPCMD", "display": "STOP CMD DO", "origin": "Params>Configuration>Main>CMD IO"},
    {"label": "BOOL_IND_QUALITYENAB", "display": "BOOL_IND_QUALITYENAB", "origin": "??"},
    {"label": "BOOL_IND_TELESERVICEREQ", "display": "BOOL_IND_TELESERVICEREQ", "origin": "??"},
    {"label": "BOOL_IND_MICROMODESEL", "display": "BOOL_IND_MICROMODESEL", "origin": "??"},
    {"label": "BOOL_IND_APPLY", "display": "BOOL_IND_APPLY", "origin": "??"},
    {"label": "BOOL_IND_QUALITYEND", "display": "BOOL_IND_QUALITYEND", "origin": "??"},
    {"label": "BOOL_IND_AUTOSTARTINGBLINK", "display": "BOOL_IND_AUTOSTARTINGBLINK", "origin": "??"},
    {"label": "BOOL_IND_QUALITYGOOD", "display": "BOOL_IND_QUALITYGOOD", "origin": "??"},
    {"label": "BOOL_IND_PARTEND", "display": "BOOL_IND_PARTEND", "origin": "??"},
    {"label": "BOOL_IND_AUTOCORR", "display": "BOOL_IND_AUTOCORR", "origin": "??"},
    {"label": "BOOL_IND_PARTBEGIN", "display": "BOOL_IND_PARTBEGIN", "origin": "??"},
    {"label": "BOOL_IND_AUTOCORRSTARTED", "display": "BOOL_IND_AUTOCORRSTARTED", "origin": "??"},
    {"label": "BOOL_IND_TILTDISABLED","display": "BOOL_IND_TILTDISABLED", "origin": "??"},
    {"label": "BOOL_IND_EYEBENDON", "display": "EYEBEND ON DO", "origin": "Params>Configuration>Check Measurement"},
    {"label": "BOOL_IND_BP1", "display": "BP1 DO", "origin": "Params>Configuration>BP"},
    {"label": "BOOL_IND_BP2", "display": "BP2 DO", "origin": "Params>Configuration>BP"},
    {"label": "BOOL_IND_BP3", "display": "BP3 DO", "origin": "Params>Configuration>BP"},
    {"label": "BOOL_IND_BP4", "display": "BP4 DO", "origin": "Params>Configuration>BP"},
    {"label": "BOOL_IND_BP5", "display": "BP5 DO", "origin": "Params>Configuration>BP"},
    {"label": "BOOL_IND_BP6", "display": "BP6 DO", "origin": "Params>Configuration>BP"},
    {"label": "BOOL_IND_BP7", "display": "BP7 DO", "origin": "Params>Configuration>BP"},
    {"label": "BOOL_IND_BP8", "display": "BP8 DO", "origin": "Params>Configuration>BP"},
    {"label": "BOOL_IND_BP9", "display": "BP9 DO", "origin": "Params>Configuration>BP"},
    {"label": "BOOL_IND_BP10", "display": "BP10 DO", "origin": "Params>Configuration>BP"},
    {"label": "BOOL_IND_BP11", "display": "BP11 DO", "origin": "Params>Configuration>BP"},
    {"label": "BOOL_IND_BP12", "display": "BP12 DO", "origin": "Params>Configuration>BP"},
    {"label": "BOOL_IND_RCV0", "display": "BOOL_IND_RCV0", "origin": "??"},
    {"label": "BOOL_IND_RCV1", "display": "BOOL_IND_RCV1", "origin": "??"},
    {"label": "BOOL_IND_RCV2", "display": "BOOL_IND_RCV2", "origin": "??"},
    {"label": "BOOL_IND_RCV3", "display": "BOOL_IND_RCV3", "origin": "??"},
    {"label": "BOOL_IND_RCV4", "display": "BOOL_IND_RCV4", "origin": "??"},
    {"label": "BOOL_IND_RCUM", "display": "RC UM DO", "origin": "Params>Configuration>Radio Control OUT"},
    {"label": "BOOL_IND_RCLUP", "display": "RC LEFT UP DO", "origin": "Params>Configuration>Radio Control OUT"},
    {"label": "BOOL_IND_RCLDOWN", "display": "RC LEFT DOWN DO", "origin": "Params>Configuration>Radio Control OUT"},
    {"label": "BOOL_IND_RCRUP", "display": "RC RIGHT UP DO", "origin": "Params>Configuration>Radio Control OUT"},
    {"label": "BOOL_IND_RCRDOWN", "display": "RC RIGHT DOWN DO", "origin": "Params>Configuration>Radio Control OUT"},
    {"label": "BOOL_IND_RCBUP", "display": "RC BOTTOM UP DO", "origin": "Params>Configuration>Radio Control OUT"},
    {"label": "BOOL_IND_RCBDOWN", "display": "RC BOTTOM DOWN DO", "origin": "Params>Configuration>Radio Control OUT"},
    {"label": "BOOL_IND_RCTLEFT", "display": "RC TOP LEFT DO", "origin": "Params>Configuration>Radio Control OUT"},
    {"label": "BOOL_IND_RCTRIGHT", "display": "RC TOP RIGHT DO", "origin": "Params>Configuration>Radio Control OUT"},
    {"label": "BOOL_IND_EMGCYRESETBTN", "display": "EMGCY RESET BTN DO", "origin": "Params>Configuration>Safety"},
    {"label": "BOOL_IND_RCALARM", "display": "RC ALARM DO", "origin": "Params>Configuration>Radio Control OUT"},
    {"label": "BOOL_IND_EMGCYRESET", "display": "EMGCY RESET LIGHT DO", "origin": "Params>Configuration>Safety"},
    {"label": "BOOL_IND_INVERTERRESET", "display": "BOOL_IND_INVERTERRESET", "origin": "??"},
    {"label": "BOOL_IND_INVERTERALARM", "display": "BOOL_IND_INVERTERALARM", "origin": "??"},
    {"label": "BOOL_IND_AUTOSTARTING", "display": "BOOL_IND_AUTOSTARTING", "origin": "??"},
    {"label": "BOOL_IND_PINCHPRESSFRONTREAR", "display": "PINC PRESS AR DO", "origin": "Params>Configuration>Pinch Preload"},
    {"label": "BOOL_IND_PINCHPRESSFRONTREAR2", "display": "PINC PRESS AR2 DO", "origin": "Params>Configuration>Pinch Preload"},
    {"label": "BOOL_IND_HOLDTORUNRC", "display": "BOOL_IND_HOLDTORUNRC", "origin": "??"},
    {"label": "BOOL_IND_PRELOADUP", "display": "BOOL_IND_PRELOADUP", "origin": "??"},
    {"label": "BOOL_IND_PRELOADPINCHDISABLED", "display": "BOOL_IND_PRELOADPINCHDISABLED", "origin": "??"},
    {"label": "BOOL_IND_PARTMAN", "display": "BOOL_IND_PARTMAN", "origin": "??"},
    {"label": "BOOL_IND_PARTMANBEGIN", "display": "BOOL_IND_PARTMANBEGIN", "origin": "??"},
    {"label": "BOOL_IND_FREE_118", "display": "BOOL_IND_FREE_118", "origin": "??"},
    {"label": "BOOL_IND_FREE_119", "display": "BOOL_IND_FREE_119", "origin": "??"},
    {"label": "BOOL_IND_FREE_120", "display": "BOOL_IND_FREE_120", "origin": "??"},
    {"label": "BOOL_IND_FREE_121", "display": "BOOL_IND_FREE_121", "origin": "??"},
    {"label": "BOOL_IND_FREE_122", "display": "BOOL_IND_FREE_122", "origin": "??"},
    {"label": "BOOL_IND_FREE_123", "display": "BOOL_IND_FREE_123", "origin": "??"},
    {"label": "BOOL_IND_FREE_124", "display": "BOOL_IND_FREE_124", "origin": "??"},
    {"label": "BOOL_IND_FREE_125", "display": "BOOL_IND_FREE_125", "origin": "??"},
    {"label": "BOOL_IND_FREE_126", "display": "BOOL_IND_FREE_126", "origin": "??"},
    {"label": "BOOL_IND_FREE_127", "display": "BOOL_IND_FREE_127", "origin": "??"},
    {"label": "BOOL_IND_FREE_128", "display": "BOOL_IND_FREE_128", "origin": "??"},
    {"label": "BOOL_IND_FREE_129", "display": "BOOL_IND_FREE_129", "origin": "??"},
    {"label": "BOOL_IND_FREE_130", "display": "BOOL_IND_FREE_130", "origin": "??"},
    {"label": "BOOL_IND_FREE_131", "display": "BOOL_IND_FREE_131", "origin": "??"},
    {"label": "BOOL_IND_FREE_132", "display": "BOOL_IND_FREE_132", "origin": "??"},
    {"label": "BOOL_IND_FREE_133", "display": "BOOL_IND_FREE_133", "origin": "??"},
    {"label": "BOOL_IND_FREE_134", "display": "BOOL_IND_FREE_134", "origin": "??"},
    {"label": "BOOL_IND_FREE_135", "display": "BOOL_IND_FREE_135", "origin": "??"},
    {"label": "BOOL_IND_FREE_136", "display": "SYNC LOAD OUT DO", "origin": "Params>Configuration>Main>SYNC IO"},
    {"label": "BOOL_IND_FREE_137", "display": "BOOL_IND_FREE_137", "origin": "??"},
    {"label": "BOOL_IND_FREE_138", "display": "SYNC UNLOAD OUT DO", "origin": "Params>Configuration>Main>SYNC IO"},
    {"label": "BOOL_IND_FREE_139", "display": "BOOL_IND_FREE_139", "origin": "??"},
    {"label": "BOOL_IND_FREE_140", "display": "SYNC START OUT DO", "origin": "Params>Configuration>Main>SYNC IO"},
    {"label": "BOOL_IND_FREE_141", "display": "BOOL_IND_FREE_141", "origin": "??"},
    {"label": "BOOL_IND_FREE_142", "display": "BOOL_IND_FREE_142", "origin": "??"},
    {"label": "BOOL_IND_FREE_143", "display": "BOOL_IND_FREE_143", "origin": "??"}
]
OUT_IND_LABELS = [e["label"] for e in OUT_IND_MAP]  # retrocompatibilità

Type_AxisParam_Map = {
    "boolval": {
        "ASSE_BOOL_CONFIG": {"display": "ASSE_BOOL_CONFIG", "origin":"??"},
        "ASSE_BOOL_BP1": {"display": "ASSE_BOOL_BP1", "origin":"??"},
        "ASSE_BOOL_BP2": {"display": "ASSE_BOOL_BP2", "origin":"??"},
        "ASSE_BOOL_BP3": {"display": "ASSE_BOOL_BP3", "origin":"??"},
        "ASSE_BOOL_BP4": {"display": "ASSE_BOOL_BP4", "origin":"??"},
        "ASSE_BOOL_BP5": {"display": "ASSE_BOOL_BP5", "origin":"??"},
        "ASSE_BOOL_BP6": {"display": "ASSE_BOOL_BP6", "origin":"??"},
        "ASSE_BOOL_BP7": {"display": "ASSE_BOOL_BP7", "origin":"??"},
        "ASSE_BOOL_BP8": {"display": "ASSE_BOOL_BP8", "origin":"??"},
        "ASSE_BOOL_BP9": {"display": "ASSE_BOOL_BP9", "origin":"??"},
        "ASSE_BOOL_BP10": {"display": "ASSE_BOOL_BP10", "origin":"??"},
        "ASSE_BOOL_BP11": {"display": "ASSE_BOOL_BP11", "origin":"??"},
        "ASSE_BOOL_BP12": {"display": "ASSE_BOOL_BP12", "origin":"??"},
        "ASSE_BOOL_FLAGCOUPMAX": {"display": "ASSE_BOOL_FLAGCOUPMAX", "origin":"??"},
        "ASSE_BOOL_SHOWMAN": {"display": "ASSE_BOOL_SHOWMAN", "origin":"??"},
        "ASSE_BOOL_SHOWAUTO": {"display": "ASSE_BOOL_SHOWAUTO", "origin":"??"},
        "ASSE_BOOL_ENABAXIS": {"display": "ASSE_BOOL_ENABAXIS", "origin":"??"},
        "ASSE_BOOL_ENABINTERP": {"display": "ASSE_BOOL_ENABINTERP", "origin":"??"},
        "ASSE_BOOL_ENABTEACH": {"display": "ASSE_BOOL_ENABTEACH", "origin":"??"},
        "ASSE_BOOL_ENABSMAX": {"display": "ASSE_BOOL_ENABSMAX", "origin":"??"},
        "ASSE_BOOL_ENABSMIN": {"display": "ASSE_BOOL_ENABSMIN", "origin":"??"},
        "ASSE_BOOL_ENABSHH": {"display": "ASSE_BOOL_ENABSHH", "origin":"??"},
        "ASSE_BOOL_ENABSH": {"display": "ASSE_BOOL_ENABSH", "origin":"??"},
        "ASSE_BOOL_ENABSL": {"display": "ASSE_BOOL_ENABSL", "origin":"??"},
        "ASSE_BOOL_ENABSLL": {"display": "ASSE_BOOL_ENABSLL", "origin":"??"},
        "ASSE_BOOL_CONFIGUP": {"display": "ASSE_BOOL_CONFIGUP", "origin":"??"},
        "ASSE_BOOL_CONFIGDOWN": {"display": "ASSE_BOOL_CONFIGDOWN", "origin":"??"},
        "ASSE_BOOL_FLAGINV": {"display": "ASSE_BOOL_FLAGINV", "origin":"??"},
        "ASSE_BOOL_CHECKSTOPDISABLED": {"display": "ASSE_BOOL_CHECKSTOPDISABLED", "origin":"??"},
        "ASSE_BOOL_SHOWDELTA": {"display": "ASSE_BOOL_SHOWDELTA", "origin":"??"},
        "ASSE_BOOL_DISABLEDELTA": {"display": "ASSE_BOOL_DISABLEDELTA", "origin":"??"},
        "ASSE_BOOL_ENABSH0": {"display": "ASSE_BOOL_ENABSH0", "origin":"??"},
        "ASSE_BOOL_ENABSL0": {"display": "ASSE_BOOL_ENABSL0", "origin":"??"},
        "ASSE_BOOL_MANSPUP": {"display": "ASSE_BOOL_MANSPUP", "origin":"??"},
        "ASSE_BOOL_MANSPDOWN": {"display": "ASSE_BOOL_MANSPDOWN", "origin":"??"},
        "ASSE_BOOL_SHOWDELTATAB": {"display": "ASSE_BOOL_SHOWDELTATAB", "origin":"??"},
        "ASSE_BOOL_NOMACHINESTARTED": {"display": "ASSE_BOOL_NOMACHINESTARTED", "origin":"??"},
        "ASSE_BOOL_AXISNOMOVE": {"display": "ASSE_BOOL_AXISNOMOVE", "origin":"??"},
        "ASSE_BOOL_COUPCALC": {"display": "ASSE_BOOL_COUPCALC", "origin":"??"},
        "ASSE_BOOL_FREE_39": {"display": "ASSE_BOOL_FREE_39", "origin":"??"},
        "ASSE_BOOL_FREE_40": {"display": "ASSE_BOOL_FREE_40", "origin":"??"},
    },
    "intval": {
        "ASSE_INT_MASTER": {"display": "ASSE_INT_MASTER", "origin":"??"},
        "ASSE_INT_FEEDBACK": {"display": "ASSE_INT_FEEDBACK", "origin":"??"},
        "ASSE_INT_INPUT": {"display": "ASSE_INT_INPUT", "origin":"??"},
        "ASSE_INT_INPUT2": {"display": "ASSE_INT_INPUT2", "origin":"??"},
        "ASSE_INT_INPUT3": {"display": "ASSE_INT_INPUT3", "origin":"??"},
        "ASSE_INT_INPUT4": {"display": "ASSE_INT_INPUT4", "origin":"??"},
        "ASSE_INT_OUTPUT1": {"display": "ASSE_INT_OUTPUT1", "origin":"??"},
        "ASSE_INT_OUTPUT2": {"display": "ASSE_INT_OUTPUT2", "origin":"??"},
        "ASSE_INT_OUTPUT3": {"display": "ASSE_INT_OUTPUT3", "origin":"??"},
        "ASSE_INT_OUTPUT4": {"display": "ASSE_INT_OUTPUT4", "origin":"??"},
        "ASSE_INT_LABELTYPE": {"display": "ASSE_INT_LABELTYPE", "origin":"??"},
        "ASSE_INT_LABELROW": {"display": "ASSE_INT_LABELROW", "origin":"??"},
        "ASSE_INT_LABELCOL": {"display": "ASSE_INT_LABELCOL", "origin":"??"},
        "ASSE_INT_LABELNTOT": {"display": "ASSE_INT_LABELNTOT", "origin":"??"},
        "ASSE_INT_LABELNDEC": {"display": "ASSE_INT_LABELNDEC", "origin":"??"},
        "ASSE_INT_LABELROWIMP": {"display": "ASSE_INT_LABELROWIMP", "origin":"??"},
        "ASSE_INT_LABELCOLIMP": {"display": "ASSE_INT_LABELCOLIMP", "origin":"??"},
        "ASSE_INT_LABELNTOTIMP": {"display": "ASSE_INT_LABELNTOTIMP", "origin":"??"},
        "ASSE_INT_LABELNDECIMP": {"display": "ASSE_INT_LABELNDECIMP", "origin":"??"},
        "ASSE_INT_SUPLSIND": {"display": "ASSE_INT_SUPLSIND", "origin":"??"},
        "ASSE_INT_INFLSIND": {"display": "ASSE_INT_INFLSIND", "origin":"??"},
        "ASSE_INT_P1": {"display": "ASSE_INT_P1", "origin":"??"},
        "ASSE_INT_P2": {"display": "ASSE_INT_P2", "origin":"??"},
        "ASSE_INT_TIMEOUT1": {"display": "ASSE_INT_TIMEOUT1", "origin":"??"},
        "ASSE_INT_TIMEOUT2": {"display": "ASSE_INT_TIMEOUT2", "origin":"??"},
        "ASSE_INT_BOOSTVAL": {"display": "ASSE_INT_BOOSTVAL", "origin":"??"},
        "ASSE_INT_TIPOMISURA": {"display": "ASSE_INT_TIPOMISURA", "origin":"??"},
        "ASSE_INT_DEFSPEED": {"display": "ASSE_INT_DEFSPEED", "origin":"??"},
        "ASSE_INT_MOVEMODE": {"display": "ASSE_INT_MOVEMODE", "origin":"??"},
        "ASSE_INT_INTERPGROUP": {"display": "ASSE_INT_INTERPGROUP", "origin":"??"},
        "ASSE_INT_ALTFB": {"display": "ASSE_INT_ALTFB", "origin":"??"},
        "ASSE_INT_ALTFBDIG": {"display": "ASSE_INT_ALTFBDIG", "origin":"??"},
        "ASSE_INT_INDSHH": {"display": "ASSE_INT_INDSHH", "origin":"??"},
        "ASSE_INT_INDSH": {"display": "ASSE_INT_INDSH", "origin":"??"},
        "ASSE_INT_INDSL": {"display": "ASSE_INT_INDSL", "origin":"??"},
        "ASSE_INT_INDSLL": {"display": "ASSE_INT_INDSLL", "origin":"??"},
        "ASSE_INT_SAFETYUPIND1": {"display": "SAFETY1 UP", "origin":"Axes\t→\t[{}]{}\t→\tSafety/Interlock"},
        "ASSE_INT_SAFETYUPIND2": {"display": "SAFETY2 UP", "origin":"Axes\t→\t[{}]{}\t→\tSafety/Interlock"},
        "ASSE_INT_SAFETYUPIND3": {"display": "SAFETY3 UP", "origin":"Axes\t→\t[{}]{}\t→\tSafety/Interlock"},
        "ASSE_INT_SAFETYUPIND4": {"display": "SAFETY4 UP", "origin":"Axes\t→\t[{}]{}\t→\tSafety/Interlock"},
        "ASSE_INT_SAFETYUPIND5": {"display": "SAFETY5 UP", "origin":"Axes\t→\t[{}]{}\t→\tSafety/Interlock"},
        "ASSE_INT_SAFETYUPIND6": {"display": "SAFETY6 UP", "origin":"Axes\t→\t[{}]{}\t→\tSafety/Interlock"},
        "ASSE_INT_INDSH0": {"display": "ASSE_INT_INDSH0", "origin":"??"},
        "ASSE_INT_INDSL0": {"display": "ASSE_INT_INDSL0", "origin":"??"},
        "ASSE_INT_INDMEM": {"display": "ASSE_INT_INDMEM", "origin":"??"},
        "ASSE_INT_PERACQ": {"display": "ASSE_INT_PERACQ", "origin":"??"},
        "ASSE_INT_NUMTIMEOUT": {"display": "ASSE_INT_NUMTIMEOUT", "origin":"??"},
        "ASSE_INT_PERVELAVG": {"display": "ASSE_INT_PERVELAVG", "origin":"??"},
        "ASSE_INT_SAFETYDOWNIND1": {"display": "SAFETY1 DOWN", "origin":"Axes\t→\t[{}]{}\t→\tSafety/Interlock"},
        "ASSE_INT_SAFETYDOWNIND2": {"display": "SAFETY2 DOWN", "origin":"Axes\t→\t[{}]{}\t→\tSafety/Interlock"},
        "ASSE_INT_SAFETYDOWNIND3": {"display": "SAFETY3 DOWN", "origin":"Axes\t→\t[{}]{}\t→\tSafety/Interlock"},
        "ASSE_INT_SAFETYDOWNIND4": {"display": "SAFETY4 DOWN", "origin":"Axes\t→\t[{}]{}\t→\tSafety/Interlock"},
        "ASSE_INT_SAFETYDOWNIND5": {"display": "SAFETY5 DOWN", "origin":"Axes\t→\t[{}]{}\t→\tSafety/Interlock"},
        "ASSE_INT_SAFETYDOWNIND6": {"display": "SAFETY6 DOWN", "origin":"Axes\t→\t[{}]{}\t→\tSafety/Interlock"},
        "ASSE_INT_DELAYUP": {"display": "ASSE_INT_DELAYUP", "origin":"??"},
        "ASSE_INT_DELAYDOWN": {"display": "ASSE_INT_DELAYDOWN", "origin":"??"},
        "ASSE_INT_MAXVELPERC": {"display": "ASSE_INT_MAXVELPERC", "origin":"??"},
        "ASSE_INT_DECOUPMASTER": {"display": "ASSE_INT_DECOUPMASTER", "origin":"??"},
        "ASSE_INT_DECOUPMASTER2": {"display": "ASSE_INT_DECOUPMASTER2", "origin":"??"},
        "ASSE_INT_DECOUPMASTER3": {"display": "ASSE_INT_DECOUPMASTER3", "origin":"??"},
        "ASSE_INT_DECOUPMASTER4": {"display": "ASSE_INT_DECOUPMASTER4", "origin":"??"},
        "ASSE_INT_DECOUPMASTER5": {"display": "ASSE_INT_DECOUPMASTER5", "origin":"??"},
        "ASSE_INT_DECOUPMASTER6": {"display": "ASSE_INT_DECOUPMASTER6", "origin":"??"},
        "ASSE_INT_PS": {"display": "ASSE_INT_PS", "origin":"??"},
        "ASSE_INT_BWVSLOW": {"display": "ASSE_INT_BWVSLOW", "origin":"??"},
        "ASSE_INT_FWVSLOW": {"display": "ASSE_INT_FWVSLOW", "origin":"??"},
        "ASSE_INT_PS2": {"display": "ASSE_INT_PS2", "origin":"??"},
        "ASSE_INT_PS3": {"display": "ASSE_INT_PS3", "origin":"??"},
        "ASSE_INT_AXISCOUPCHECK": {"display": "ASSE_INT_AXISCOUPCHECK", "origin":"??"},
        "ASSE_INT_TEACHMINMULT": {"display": "ASSE_INT_TEACHMINMULT", "origin":"??"},
        "ASSE_INT_FREE_70": {"display": "ASSE_INT_FREE_70", "origin":"??"},
        "ASSE_INT_FREE_71": {"display": "ASSE_INT_FREE_71", "origin":"??"},
        "ASSE_INT_PID": {"display": "ASSE_INT_PID", "origin":"??"},
        "ASSE_INT_GRAFIND": {"display": "ASSE_INT_GRAFIND", "origin":"??"},
        "ASSE_INT_DELTA1": {"display": "ASSE_INT_DELTA1", "origin":"??"},
        "ASSE_INT_OPTPARAMIND": {"display": "ASSE_INT_OPTPARAMIND", "origin":"??"},
        "ASSE_INT_DISABLEBP1": {"display": "ASSE_INT_DISABLEBP1", "origin":"??"},
        "ASSE_INT_DISABLEBP2": {"display": "ASSE_INT_DISABLEBP2", "origin":"??"},
        "ASSE_INT_DISABLEBP3": {"display": "ASSE_INT_DISABLEBP3", "origin":"??"},
        "ASSE_INT_DISABLEBP4": {"display": "ASSE_INT_DISABLEBP4", "origin":"??"},
        "ASSE_INT_DISABLEBP5": {"display": "ASSE_INT_DISABLEBP5", "origin":"??"},
        "ASSE_INT_DISABLEBP6": {"display": "ASSE_INT_DISABLEBP6", "origin":"??"},
        "ASSE_INT_DISABLEBP7": {"display": "ASSE_INT_DISABLEBP7", "origin":"??"},
        "ASSE_INT_DISABLEBP8": {"display": "ASSE_INT_DISABLEBP8", "origin":"??"},
        "ASSE_INT_DISABLEBP9": {"display": "ASSE_INT_DISABLEBP9", "origin":"??"},
        "ASSE_INT_DISABLEBP10": {"display": "ASSE_INT_DISABLEBP10", "origin":"??"},
        "ASSE_INT_DISABLEBP11": {"display": "ASSE_INT_DISABLEBP11", "origin":"??"},
        "ASSE_INT_DISABLEBP12": {"display": "ASSE_INT_DISABLEBP12", "origin":"??"},
        "ASSE_INT_OPTPARAM1": {"display": "ASSE_INT_OPTPARAM1", "origin":"??"},
        "ASSE_INT_OPTPARAM2": {"display": "ASSE_INT_OPTPARAM2", "origin":"??"},
        "ASSE_INT_OPTPARAM3": {"display": "ASSE_INT_OPTPARAM3", "origin":"??"},
        "ASSE_INT_HOLDTORUNTYPE": {"display": "ASSE_INT_HOLDTORUNTYPE", "origin":"??"},
        "ASSE_INT_FREE_92": {"display": "ASSE_INT_FREE_92", "origin":"??"},
        "ASSE_INT_FREE_93": {"display": "ASSE_INT_FREE_93", "origin":"??"},
        "ASSE_INT_FREE_94": {"display": "ASSE_INT_FREE_94", "origin":"??"},
    },
    "realvalcfg": {
        "ASSE_REAL_SRTUP": {"display": "ASSE_REAL_SRTUP", "origin": "??"},
        "ASSE_REAL_SRTDOWN": {"display": "ASSE_REAL_SRTDOWN", "origin": "??"},
        "ASSE_REAL_COEFFUP": {"display": "ASSE_REAL_COEFFUP", "origin": "??"},
        "ASSE_REAL_COEFFDOWN": {"display": "ASSE_REAL_COEFFDOWN", "origin": "??"},
        "ASSE_REAL_P1UP": {"display": "ASSE_REAL_P1UP", "origin": "??"},
        "ASSE_REAL_P1DOWN": {"display": "ASSE_REAL_P1DOWN", "origin": "??"},
        "ASSE_REAL_P2UP": {"display": "ASSE_REAL_P2UP", "origin": "??"},
        "ASSE_REAL_P2DOWN": {"display": "ASSE_REAL_P2DOWN", "origin": "??"},
        "ASSE_REAL_SYSPRESSUP1": {"display": "ASSE_REAL_SYSPRESSUP1", "origin": "??"},
        "ASSE_REAL_SYSPRESSDOWN1": {"display": "ASSE_REAL_SYSPRESSDOWN1", "origin": "??"},
        "ASSE_REAL_SYSPRESSUP2": {"display": "ASSE_REAL_SYSPRESSUP2", "origin": "??"},
        "ASSE_REAL_SYSPRESSDOWN2": {"display": "ASSE_REAL_SYSPRESSDOWN2", "origin": "??"},
        "ASSE_REAL_SYSPRESSUP3": {"display": "ASSE_REAL_SYSPRESSUP3", "origin": "??"},
        "ASSE_REAL_SYSPRESSDOWN3": {"display": "ASSE_REAL_SYSPRESSDOWN3", "origin": "??"},
        "ASSE_REAL_BWVMAX": {"display": "ASSE_REAL_BWVMAX", "origin": "??"},
        "ASSE_REAL_DSMAXDOWN": {"display": "ASSE_REAL_DSMAXDOWN", "origin": "??"},
        "ASSE_REAL_DSMAXUP": {"display": "ASSE_REAL_DSMAXUP", "origin": "??"},
        "ASSE_REAL_FWVMAX": {"display": "ASSE_REAL_FWVMAX", "origin": "??"},
        "ASSE_REAL_SMAX": {"display": "ASSE_REAL_SMAX", "origin": "??"},
        "ASSE_REAL_SMIN": {"display": "ASSE_REAL_SMIN", "origin": "??"},
        "ASSE_REAL_SSUP": {"display": "ASSE_REAL_SSUP", "origin": "??"},
        "ASSE_REAL_SINF": {"display": "ASSE_REAL_SINF", "origin": "??"},
        "ASSE_REAL_VMINSTARTED": {"display": "ASSE_REAL_VMINSTARTED", "origin": "??"},
        "ASSE_REAL_SHH": {"display": "ASSE_REAL_SHH", "origin": "??"},
        "ASSE_REAL_SH": {"display": "ASSE_REAL_SH", "origin": "??"},
        "ASSE_REAL_SL": {"display": "ASSE_REAL_SL", "origin": "??"},
        "ASSE_REAL_SLL": {"display": "ASSE_REAL_SLL", "origin": "??"},
        "ASSE_REAL_TILTMAX": {"display": "ASSE_REAL_TILTMAX", "origin": "??"},
        "ASSE_REAL_MASTERMULT": {"display": "ASSE_REAL_MASTERMULT", "origin": "??"},
        "ASSE_REAL_MASTERDELTAMIN": {"display": "ASSE_REAL_MASTERDELTAMIN", "origin": "??"},
        "ASSE_REAL_MASTERKSRS": {"display": "ASSE_REAL_MASTERKSRS", "origin": "??"},
        "ASSE_REAL_SLAVEVRESET": {"display": "ASSE_REAL_SLAVEVRESET", "origin": "??"},
        "ASSE_REAL_SLAVEVMIN": {"display": "ASSE_REAL_SLAVEVMIN", "origin": "??"},
        "ASSE_REAL_SLAVEDELTATSTART": {"display": "ASSE_REAL_SLAVEDELTATSTART", "origin": "??"},
        "ASSE_REAL_OUTKP": {"display": "ASSE_REAL_OUTKP", "origin": "??"},
        "ASSE_REAL_OUTDELTAT": {"display": "ASSE_REAL_OUTDELTAT", "origin": "??"},
        "ASSE_REAL_SH0": {"display": "ASSE_REAL_SH0", "origin": "??"},
        "ASSE_REAL_SL0": {"display": "ASSE_REAL_SL0", "origin": "??"},
        "ASSE_REAL_TILTMAXDOWN": {"display": "ASSE_REAL_TILTMAXDOWN", "origin": "??"},
        "ASSE_REAL_FREE_39": {"display": "ASSE_REAL_FREE_39", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGUP": {"display": "ASSE_REAL_DELTAMOVINGUP", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGDOWN": {"display": "ASSE_REAL_DELTAMOVINGDOWN", "origin": "??"},
        "ASSE_REAL_DELTADIV": {"display": "ASSE_REAL_DELTADIV", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGSUPUP": {"display": "ASSE_REAL_DELTAMOVINGSUPUP", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGINFUP": {"display": "ASSE_REAL_DELTAMOVINGINFUP", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGSUPDOWN": {"display": "ASSE_REAL_DELTAMOVINGSUPDOWN", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGINFDOWN": {"display": "ASSE_REAL_DELTAMOVINGINFDOWN", "origin": "??"},
        "ASSE_REAL_DELTAAUTO": {"display": "ASSE_REAL_DELTAAUTO", "origin": "??"},
        "ASSE_REAL_BWACCMAX": {"display": "ASSE_REAL_BWACCMAX", "origin": "??"},
        "ASSE_REAL_FWACCMAX": {"display": "ASSE_REAL_FWACCMAX", "origin": "??"},
        "ASSE_REAL_OPTPARAM1": {"display": "ASSE_REAL_OPTPARAM1", "origin": "??"},
        "ASSE_REAL_OPTPARAM2": {"display": "ASSE_REAL_OPTPARAM2", "origin": "??"},
        "ASSE_REAL_OPTPARAM3": {"display": "ASSE_REAL_OPTPARAM3", "origin": "??"},
        "ASSE_REAL_AXISCOUPMIN": {"display": "ASSE_REAL_AXISCOUPMIN", "origin": "??"},
        "ASSE_REAL_FREE_54": {"display": "ASSE_REAL_FREE_54", "origin": "??"},

    },
    "realval": {
        "ASSE_REAL_SRTUP": {"display": "ASSE_REAL_SRTUP", "origin":"??"},
        "ASSE_REAL_SRTDOWN": {"display": "ASSE_REAL_SRTDOWN", "origin":"??"},
        "ASSE_REAL_COEFFUP": {"display": "ASSE_REAL_COEFFUP", "origin":"??"},
        "ASSE_REAL_COEFFDOWN": {"display": "ASSE_REAL_COEFFDOWN", "origin":"??"},
        "ASSE_REAL_P1UP": {"display": "ASSE_REAL_P1UP", "origin":"??"},
        "ASSE_REAL_P1DOWN": {"display": "ASSE_REAL_P1DOWN", "origin":"??"},
        "ASSE_REAL_P2UP": {"display": "ASSE_REAL_P2UP", "origin":"??"},
        "ASSE_REAL_P2DOWN": {"display": "ASSE_REAL_P2DOWN", "origin":"??"},
        "ASSE_REAL_SYSPRESSUP1": {"display": "ASSE_REAL_SYSPRESSUP1", "origin":"??"},
        "ASSE_REAL_SYSPRESSDOWN1": {"display": "ASSE_REAL_SYSPRESSDOWN1", "origin":"??"},
        "ASSE_REAL_SYSPRESSUP2": {"display": "ASSE_REAL_SYSPRESSUP2", "origin":"??"},
        "ASSE_REAL_SYSPRESSDOWN2": {"display": "ASSE_REAL_SYSPRESSDOWN2", "origin":"??"},
        "ASSE_REAL_SYSPRESSUP3": {"display": "ASSE_REAL_SYSPRESSUP3", "origin":"??"},
        "ASSE_REAL_SYSPRESSDOWN3": {"display": "ASSE_REAL_SYSPRESSDOWN3", "origin":"??"},
        "ASSE_REAL_BWVMAX": {"display": "ASSE_REAL_BWVMAX", "origin":"??"},
        "ASSE_REAL_DSMAXDOWN": {"display": "ASSE_REAL_DSMAXDOWN", "origin":"??"},
        "ASSE_REAL_DSMAXUP": {"display": "ASSE_REAL_DSMAXUP", "origin":"??"},
        "ASSE_REAL_FWVMAX": {"display": "ASSE_REAL_FWVMAX", "origin":"??"},
        "ASSE_REAL_SMAX": {"display": "ASSE_REAL_SMAX", "origin":"??"},
        "ASSE_REAL_SMIN": {"display": "ASSE_REAL_SMIN", "origin":"??"},
        "ASSE_REAL_SSUP": {"display": "ASSE_REAL_SSUP", "origin":"??"},
        "ASSE_REAL_SINF": {"display": "ASSE_REAL_SINF", "origin":"??"},
        "ASSE_REAL_VMINSTARTED": {"display": "ASSE_REAL_VMINSTARTED", "origin":"??"},
        "ASSE_REAL_SHH": {"display": "ASSE_REAL_SHH", "origin":"??"},
        "ASSE_REAL_SH": {"display": "ASSE_REAL_SH", "origin":"??"},
        "ASSE_REAL_SL": {"display": "ASSE_REAL_SL", "origin":"??"},
        "ASSE_REAL_SLL": {"display": "ASSE_REAL_SLL", "origin":"??"},
        "ASSE_REAL_TILTMAX": {"display": "ASSE_REAL_TILTMAX", "origin":"??"},
        "ASSE_REAL_MASTERMULT": {"display": "ASSE_REAL_MASTERMULT", "origin":"??"},
        "ASSE_REAL_MASTERDELTAMIN": {"display": "ASSE_REAL_MASTERDELTAMIN", "origin":"??"},
        "ASSE_REAL_MASTERKSRS": {"display": "ASSE_REAL_MASTERKSRS", "origin":"??"},
        "ASSE_REAL_SLAVEVRESET": {"display": "ASSE_REAL_SLAVEVRESET", "origin":"??"},
        "ASSE_REAL_SLAVEVMIN": {"display": "ASSE_REAL_SLAVEVMIN", "origin":"??"},
        "ASSE_REAL_SLAVEDELTATSTART": {"display": "ASSE_REAL_SLAVEDELTATSTART", "origin":"??"},
        "ASSE_REAL_OUTKP": {"display": "ASSE_REAL_OUTKP", "origin":"??"},
        "ASSE_REAL_OUTDELTAT": {"display": "ASSE_REAL_OUTDELTAT", "origin":"??"},
        "ASSE_REAL_SH0": {"display": "ASSE_REAL_SH0", "origin":"??"},
        "ASSE_REAL_SL0": {"display": "ASSE_REAL_SL0", "origin":"??"},
        "ASSE_REAL_TILTMAXDOWN": {"display": "ASSE_REAL_TILTMAXDOWN", "origin":"??"},
        "ASSE_REAL_FREE_39": {"display": "ASSE_REAL_FREE_39", "origin":"??"},
        "ASSE_REAL_DELTAMOVINGUP": {"display": "ASSE_REAL_DELTAMOVINGUP", "origin":"??"},
        "ASSE_REAL_DELTAMOVINGDOWN": {"display": "ASSE_REAL_DELTAMOVINGDOWN", "origin":"??"},
        "ASSE_REAL_DELTADIV": {"display": "ASSE_REAL_DELTADIV", "origin":"??"},
        "ASSE_REAL_DELTAMOVINGSUPUP": {"display": "ASSE_REAL_DELTAMOVINGSUPUP", "origin":"??"},
        "ASSE_REAL_DELTAMOVINGINFUP": {"display": "ASSE_REAL_DELTAMOVINGINFUP", "origin":"??"},
        "ASSE_REAL_DELTAMOVINGSUPDOWN": {"display": "ASSE_REAL_DELTAMOVINGSUPDOWN", "origin":"??"},
        "ASSE_REAL_DELTAMOVINGINFDOWN": {"display": "ASSE_REAL_DELTAMOVINGINFDOWN", "origin":"??"},
        "ASSE_REAL_DELTAAUTO": {"display": "ASSE_REAL_DELTAAUTO", "origin":"??"},
        "ASSE_REAL_BWACCMAX": {"display": "ASSE_REAL_BWACCMAX", "origin":"??"},
        "ASSE_REAL_FWACCMAX": {"display": "ASSE_REAL_FWACCMAX", "origin":"??"},
        "ASSE_REAL_OPTPARAM1": {"display": "ASSE_REAL_OPTPARAM1", "origin":"??"},
        "ASSE_REAL_OPTPARAM2": {"display": "ASSE_REAL_OPTPARAM2", "origin":"??"},
        "ASSE_REAL_OPTPARAM3": {"display": "ASSE_REAL_OPTPARAM3", "origin":"??"},
        "ASSE_REAL_AXISCOUPMIN": {"display": "ASSE_REAL_AXISCOUPMIN", "origin":"??"},
        "ASSE_REAL_FREE_54": {"display": "ASSE_REAL_FREE_54", "origin":"??"},

    },
    "fcval": {
        "ASSE_REAL_SRTUP": {"label": "ASSE_REAL_SRTUP", "origin": "??"},
        "ASSE_REAL_SRTDOWN": {"label": "ASSE_REAL_SRTDOWN", "origin": "??"},
        "ASSE_REAL_COEFFUP": {"label": "ASSE_REAL_COEFFUP", "origin": "??"},
        "ASSE_REAL_COEFFDOWN": {"label": "ASSE_REAL_COEFFDOWN", "origin": "??"},
        "ASSE_REAL_P1UP": {"label": "ASSE_REAL_P1UP", "origin": "??"},
        "ASSE_REAL_P1DOWN": {"label": "ASSE_REAL_P1DOWN", "origin": "??"},
        "ASSE_REAL_P2UP": {"label": "ASSE_REAL_P2UP", "origin": "??"},
        "ASSE_REAL_P2DOWN": {"label": "ASSE_REAL_P2DOWN", "origin": "??"},
        "ASSE_REAL_SYSPRESSUP1": {"label": "ASSE_REAL_SYSPRESSUP1", "origin": "??"},
        "ASSE_REAL_SYSPRESSDOWN1": {"label": "ASSE_REAL_SYSPRESSDOWN1", "origin": "??"},
        "ASSE_REAL_SYSPRESSUP2": {"label": "ASSE_REAL_SYSPRESSUP2", "origin": "??"},
        "ASSE_REAL_SYSPRESSDOWN2": {"label": "ASSE_REAL_SYSPRESSDOWN2", "origin": "??"},
        "ASSE_REAL_SYSPRESSUP3": {"label": "ASSE_REAL_SYSPRESSUP3", "origin": "??"},
        "ASSE_REAL_SYSPRESSDOWN3": {"label": "ASSE_REAL_SYSPRESSDOWN3", "origin": "??"},
        "ASSE_REAL_BWVMAX": {"label": "ASSE_REAL_BWVMAX", "origin": "??"},
        "ASSE_REAL_DSMAXDOWN": {"label": "ASSE_REAL_DSMAXDOWN", "origin": "??"},
        "ASSE_REAL_DSMAXUP": {"label": "ASSE_REAL_DSMAXUP", "origin": "??"},
        "ASSE_REAL_FWVMAX": {"label": "ASSE_REAL_FWVMAX", "origin": "??"},
        "ASSE_REAL_SMAX": {"label": "ASSE_REAL_SMAX", "origin": "??"},
        "ASSE_REAL_SMIN": {"label": "ASSE_REAL_SMIN", "origin": "??"},
        "ASSE_REAL_SSUP": {"label": "ASSE_REAL_SSUP", "origin": "??"},
        "ASSE_REAL_SINF": {"label": "ASSE_REAL_SINF", "origin": "??"},
        "ASSE_REAL_VMINSTARTED": {"label": "ASSE_REAL_VMINSTARTED", "origin": "??"},
        "ASSE_REAL_SHH": {"label": "ASSE_REAL_SHH", "origin": "??"},
        "ASSE_REAL_SH": {"label": "ASSE_REAL_SH", "origin": "??"},
        "ASSE_REAL_SL": {"label": "ASSE_REAL_SL", "origin": "??"},
        "ASSE_REAL_SLL": {"label": "ASSE_REAL_SLL", "origin": "??"},
        "ASSE_REAL_TILTMAX": {"label": "ASSE_REAL_TILTMAX", "origin": "??"},
        "ASSE_REAL_MASTERMULT": {"label": "ASSE_REAL_MASTERMULT", "origin": "??"},
        "ASSE_REAL_MASTERDELTAMIN": {"label": "ASSE_REAL_MASTERDELTAMIN", "origin": "??"},
        "ASSE_REAL_MASTERKSRS": {"label": "ASSE_REAL_MASTERKSRS", "origin": "??"},
        "ASSE_REAL_SLAVEVRESET": {"label": "ASSE_REAL_SLAVEVRESET", "origin": "??"},
        "ASSE_REAL_SLAVEVMIN": {"label": "ASSE_REAL_SLAVEVMIN", "origin": "??"},
        "ASSE_REAL_SLAVEDELTATSTART": {"label": "ASSE_REAL_SLAVEDELTATSTART", "origin": "??"},
        "ASSE_REAL_OUTKP": {"label": "ASSE_REAL_OUTKP", "origin": "??"},
        "ASSE_REAL_OUTDELTAT": {"label": "ASSE_REAL_OUTDELTAT", "origin": "??"},
        "ASSE_REAL_SH0": {"label": "ASSE_REAL_SH0", "origin": "??"},
        "ASSE_REAL_SL0": {"label": "ASSE_REAL_SL0", "origin": "??"},
        "ASSE_REAL_TILTMAXDOWN": {"label": "ASSE_REAL_TILTMAXDOWN", "origin": "??"},
        "ASSE_REAL_FREE_39": {"label": "ASSE_REAL_FREE_39", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGUP": {"label": "ASSE_REAL_DELTAMOVINGUP", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGDOWN": {"label": "ASSE_REAL_DELTAMOVINGDOWN", "origin": "??"},
        "ASSE_REAL_DELTADIV": {"label": "ASSE_REAL_DELTADIV", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGSUPUP": {"label": "ASSE_REAL_DELTAMOVINGSUPUP", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGINFUP": {"label": "ASSE_REAL_DELTAMOVINGINFUP", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGSUPDOWN": {"label": "ASSE_REAL_DELTAMOVINGSUPDOWN", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGINFDOWN": {"label": "ASSE_REAL_DELTAMOVINGINFDOWN", "origin": "??"},
        "ASSE_REAL_DELTAAUTO": {"label": "ASSE_REAL_DELTAAUTO", "origin": "??"},
        "ASSE_REAL_BWACCMAX": {"label": "ASSE_REAL_BWACCMAX", "origin": "??"},
        "ASSE_REAL_FWACCMAX": {"label": "ASSE_REAL_FWACCMAX", "origin": "??"},
        "ASSE_REAL_OPTPARAM1": {"label": "ASSE_REAL_OPTPARAM1", "origin": "??"},
        "ASSE_REAL_OPTPARAM2": {"label": "ASSE_REAL_OPTPARAM2", "origin": "??"},
        "ASSE_REAL_OPTPARAM3": {"label": "ASSE_REAL_OPTPARAM3", "origin": "??"},
        "ASSE_REAL_AXISCOUPMIN": {"label": "ASSE_REAL_AXISCOUPMIN", "origin": "??"},
        "ASSE_REAL_FREE_54": {"label": "ASSE_REAL_FREE_54", "origin": "??"},

    },
    "offsetval": {
        "ASSE_REAL_SRTUP": {"display": "ASSE_REAL_SRTUP", "origin": "??"},
        "ASSE_REAL_SRTDOWN": {"display": "ASSE_REAL_SRTDOWN", "origin": "??"},
        "ASSE_REAL_COEFFUP": {"display": "ASSE_REAL_COEFFUP", "origin": "??"},
        "ASSE_REAL_COEFFDOWN": {"display": "ASSE_REAL_COEFFDOWN", "origin": "??"},
        "ASSE_REAL_P1UP": {"display": "ASSE_REAL_P1UP", "origin": "??"},
        "ASSE_REAL_P1DOWN": {"display": "ASSE_REAL_P1DOWN", "origin": "??"},
        "ASSE_REAL_P2UP": {"display": "ASSE_REAL_P2UP", "origin": "??"},
        "ASSE_REAL_P2DOWN": {"display": "ASSE_REAL_P2DOWN", "origin": "??"},
        "ASSE_REAL_SYSPRESSUP1": {"display": "ASSE_REAL_SYSPRESSUP1", "origin": "??"},
        "ASSE_REAL_SYSPRESSDOWN1": {"display": "ASSE_REAL_SYSPRESSDOWN1", "origin": "??"},
        "ASSE_REAL_SYSPRESSUP2": {"display": "ASSE_REAL_SYSPRESSUP2", "origin": "??"},
        "ASSE_REAL_SYSPRESSDOWN2": {"display": "ASSE_REAL_SYSPRESSDOWN2", "origin": "??"},
        "ASSE_REAL_SYSPRESSUP3": {"display": "ASSE_REAL_SYSPRESSUP3", "origin": "??"},
        "ASSE_REAL_SYSPRESSDOWN3": {"display": "ASSE_REAL_SYSPRESSDOWN3", "origin": "??"},
        "ASSE_REAL_BWVMAX": {"display": "ASSE_REAL_BWVMAX", "origin": "??"},
        "ASSE_REAL_DSMAXDOWN": {"display": "ASSE_REAL_DSMAXDOWN", "origin": "??"},
        "ASSE_REAL_DSMAXUP": {"display": "ASSE_REAL_DSMAXUP", "origin": "??"},
        "ASSE_REAL_FWVMAX": {"display": "ASSE_REAL_FWVMAX", "origin": "??"},
        "ASSE_REAL_SMAX": {"display": "ASSE_REAL_SMAX", "origin": "??"},
        "ASSE_REAL_SMIN": {"display": "ASSE_REAL_SMIN", "origin": "??"},
        "ASSE_REAL_SSUP": {"display": "ASSE_REAL_SSUP", "origin": "??"},
        "ASSE_REAL_SINF": {"display": "ASSE_REAL_SINF", "origin": "??"},
        "ASSE_REAL_VMINSTARTED": {"display": "ASSE_REAL_VMINSTARTED", "origin": "??"},
        "ASSE_REAL_SHH": {"display": "ASSE_REAL_SHH", "origin": "??"},
        "ASSE_REAL_SH": {"display": "ASSE_REAL_SH", "origin": "??"},
        "ASSE_REAL_SL": {"display": "ASSE_REAL_SL", "origin": "??"},
        "ASSE_REAL_SLL": {"display": "ASSE_REAL_SLL", "origin": "??"},
        "ASSE_REAL_TILTMAX": {"display": "ASSE_REAL_TILTMAX", "origin": "??"},
        "ASSE_REAL_MASTERMULT": {"display": "ASSE_REAL_MASTERMULT", "origin": "??"},
        "ASSE_REAL_MASTERDELTAMIN": {"display": "ASSE_REAL_MASTERDELTAMIN", "origin": "??"},
        "ASSE_REAL_MASTERKSRS": {"display": "ASSE_REAL_MASTERKSRS", "origin": "??"},
        "ASSE_REAL_SLAVEVRESET": {"display": "ASSE_REAL_SLAVEVRESET", "origin": "??"},
        "ASSE_REAL_SLAVEVMIN": {"display": "ASSE_REAL_SLAVEVMIN", "origin": "??"},
        "ASSE_REAL_SLAVEDELTATSTART": {"display": "ASSE_REAL_SLAVEDELTATSTART", "origin": "??"},
        "ASSE_REAL_OUTKP": {"display": "ASSE_REAL_OUTKP", "origin": "??"},
        "ASSE_REAL_OUTDELTAT": {"display": "ASSE_REAL_OUTDELTAT", "origin": "??"},
        "ASSE_REAL_SH0": {"display": "ASSE_REAL_SH0", "origin": "??"},
        "ASSE_REAL_SL0": {"display": "ASSE_REAL_SL0", "origin": "??"},
        "ASSE_REAL_TILTMAXDOWN": {"display": "ASSE_REAL_TILTMAXDOWN", "origin": "??"},
        "ASSE_REAL_FREE_39": {"display": "ASSE_REAL_FREE_39", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGUP": {"display": "ASSE_REAL_DELTAMOVINGUP", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGDOWN": {"display": "ASSE_REAL_DELTAMOVINGDOWN", "origin": "??"},
        "ASSE_REAL_DELTADIV": {"display": "ASSE_REAL_DELTADIV", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGSUPUP": {"display": "ASSE_REAL_DELTAMOVINGSUPUP", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGINFUP": {"display": "ASSE_REAL_DELTAMOVINGINFUP", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGSUPDOWN": {"display": "ASSE_REAL_DELTAMOVINGSUPDOWN", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGINFDOWN": {"display": "ASSE_REAL_DELTAMOVINGINFDOWN", "origin": "??"},
        "ASSE_REAL_DELTAAUTO": {"display": "ASSE_REAL_DELTAAUTO", "origin": "??"},
        "ASSE_REAL_BWACCMAX": {"display": "ASSE_REAL_BWACCMAX", "origin": "??"},
        "ASSE_REAL_FWACCMAX": {"display": "ASSE_REAL_FWACCMAX", "origin": "??"},
        "ASSE_REAL_OPTPARAM1": {"display": "ASSE_REAL_OPTPARAM1", "origin": "??"},
        "ASSE_REAL_OPTPARAM2": {"display": "ASSE_REAL_OPTPARAM2", "origin": "??"},
        "ASSE_REAL_OPTPARAM3": {"display": "ASSE_REAL_OPTPARAM3", "origin": "??"},
        "ASSE_REAL_AXISCOUPMIN": {"display": "ASSE_REAL_AXISCOUPMIN", "origin": "??"},
        "ASSE_REAL_FREE_54": {"display": "ASSE_REAL_FREE_54", "origin": "??"},

    },
    "typval": {
        "ASSE_REAL_SRTUP": {"display": "ASSE_REAL_SRTUP", "origin": "??"},
        "ASSE_REAL_SRTDOWN": {"display": "ASSE_REAL_SRTDOWN", "origin": "??"},
        "ASSE_REAL_COEFFUP": {"display": "ASSE_REAL_COEFFUP", "origin": "??"},
        "ASSE_REAL_COEFFDOWN": {"display": "ASSE_REAL_COEFFDOWN", "origin": "??"},
        "ASSE_REAL_P1UP": {"display": "ASSE_REAL_P1UP", "origin": "??"},
        "ASSE_REAL_P1DOWN": {"display": "ASSE_REAL_P1DOWN", "origin": "??"},
        "ASSE_REAL_P2UP": {"display": "ASSE_REAL_P2UP", "origin": "??"},
        "ASSE_REAL_P2DOWN": {"display": "ASSE_REAL_P2DOWN", "origin": "??"},
        "ASSE_REAL_SYSPRESSUP1": {"display": "ASSE_REAL_SYSPRESSUP1", "origin": "??"},
        "ASSE_REAL_SYSPRESSDOWN1": {"display": "ASSE_REAL_SYSPRESSDOWN1", "origin": "??"},
        "ASSE_REAL_SYSPRESSUP2": {"display": "ASSE_REAL_SYSPRESSUP2", "origin": "??"},
        "ASSE_REAL_SYSPRESSDOWN2": {"display": "ASSE_REAL_SYSPRESSDOWN2", "origin": "??"},
        "ASSE_REAL_SYSPRESSUP3": {"display": "ASSE_REAL_SYSPRESSUP3", "origin": "??"},
        "ASSE_REAL_SYSPRESSDOWN3": {"display": "ASSE_REAL_SYSPRESSDOWN3", "origin": "??"},
        "ASSE_REAL_BWVMAX": {"display": "ASSE_REAL_BWVMAX", "origin": "??"},
        "ASSE_REAL_DSMAXDOWN": {"display": "ASSE_REAL_DSMAXDOWN", "origin": "??"},
        "ASSE_REAL_DSMAXUP": {"display": "ASSE_REAL_DSMAXUP", "origin": "??"},
        "ASSE_REAL_FWVMAX": {"display": "ASSE_REAL_FWVMAX", "origin": "??"},
        "ASSE_REAL_SMAX": {"display": "ASSE_REAL_SMAX", "origin": "??"},
        "ASSE_REAL_SMIN": {"display": "ASSE_REAL_SMIN", "origin": "??"},
        "ASSE_REAL_SSUP": {"display": "ASSE_REAL_SSUP", "origin": "??"},
        "ASSE_REAL_SINF": {"display": "ASSE_REAL_SINF", "origin": "??"},
        "ASSE_REAL_VMINSTARTED": {"display": "ASSE_REAL_VMINSTARTED", "origin": "??"},
        "ASSE_REAL_SHH": {"display": "ASSE_REAL_SHH", "origin": "??"},
        "ASSE_REAL_SH": {"display": "ASSE_REAL_SH", "origin": "??"},
        "ASSE_REAL_SL": {"display": "ASSE_REAL_SL", "origin": "??"},
        "ASSE_REAL_SLL": {"display": "ASSE_REAL_SLL", "origin": "??"},
        "ASSE_REAL_TILTMAX": {"display": "ASSE_REAL_TILTMAX", "origin": "??"},
        "ASSE_REAL_MASTERMULT": {"display": "ASSE_REAL_MASTERMULT", "origin": "??"},
        "ASSE_REAL_MASTERDELTAMIN": {"display": "ASSE_REAL_MASTERDELTAMIN", "origin": "??"},
        "ASSE_REAL_MASTERKSRS": {"display": "ASSE_REAL_MASTERKSRS", "origin": "??"},
        "ASSE_REAL_SLAVEVRESET": {"display": "ASSE_REAL_SLAVEVRESET", "origin": "??"},
        "ASSE_REAL_SLAVEVMIN": {"display": "ASSE_REAL_SLAVEVMIN", "origin": "??"},
        "ASSE_REAL_SLAVEDELTATSTART": {"display": "ASSE_REAL_SLAVEDELTATSTART", "origin": "??"},
        "ASSE_REAL_OUTKP": {"display": "ASSE_REAL_OUTKP", "origin": "??"},
        "ASSE_REAL_OUTDELTAT": {"display": "ASSE_REAL_OUTDELTAT", "origin": "??"},
        "ASSE_REAL_SH0": {"display": "ASSE_REAL_SH0", "origin": "??"},
        "ASSE_REAL_SL0": {"display": "ASSE_REAL_SL0", "origin": "??"},
        "ASSE_REAL_TILTMAXDOWN": {"display": "ASSE_REAL_TILTMAXDOWN", "origin": "??"},
        "ASSE_REAL_FREE_39": {"display": "ASSE_REAL_FREE_39", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGUP": {"display": "ASSE_REAL_DELTAMOVINGUP", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGDOWN": {"display": "ASSE_REAL_DELTAMOVINGDOWN", "origin": "??"},
        "ASSE_REAL_DELTADIV": {"display": "ASSE_REAL_DELTADIV", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGSUPUP": {"display": "ASSE_REAL_DELTAMOVINGSUPUP", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGINFUP": {"display": "ASSE_REAL_DELTAMOVINGINFUP", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGSUPDOWN": {"display": "ASSE_REAL_DELTAMOVINGSUPDOWN", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGINFDOWN": {"display": "ASSE_REAL_DELTAMOVINGINFDOWN", "origin": "??"},
        "ASSE_REAL_DELTAAUTO": {"display": "ASSE_REAL_DELTAAUTO", "origin": "??"},
        "ASSE_REAL_BWACCMAX": {"display": "ASSE_REAL_BWACCMAX", "origin": "??"},
        "ASSE_REAL_FWACCMAX": {"display": "ASSE_REAL_FWACCMAX", "origin": "??"},
        "ASSE_REAL_OPTPARAM1": {"display": "ASSE_REAL_OPTPARAM1", "origin": "??"},
        "ASSE_REAL_OPTPARAM2": {"display": "ASSE_REAL_OPTPARAM2", "origin": "??"},
        "ASSE_REAL_OPTPARAM3": {"display": "ASSE_REAL_OPTPARAM3", "origin": "??"},
        "ASSE_REAL_AXISCOUPMIN": {"display": "ASSE_REAL_AXISCOUPMIN", "origin": "??"},
        "ASSE_REAL_FREE_54": {"display": "ASSE_REAL_FREE_54", "origin": "??"},

    }
}


def axisparam_map_indexes():
    new_entries = {}
    for key, value in Type_AxisParam_Map.items():
        if isinstance(value, dict):
            new_entries[f'_{key}'] = {i: k for i, k in enumerate(value.keys())}
    return new_entries


Type_AxisParam_Map.update(axisparam_map_indexes())


