# -*- coding: utf-8 -*-
# =====================================
#  tia_constants_map.py  (rebuilt clean)
# =====================================
from utils.exports.tia_constants import *

# Costanti base

# ===============================
# 📌 LEGGENDA TYPE_AXISPARAM
# ===============================
AXIS_BOOL_LABELS = [
    "ASSE_BOOL_CONFIG",
    "ASSE_BOOL_BP1",
    "ASSE_BOOL_BP2",
    "ASSE_BOOL_BP3",
    "ASSE_BOOL_BP4",
    "ASSE_BOOL_BP5",
    "ASSE_BOOL_BP6",
    "ASSE_BOOL_BP7",
    "ASSE_BOOL_BP8",
    "ASSE_BOOL_BP9",
    "ASSE_BOOL_BP10",
    "ASSE_BOOL_BP11",
    "ASSE_BOOL_BP12",
    "ASSE_BOOL_FLAGCOUPMAX",
    "ASSE_BOOL_SHOWMAN",
    "ASSE_BOOL_SHOWAUTO",
    "ASSE_BOOL_ENABAXIS",
    "ASSE_BOOL_ENABINTERP",
    "ASSE_BOOL_ENABTEACH",
    "ASSE_BOOL_ENABSMAX",
    "ASSE_BOOL_ENABSMIN",
    "ASSE_BOOL_ENABSHH",
    "ASSE_BOOL_ENABSH",
    "ASSE_BOOL_ENABSL",
    "ASSE_BOOL_ENABSLL",
    "ASSE_BOOL_CONFIGUP",
    "ASSE_BOOL_CONFIGDOWN",
    "ASSE_BOOL_FLAGINV",
    "ASSE_BOOL_CHECKSTOPDISABLED",
    "ASSE_BOOL_SHOWDELTA",
    "ASSE_BOOL_DISABLEDELTA",
    "ASSE_BOOL_ENABSH0",
    "ASSE_BOOL_ENABSL0",
    "ASSE_BOOL_MANSPUP",
    "ASSE_BOOL_MANSPDOWN",
    "ASSE_BOOL_SHOWDELTATAB",
    "ASSE_BOOL_NOMACHINESTARTED",
    "ASSE_BOOL_AXISNOMOVE",
    "ASSE_BOOL_COUPCALC",
    "ASSE_BOOL_FREE_39",
    "ASSE_BOOL_FREE_40",
]

AXIS_INT_LABELS = [
    "ASSE_INT_MASTER",
    "ASSE_INT_FEEDBACK",
    "ASSE_INT_INPUT",
    "ASSE_INT_INPUT2",
    "ASSE_INT_INPUT3",
    "ASSE_INT_INPUT4",
    "ASSE_INT_OUTPUT1",
    "ASSE_INT_OUTPUT2",
    "ASSE_INT_OUTPUT3",
    "ASSE_INT_OUTPUT4",
    "ASSE_INT_LABELTYPE",
    "ASSE_INT_LABELROW",
    "ASSE_INT_LABELCOL",
    "ASSE_INT_LABELNTOT",
    "ASSE_INT_LABELNDEC",
    "ASSE_INT_LABELROWIMP",
    "ASSE_INT_LABELCOLIMP",
    "ASSE_INT_LABELNTOTIMP",
    "ASSE_INT_LABELNDECIMP",
    "ASSE_INT_SUPLSIND",
    "ASSE_INT_INFLSIND",
    "ASSE_INT_P1",
    "ASSE_INT_P2",
    "ASSE_INT_TIMEOUT1",
    "ASSE_INT_TIMEOUT2",
    "ASSE_INT_BOOSTVAL",
    "ASSE_INT_TIPOMISURA",
    "ASSE_INT_DEFSPEED",
    "ASSE_INT_MOVEMODE",
    "ASSE_INT_INTERPGROUP",
    "ASSE_INT_ALTFB",
    "ASSE_INT_ALTFBDIG",
    "ASSE_INT_INDSHH",
    "ASSE_INT_INDSH",
    "ASSE_INT_INDSL",
    "ASSE_INT_INDSLL",
    "ASSE_INT_SAFETYUPIND1",
    "ASSE_INT_SAFETYUPIND2",
    "ASSE_INT_SAFETYUPIND3",
    "ASSE_INT_SAFETYUPIND4",
    "ASSE_INT_SAFETYUPIND5",
    "ASSE_INT_SAFETYUPIND6",
    "ASSE_INT_INDSH0",
    "ASSE_INT_INDSL0",
    "ASSE_INT_INDMEM",
    "ASSE_INT_PERACQ",
    "ASSE_INT_NUMTIMEOUT",
    "ASSE_INT_PERVELAVG",
    "ASSE_INT_SAFETYDOWNIND1",
    "ASSE_INT_SAFETYDOWNIND2",
    "ASSE_INT_SAFETYDOWNIND3",
    "ASSE_INT_SAFETYDOWNIND4",
    "ASSE_INT_SAFETYDOWNIND5",
    "ASSE_INT_SAFETYDOWNIND6",
    "ASSE_INT_DELAYUP",
    "ASSE_INT_DELAYDOWN",
    "ASSE_INT_MAXVELPERC",
    "ASSE_INT_DECOUPMASTER",
    "ASSE_INT_DECOUPMASTER2",
    "ASSE_INT_DECOUPMASTER3",
    "ASSE_INT_DECOUPMASTER4",
    "ASSE_INT_DECOUPMASTER5",
    "ASSE_INT_DECOUPMASTER6",
    "ASSE_INT_PS",
    "ASSE_INT_BWVSLOW",
    "ASSE_INT_FWVSLOW",
    "ASSE_INT_PS2",
    "ASSE_INT_PS3",
    "ASSE_INT_AXISCOUPCHECK",
    "ASSE_INT_TEACHMINMULT",
    "ASSE_INT_FREE_70",
    "ASSE_INT_FREE_71",
    "ASSE_INT_PID",
    "ASSE_INT_GRAFIND",
    "ASSE_INT_DELTA1",
    "ASSE_INT_OPTPARAMIND",
    "ASSE_INT_DISABLEBP1",
    "ASSE_INT_DISABLEBP2",
    "ASSE_INT_DISABLEBP3",
    "ASSE_INT_DISABLEBP4",
    "ASSE_INT_DISABLEBP5",
    "ASSE_INT_DISABLEBP6",
    "ASSE_INT_DISABLEBP7",
    "ASSE_INT_DISABLEBP8",
    "ASSE_INT_DISABLEBP9",
    "ASSE_INT_DISABLEBP10",
    "ASSE_INT_DISABLEBP11",
    "ASSE_INT_DISABLEBP12",
    "ASSE_INT_OPTPARAM1",
    "ASSE_INT_OPTPARAM2",
    "ASSE_INT_OPTPARAM3",
    "ASSE_INT_HOLDTORUNTYPE",
    "ASSE_INT_FREE_92",
    "ASSE_INT_FREE_93",
    "ASSE_INT_FREE_94",
]

AXIS_REAL_LABELS = [
    "ASSE_REAL_SRTUP",
    "ASSE_REAL_SRTDOWN",
    "ASSE_REAL_COEFFUP",
    "ASSE_REAL_COEFFDOWN",
    "ASSE_REAL_P1UP",
    "ASSE_REAL_P1DOWN",
    "ASSE_REAL_P2UP",
    "ASSE_REAL_P2DOWN",
    "ASSE_REAL_SYSPRESSUP1",
    "ASSE_REAL_SYSPRESSDOWN1",
    "ASSE_REAL_SYSPRESSUP2",
    "ASSE_REAL_SYSPRESSDOWN2",
    "ASSE_REAL_SYSPRESSUP3",
    "ASSE_REAL_SYSPRESSDOWN3",
    "ASSE_REAL_BWVMAX",
    "ASSE_REAL_DSMAXDOWN",
    "ASSE_REAL_DSMAXUP",
    "ASSE_REAL_FWVMAX",
    "ASSE_REAL_SMAX",
    "ASSE_REAL_SMIN",
    "ASSE_REAL_SSUP",
    "ASSE_REAL_SINF",
    "ASSE_REAL_VMINSTARTED",
    "ASSE_REAL_SHH",
    "ASSE_REAL_SH",
    "ASSE_REAL_SL",
    "ASSE_REAL_SLL",
    "ASSE_REAL_TILTMAX",
    "ASSE_REAL_MASTERMULT",
    "ASSE_REAL_MASTERDELTAMIN",
    "ASSE_REAL_MASTERKSRS",
    "ASSE_REAL_SLAVEVRESET",
    "ASSE_REAL_SLAVEVMIN",
    "ASSE_REAL_SLAVEDELTATSTART",
    "ASSE_REAL_OUTKP",
    "ASSE_REAL_OUTDELTAT",
    "ASSE_REAL_SH0",
    "ASSE_REAL_SL0",
    "ASSE_REAL_TILTMAXDOWN",
    "ASSE_REAL_FREE_39",
    "ASSE_REAL_DELTAMOVINGUP",
    "ASSE_REAL_DELTAMOVINGDOWN",
    "ASSE_REAL_DELTADIV",
    "ASSE_REAL_DELTAMOVINGSUPUP",
    "ASSE_REAL_DELTAMOVINGINFUP",
    "ASSE_REAL_DELTAMOVINGSUPDOWN",
    "ASSE_REAL_DELTAMOVINGINFDOWN",
    "ASSE_REAL_DELTAAUTO",
    "ASSE_REAL_BWACCMAX",
    "ASSE_REAL_FWACCMAX",
    "ASSE_REAL_OPTPARAM1",
    "ASSE_REAL_OPTPARAM2",
    "ASSE_REAL_OPTPARAM3",
    "ASSE_REAL_AXISCOUPMIN",
    "ASSE_REAL_FREE_54",
]

# ===============================
# 📌 LEGGENDA TYPE_TOOLSETOUTPUTPARAM
# ===============================

TOOLSETOUTPUT_INT_LABELS = [
    "TOOLSETOUTPUT_INT_AXIS",  # intval[0]
    "TOOLSETOUTPUT_INT_IND",  # intval[1]
]

TOOLSETOUTPUT_DINT_LABELS = [
    "TOOLSETOUTPUT_DINT_SCALEMIN1",  # dintval[0]
    "TOOLSETOUTPUT_DINT_SCALEMAX1",  # dintval[1]
    "TOOLSETOUTPUT_DINT_SCALEMIN2",  # dintval[2]
    "TOOLSETOUTPUT_DINT_SCALEMAX2",  # dintval[3]
    "TOOLSETOUTPUT_DINT_SCALEMIN1H",  # dintval[4]
    "TOOLSETOUTPUT_DINT_SCALEMAX1H",  # dintval[5]
    "TOOLSETOUTPUT_DINT_SCALEMIN2H",  # dintval[6]
    "TOOLSETOUTPUT_DINT_SCALEMAX2H",  # dintval[7]
]

# ===============================
# 📌 IN/OUT INDEX MAPS
# ===============================

IN_IND_MAP = [
    {"label": "BOOL_IND_AUTOMODESEL", "display": "AUTO SEL DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tSEL IO"},
    {"label": "BOOL_IND_TEACHMODESEL", "display": "AUTO TEACH DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tSEL IO"},
    {"label": "BOOL_IND_CYCLEMODESEL", "display": "CYCLE SEL DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tSEL IO"},
    {"label": "BOOL_IND_STARTRESET", "display": "BOOL_IND_STARTRESET", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tCMD IO"},
    {"label": "BOOL_IND_REMOTEMODESEL", "display": "REMOTE SEL DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tSEL IO"},
    {"label": "BOOL_IND_EMGCYPB", "display": "EMGCY PB DI", "origin": "Params\t→\tConfiguration\t→\tSafety"},
    {"label": "BOOL_IND_CONSOLE2MODESEL", "display": "CONSOLE 2 SEL DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tSEL IO"},
    {"label": "BOOL_IND_CHROLLMODESEL", "display": "CHROLL SEL DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tSEL IO"},
    {"label": "BOOL_IND_INENABLED", "display": "BOOL_IND_INENABLED", "origin": "??"},
    {"label": "BOOL_IND_DEBALNOTPRESS", "display": "DEBALNOTPRESS DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tSTATUS IO"},
    {"label": "BOOL_IND_CONSOLE1MODESEL", "display": "CONSOLE 1 SEL DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tSEL IO"},
    {"label": "BOOL_IND_SINGMOVSEL", "display": "SINGMOV SEL DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tSEL IO"},
    {"label": "BOOL_IND_STARTIN", "display": "STARTIN DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tCMD IO"},
    {"label": "BOOL_IND_STOPIN", "display": "STOPIN DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tCMD IO"},
    {"label": "BOOL_IND_STARTEDIN", "display": "MAC.STARTED IN DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tSTATUS IO"},
    {"label": "BOOL_IND_HOLDTORUN", "display": "HOLDTORUN DI", "origin": "Params\t→\tConfiguration\t→\tSafety"},
    {"label": "BOOL_IND_RTCOUPLED", "display": "RTCOUPLED DI", "origin": "Params\t→\tConfiguration\t→\tRT"},
    {"label": "BOOL_IND_LEFTSEL", "display": "RC LEFT SEL DI", "origin": "Params\t→\tConfiguration\t→\tRadio Control"},
    {"label": "BOOL_IND_PINCHPRESS", "display": "PINCHPRESS DI", "origin": "Params\t→\tPinch Preload"},
    {"label": "BOOL_IND_RIGHTSEL", "display": "RC RIGHT SEL", "origin": "Params\t→\tConfiguration\t→\tRadio Control"},
    {"label": "BOOL_IND_STARTSENSOR", "display": "START SENSOR IN DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tSTATUS IO"},
    {"label": "BOOL_IND_MAINTRESET", "display": "MAINTRESET DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tCMD IO"},
    {"label": "BOOL_IND_MANMODESEL", "display": "MAN SEL DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tSEL IO"},
    {"label": "BOOL_IND_TESTMODESEL", "display": "TEST SEL DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tSEL IO"},
    {"label": "BOOL_IND_SEMIAUTOMODESEL", "display": "SEMIAUTO SEL DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tSEL IO"},
    {"label": "BOOL_IND_HOLDTORUN2", "display": "HOLDTORUN2 DI", "origin": "Params\t→\tConfiguration\t→\tSafety"},
    {"label": "BOOL_IND_DISABLEBP1", "display": "DISABLEBP1 DI", "origin": "Params\t→\tConfiguration\t→\tBP"},
    {"label": "BOOL_IND_DISABLEBP2", "display": "DISABLEBP2 DI", "origin": "Params\t→\tConfiguration\t→\tBP"},
    {"label": "BOOL_IND_DISABLEBP3", "display": "DISABLEBP3 DI", "origin": "Params\t→\tConfiguration\t→\tBP"},
    {"label": "BOOL_IND_DISABLEBP4", "display": "DISABLEBP4 DI", "origin": "Params\t→\tConfiguration\t→\tBP"},
    {"label": "BOOL_IND_DISABLEBP5", "display": "DISABLEBP5 DI", "origin": "Params\t→\tConfiguration\t→\tBP"},
    {"label": "BOOL_IND_DISABLEBP6", "display": "DISABLEBP6 DI", "origin": "Params\t→\tConfiguration\t→\tBP"},
    {"label": "BOOL_IND_DISABLEBP7", "display": "DISABLEBP7 DI", "origin": "Params\t→\tConfiguration\t→\tBP"},
    {"label": "BOOL_IND_DISABLEBP8", "display": "DISABLEBP8 DI", "origin": "Params\t→\tConfiguration\t→\tBP"},
    {"label": "BOOL_IND_DISABLEBP9", "display": "DISABLEBP9 DI", "origin": "Params\t→\tConfiguration\t→\tBP"},
    {"label": "BOOL_IND_DISABLEBP10", "display": "DISABLEBP10 DI", "origin": "Params\t→\tConfiguration\t→\tBP"},
    {"label": "BOOL_IND_DISABLEBP11", "display": "DISABLEBP11 DI", "origin": "Params\t→\tConfiguration\t→\tBP"},
    {"label": "BOOL_IND_DISABLEBP12", "display": "DISABLEBP12 DI", "origin": "Params\t→\tConfiguration\t→\tBP"},
    {"label": "BOOL_IND_AUTOMODE", "display": "AUTO MODE DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tMODE IO"},
    {"label": "BOOL_IND_AUTOCYCLEMODE", "display": "AUTOCYCLE MODE DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tMODE IO"},
    {"label": "BOOL_IND_AUTOSTEPMODE", "display": "AUTOSTEP MODE DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tMODE IO"},
    {"label": "BOOL_IND_SEMIAUTOMODE", "display": "SEMIAUTO MODE DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tMODE IO"},
    {"label": "BOOL_IND_TEACHMODE", "display": "TEACH MODE DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tMODE IO"},
    {"label": "BOOL_IND_MANMODE", "display": "MAN MODE DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tMODE IO"},
    {"label": "BOOL_IND_CONSOLE1MODE", "display": "CONSOLE 1 MODE DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tMODE IO"},
    {"label": "BOOL_IND_CONSOLE2MODE", "display": "CONSOLE 2 MODE DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tMODE IO"},
    {"label": "BOOL_IND_REMOTEMODE", "display": "REMOTE MODE DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tMODE IO"},
    {"label": "BOOL_IND_CHROLLMODE", "display": "CHROLL MODE DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tMODE IO"},
    {"label": "BOOL_IND_SINGMOVMODE", "display": "SINGMOV MODE DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tMODE IO"},
    {"label": "BOOL_IND_MACHINESTARTED", "display": "MACHINE STARTED DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tRSM IO"},
    {"label": "BOOL_IND_OUTSWENAB", "display": "BOOL_IND_OUTSWENAB", "origin": "??"},
    {"label": "BOOL_IND_GREASEPUMPON", "display": "PUMP ON CALC DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tGrease"},
    {"label": "BOOL_IND_GREASEALARM", "display": "GREASE ALARM CALC DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tGrease"},
    {"label": "BOOL_IND_GREASEPUMPALARM", "display": "PUMP ALARM (CALC) DI",
     "origin": "Params\t→\tConfiguration\t→\tMain\t→\tGrease"},
    {"label": "BOOL_IND_WAITINGFORSTART", "display": "BOOL_IND_WAITINGFORSTART", "origin": "??"},
    {"label": "BOOL_IND_POWEROFFFLAG", "display": "BOOL_IND_POWEROFFFLAG", "origin": "??"},
    {"label": "BOOL_IND_ALARMON", "display": "ALARM ON DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tRSM IO"},
    {"label": "BOOL_IND_STARTCMD", "display": "BOOL_IND_STARTCMD", "origin": "??"},
    {"label": "BOOL_IND_ALARMSTOP", "display": "ALARM STOP DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tRSM IO"},
    {"label": "BOOL_IND_MAINTON", "display": "MAINTON DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tRSM IO"},
    {"label": "BOOL_IND_RTFWDISABLED", "display": "RTFW DISABLED DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tSTATUS IO"},
    {"label": "BOOL_IND_LEFTMEM", "display": "RC LEFT MEM DI", "origin": "Params\t→\tConfiguration\t→\tRadio Control"},
    {"label": "BOOL_IND_RESETFLAG", "display": "BOOL_IND_RESETFLAG", "origin": "??"},
    {"label": "BOOL_IND_RIGHTMEM", "display": "RC RIGHT MEM DI", "origin": "Params\t→\tConfiguration\t→\tRadio Control"},
    {"label": "BOOL_IND_OUTENABLED", "display": "HOLDTORUN ERROR DI", "origin": "Params\t→\tConfiguration\t→\tSafety"},
    {"label": "BOOL_IND_STOPCMD", "display": "BOOL_IND_STOPCMD", "origin": "??"},
    {"label": "BOOL_IND_QUALITYENAB", "display": "BOOL_IND_QUALITYENAB", "origin": "??"},
    {"label": "BOOL_IND_TELESERVICEREQ", "display": "BOOL_IND_TELESERVICEREQ", "origin": "??"},
    {"label": "BOOL_IND_MICROMODESEL", "display": "MICRO SEL DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tSEL IO"},
    {"label": "BOOL_IND_APPLY", "display": "BOOL_IND_APPLY", "origin": "??"},
    {"label": "BOOL_IND_QUALITYEND", "display": "QUALITY END DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tRSM IO"},
    {"label": "BOOL_IND_AUTOSTARTINGBLINK", "display": "AUTOSTARTI BLINK DI",
     "origin": "Params\t→\tConfiguration\t→\tMain\t→\tSTATUS IO"},
    {"label": "BOOL_IND_QUALITYGOOD", "display": "QUALITY GOOD DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tRSM IO"},
    {"label": "BOOL_IND_PARTEND", "display": "PART END DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tRSM IO"},
    {"label": "BOOL_IND_AUTOCORR", "display": "BOOL_IND_AUTOCORR", "origin": "??"},
    {"label": "BOOL_IND_PARTBEGIN", "display": "PART BEGIN DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tRSM IO"},
    {"label": "BOOL_IND_AUTOCORRSTARTED", "display": "BOOL_IND_AUTOCORRSTARTED", "origin": "??"},
    {"label": "BOOL_IND_TILTDISABLED", "display": "TILT DISABLE DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tCMD IO"},
    {"label": "BOOL_IND_EYEBENDON", "display": "BOOL_IND_EYEBENDON", "origin": "??"},
    {"label": "BOOL_IND_BP1", "display": "BOOL_IND_BP1", "origin": "??"},
    {"label": "BOOL_IND_BP2", "display": "BOOL_IND_BP2", "origin": "??"},
    {"label": "BOOL_IND_BP3", "display": "BOOL_IND_BP3", "origin": "??"},
    {"label": "BOOL_IND_BP4", "display": "BOOL_IND_BP4", "origin": "??"},
    {"label": "BOOL_IND_BP5", "display": "BOOL_IND_BP5", "origin": "??"},
    {"label": "BOOL_IND_BP6", "display": "BOOL_IND_BP6", "origin": "??"},
    {"label": "BOOL_IND_BP7", "display": "BOOL_IND_BP7", "origin": "??"},
    {"label": "BOOL_IND_BP8", "display": "BOOL_IND_BP8", "origin": "??"},
    {"label": "BOOL_IND_BP9", "display": "BOOL_IND_BP9", "origin": "??"},
    {"label": "BOOL_IND_BP10", "display": "BOOL_IND_BP10", "origin": "??"},
    {"label": "BOOL_IND_BP11", "display": "BOOL_IND_BP11", "origin": "??"},
    {"label": "BOOL_IND_BP12", "display": "BOOL_IND_BP12", "origin": "??"},
    {"label": "BOOL_IND_RCV0", "display": "RC V0 DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tRadio Control"},
    {"label": "BOOL_IND_RCV1", "display": "RC V1 DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tRadio Control"},
    {"label": "BOOL_IND_RCV2", "display": "RC V2 DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tRadio Control"},
    {"label": "BOOL_IND_RCV3", "display": "RC V3 DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tRadio Control"},
    {"label": "BOOL_IND_RCV4", "display": "RC V4 DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tRadio Control"},
    {"label": "BOOL_IND_RCUM", "display": "BOOL_IND_RCUM", "origin": "??"},
    {"label": "BOOL_IND_RCLUP", "display": "BOOL_IND_RCLUP", "origin": "??"},
    {"label": "BOOL_IND_RCLDOWN", "display": "BOOL_IND_RCLDOWN", "origin": "??"},
    {"label": "BOOL_IND_RCRUP", "display": "BOOL_IND_RCRUP", "origin": "??"},
    {"label": "BOOL_IND_RCRDOWN", "display": "BOOL_IND_RCRDOWN", "origin": "??"},
    {"label": "BOOL_IND_RCBUP", "display": "BOOL_IND_RCBUP", "origin": "??"},
    {"label": "BOOL_IND_RCBDOWN", "display": "BOOL_IND_RCBDOWN", "origin": "??"},
    {"label": "BOOL_IND_RCTLEFT", "display": "BOOL_IND_RCTLEFT", "origin": "??"},
    {"label": "BOOL_IND_RCTRIGHT", "display": "BOOL_IND_RCTRIGHT", "origin": "??"},
    {"label": "BOOL_IND_EMGCYRESETBTN", "display": "EMGCY RESET BTN DI", "origin": "Params\t→\tConfiguration\t→\tSafety"},
    {"label": "BOOL_IND_RCALARM", "display": "BOOL_IND_RCALARM", "origin": "??"},
    {"label": "BOOL_IND_EMGCYRESET", "display": "BOOL_IND_EMGCYRESET", "origin": "??"},
    {"label": "BOOL_IND_INVERTERRESET", "display": "INVERTER RESET DI",
     "origin": "Params\t→\tConfiguration\t→\tMain\t→\tSTATUS IO"},
    {"label": "BOOL_IND_INVERTERALARM", "display": "INVERTER ALARM DI",
     "origin": "Params\t→\tConfiguration\t→\tMain\t→\tSTATUS IO"},
    {"label": "BOOL_IND_AUTOSTARTING", "display": "AUTO STARTING DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tSTATUS IO"},
    {"label": "BOOL_IND_PINCHPRESSFRONTREAR", "display": "BOOL_IND_PINCHPRESSFRONTREAR", "origin": "??"},
    {"label": "BOOL_IND_PINCHPRESSFRONTREAR2", "display": "BOOL_IND_PINCHPRESSFRONTREAR2", "origin": "??"},
    {"label": "BOOL_IND_HOLDTORUNRC", "display": "HOLDTORUN RC DI", "origin": "Params\t→\tConfiguration\t→\tSafety"},
    {"label": "BOOL_IND_PRELOADUP", "display": "PRELOAD UP DI", "origin": "Params\t→\tConfiguration\t→\tPinch Preload"},
    {"label": "BOOL_IND_PRELOADPINCHDISABLED", "display": "PRELOAD PINCH DISAB DI",
     "origin": "Params\t→\tConfiguration\t→\tPinch Preload"},
    {"label": "BOOL_IND_PARTMAN", "display": "BOOL_IND_PARTMAN", "origin": "??"},
    {"label": "BOOL_IND_PARTMANBEGIN", "display": "BOOL_IND_PARTMANBEGIN", "origin": "??"},
    {"label": "BOOL_IND_PARTMANEND", "display": "BOOL_IND_PARTMANEND", "origin": "??"},
    {"label": "BOOL_IND_PARTMANRUNNING", "display": "BOOL_IND_PARTMANRUNNING", "origin": "??"},
    {"label": "BOOL_IND_UNBALLEFT", "display": "UNBAL LEFT DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tCMD IO"},
    {"label": "BOOL_IND_UNBALRIGHT", "display": "UNBAL RIGHT DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tCMD IO"},
    {"label": "BOOL_IND_INVERTEROVERLOAD", "display": "INVERTER OVERLOAD DI",
     "origin": "Params\t→\tConfiguration\t→\tMain\t→\tSTATUS IO"},
    {"label": "BOOL_IND_LEFTSUPPINTERLOCK", "display": "LEFT SUPP INTERL. DI",
     "origin": "Params\t→\tConfiguration\t→\tMain\t→\tSTATUS IO"},
    {"label": "BOOL_IND_GREASELEVEL", "display": "GREASE LEVEL DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tGrease"},
    {"label": "BOOL_IND_GREASETR", "display": "GREASE TR DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tGrease"},
    {"label": "BOOL_IND_STARTSENSOR2", "display": "START SENSOR 2 IN DI",
     "origin": "Params\t→\tConfiguration\t→\tMain\t→\tSTATUS IO"},
    {"label": "BOOL_IND_HOLDTORUNRC2", "display": "HOLDTORUN RC2 DI", "origin": "Params\t→\tConfiguration\t→\tSafety"},
    {"label": "BOOL_IND_TILTBAL", "display": "ROLLTILTBALANCED DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tSTATUS IO"},
    {"label": "BOOL_IND_SDOSTART", "display": "BOOL_IND_SDOSTART", "origin": "??"},
    {"label": "BOOL_IND_SDOBUSY", "display": "BOOL_IND_SDOBUSY", "origin": "??"},
    {"label": "BOOL_IND_SDOOK", "display": "BOOL_IND_SDOOK", "origin": "??"},
    {"label": "BOOL_IND_RIGHTSUPPINTERLOCK", "display": "RIGHT SUPP INTERL. DI",
     "origin": "Params\t→\tConfiguration\t→\tMain\t→\tSTATUS IO"},
    {"label": "BOOL_IND_APPLYROT", "display": "BOOL_IND_APPLYROT", "origin": "??"},
    {"label": "BOOL_IND_REPEATEND", "display": "BOOL_IND_REPEATEND", "origin": "??"},
    {"label": "BOOL_IND_SYNCLOADIN", "display": "SYNC LOAD IN DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tSYNC IO"},
    {"label": "BOOL_IND_SYNCLOADOUT", "display": "BOOL_IND_SYNCLOADOUT", "origin": "??"},
    {"label": "BOOL_IND_SYNCUNLOADIN", "display": "SYNC UNLOAD IN DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tSYNC IO"},
    {"label": "BOOL_IND_SYNCUNLOADOUT", "display": "BOOL_IND_SYNCUNLOADOUT", "origin": "??"},
    {"label": "BOOL_IND_SYNCSTARTIN", "display": "SYNC START IN DI", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tSYNC IO"},
    {"label": "BOOL_IND_SYNCSTARTOUT", "display": "BOOL_IND_SYNCSTARTOUT", "origin": "??"},
    {"label": "BOOL_IND_FREE_141", "display": "BOOL_IND_FREE_141", "origin": "??"},
    {"label": "BOOL_IND_FREE_142", "display": "BOOL_IND_FREE_142", "origin": "??"},
    {"label": "BOOL_IND_FREE_143", "display": "BOOL_IND_FREE_143", "origin": "??"}
]
IN_IND_LABELS = [e["label"] for e in IN_IND_MAP]  # retrocompatibilità

OUT_IND_MAP = [
    {"label": "BOOL_IND_AUTOMODESEL", "display": "BOOL_IND_AUTOMODESEL", "origin": "??"},
    {"label": "BOOL_IND_TEACHMODESEL", "display": "BOOL_IND_TEACHMODESEL", "origin": "??"},
    {"label": "BOOL_IND_CYCLEMODESEL", "display": "BOOL_IND_CYCLEMODESEL", "origin": "??"},
    {"label": "BOOL_IND_STARTRESET", "display": "BOOL_IND_STARTRESET", "origin": "??"},
    {"label": "BOOL_IND_REMOTEMODESEL", "display": "BOOL_IND_REMOTEMODESEL", "origin": "??"},
    {"label": "BOOL_IND_EMGCYPB", "display": "BOOL_IND_EMGCYPB", "origin": "??"},
    {"label": "BOOL_IND_CONSOLE2MODESEL", "display": "BOOL_IND_CONSOLE2MODESEL", "origin": "??"},
    {"label": "BOOL_IND_CHROLLMODESEL", "display": "BOOL_IND_CHROLLMODESEL", "origin": "??"},
    {"label": "BOOL_IND_INENABLED", "display": "BOOL_IND_INENABLED", "origin": "??"},
    {"label": "BOOL_IND_DEBALNOTPRESS", "display": "BOOL_IND_DEBALNOTPRESS", "origin": "??"},
    {"label": "BOOL_IND_CONSOLE1MODESEL", "display": "BOOL_IND_CONSOLE1MODESEL", "origin": "??"},
    {"label": "BOOL_IND_SINGMOVSEL", "display": "BOOL_IND_SINGMOVSEL", "origin": "??"},
    {"label": "BOOL_IND_STARTIN", "display": "BOOL_IND_STARTIN", "origin": "??"},
    {"label": "BOOL_IND_STOPIN", "display": "BOOL_IND_STOPIN", "origin": "??"},
    {"label": "BOOL_IND_STARTEDIN", "display": "BOOL_IND_STARTEDIN", "origin": "??"},
    {"label": "BOOL_IND_HOLDTORUN", "display": "BOOL_IND_HOLDTORUN", "origin": "??"},
    {"label": "BOOL_IND_RTCOUPLED", "display": "BOOL_IND_RTCOUPLED", "origin": "??"},
    {"label": "BOOL_IND_LEFTSEL", "display": "BOOL_IND_LEFTSEL", "origin": "??"},
    {"label": "BOOL_IND_PINCHPRESS", "display": "BOOL_IND_PINCHPRESS", "origin": "??"},
    {"label": "BOOL_IND_RIGHTSEL", "display": "BOOL_IND_RIGHTSEL", "origin": "??"},
    {"label": "BOOL_IND_STARTSENSOR", "display": "BOOL_IND_STARTSENSOR", "origin": "??"},
    {"label": "BOOL_IND_MAINTRESET", "display": "BOOL_IND_MAINTRESET", "origin": "??"},
    {"label": "BOOL_IND_MANMODESEL", "display": "BOOL_IND_MANMODESEL", "origin": "??"},
    {"label": "BOOL_IND_TESTMODESEL", "display": "BOOL_IND_TESTMODESEL", "origin": "??"},
    {"label": "BOOL_IND_SEMIAUTOMODESEL", "display": "BOOL_IND_SEMIAUTOMODESEL", "origin": "??"},
    {"label": "BOOL_IND_HOLDTORUN2", "display": "BOOL_IND_HOLDTORUN2", "origin": "??"},
    {"label": "BOOL_IND_DISABLEBP1", "display": "BOOL_IND_DISABLEBP1", "origin": "??"},
    {"label": "BOOL_IND_DISABLEBP2", "display": "BOOL_IND_DISABLEBP2", "origin": "??"},
    {"label": "BOOL_IND_DISABLEBP3", "display": "BOOL_IND_DISABLEBP3", "origin": "??"},
    {"label": "BOOL_IND_DISABLEBP4", "display": "BOOL_IND_DISABLEBP4", "origin": "??"},
    {"label": "BOOL_IND_DISABLEBP5", "display": "BOOL_IND_DISABLEBP5", "origin": "??"},
    {"label": "BOOL_IND_DISABLEBP6", "display": "BOOL_IND_DISABLEBP6", "origin": "??"},
    {"label": "BOOL_IND_DISABLEBP7", "display": "BOOL_IND_DISABLEBP7", "origin": "??"},
    {"label": "BOOL_IND_DISABLEBP8", "display": "BOOL_IND_DISABLEBP8", "origin": "??"},
    {"label": "BOOL_IND_DISABLEBP9", "display": "BOOL_IND_DISABLEBP9", "origin": "??"},
    {"label": "BOOL_IND_DISABLEBP10", "display": "BOOL_IND_DISABLEBP10", "origin": "??"},
    {"label": "BOOL_IND_DISABLEBP11", "display": "BOOL_IND_DISABLEBP11", "origin": "??"},
    {"label": "BOOL_IND_DISABLEBP12", "display": "BOOL_IND_DISABLEBP12", "origin": "??"},
    {"label": "BOOL_IND_AUTOMODE", "display": "BOOL_IND_AUTOMODE", "origin": "??"},
    {"label": "BOOL_IND_AUTOCYCLEMODE", "display": "BOOL_IND_AUTOCYCLEMODE", "origin": "??"},
    {"label": "BOOL_IND_AUTOSTEPMODE", "display": "BOOL_IND_AUTOSTEPMODE", "origin": "??"},
    {"label": "BOOL_IND_SEMIAUTOMODE", "display": "BOOL_IND_SEMIAUTOMODE", "origin": "??"},
    {"label": "BOOL_IND_TEACHMODE", "display": "BOOL_IND_TEACHMODE", "origin": "??"},
    {"label": "BOOL_IND_MANMODE", "display": "BOOL_IND_MANMODE", "origin": "??"},
    {"label": "BOOL_IND_CONSOLE1MODE", "display": "BOOL_IND_CONSOLE1MODE", "origin": "??"},
    {"label": "BOOL_IND_CONSOLE2MODE", "display": "BOOL_IND_CONSOLE2MODE", "origin": "??"},
    {"label": "BOOL_IND_REMOTEMODE", "display": "BOOL_IND_REMOTEMODE", "origin": "??"},
    {"label": "BOOL_IND_CHROLLMODE", "display": "BOOL_IND_CHROLLMODE", "origin": "??"},
    {"label": "BOOL_IND_SINGMOVMODE", "display": "BOOL_IND_SINGMOVMODE", "origin": "??"},
    {"label": "BOOL_IND_MACHINESTARTED", "display": "MAC.START LIGHT DO", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tCMD IO"},
    {"label": "BOOL_IND_OUTSWENAB", "display": "BOOL_IND_OUTSWENAB", "origin": "??"},
    {"label": "BOOL_IND_GREASEPUMPON", "display": "BOOL_IND_GREASEPUMPON", "origin": "??"},
    {"label": "BOOL_IND_GREASEALARM", "display": "BOOL_IND_GREASEALARM", "origin": "??"},
    {"label": "BOOL_IND_GREASEPUMPALARM", "display": "BOOL_IND_GREASEPUMPALARM", "origin": "??"},
    {"label": "BOOL_IND_WAITINGFORSTART", "display": "MAC.READY LIGHT DO",
     "origin": "Params\t→\tConfiguration\t→\tMain\t→\tCMD IO"},
    {"label": "BOOL_IND_POWEROFFFLAG", "display": "BOOL_IND_POWEROFFFLAG", "origin": "??"},
    {"label": "BOOL_IND_ALARMON", "display": "BOOL_IND_ALARMON", "origin": "??"},
    {"label": "BOOL_IND_STARTCMD", "display": "START CMD DO", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tCMD IO"},
    {"label": "BOOL_IND_ALARMSTOP", "display": "BOOL_IND_ALARMSTOP", "origin": "??"},
    {"label": "BOOL_IND_MAINTON", "display": "BOOL_IND_MAINTON", "origin": "??"},
    {"label": "BOOL_IND_RTFWDISABLED", "display": "BOOL_IND_RTFWDISABLED", "origin": "??"},
    {"label": "BOOL_IND_LEFTMEM", "display": "BOOL_IND_LEFTMEM", "origin": "??"},
    {"label": "BOOL_IND_RESETFLAG", "display": "BOOL_IND_RESETFLAG", "origin": "??"},
    {"label": "BOOL_IND_RIGHTMEM", "display": "BOOL_IND_RIGHTMEM", "origin": "??"},
    {"label": "BOOL_IND_OUTENABLED", "display": "BOOL_IND_OUTENABLED", "origin": "??"},
    {"label": "BOOL_IND_STOPCMD", "display": "STOP CMD DO", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tCMD IO"},
    {"label": "BOOL_IND_QUALITYENAB", "display": "BOOL_IND_QUALITYENAB", "origin": "??"},
    {"label": "BOOL_IND_TELESERVICEREQ", "display": "BOOL_IND_TELESERVICEREQ", "origin": "??"},
    {"label": "BOOL_IND_MICROMODESEL", "display": "BOOL_IND_MICROMODESEL", "origin": "??"},
    {"label": "BOOL_IND_APPLY", "display": "BOOL_IND_APPLY", "origin": "??"},
    {"label": "BOOL_IND_QUALITYEND", "display": "BOOL_IND_QUALITYEND", "origin": "??"},
    {"label": "BOOL_IND_AUTOSTARTINGBLINK", "display": "BOOL_IND_AUTOSTARTINGBLINK", "origin": "??"},
    {"label": "BOOL_IND_QUALITYGOOD", "display": "BOOL_IND_QUALITYGOOD", "origin": "??"},
    {"label": "BOOL_IND_PARTEND", "display": "BOOL_IND_PARTEND", "origin": "??"},
    {"label": "BOOL_IND_AUTOCORR", "display": "BOOL_IND_AUTOCORR", "origin": "??"},
    {"label": "BOOL_IND_PARTBEGIN", "display": "BOOL_IND_PARTBEGIN", "origin": "??"},
    {"label": "BOOL_IND_AUTOCORRSTARTED", "display": "BOOL_IND_AUTOCORRSTARTED", "origin": "??"},
    {"label": "BOOL_IND_TILTDISABLED", "display": "BOOL_IND_TILTDISABLED", "origin": "??"},
    {"label": "BOOL_IND_EYEBENDON", "display": "EYEBEND ON DO", "origin": "Params\t→\tConfiguration\t→\tCheck Measurement"},
    {"label": "BOOL_IND_BP1", "display": "BP1 DO", "origin": "Params\t→\tConfiguration\t→\tBP"},
    {"label": "BOOL_IND_BP2", "display": "BP2 DO", "origin": "Params\t→\tConfiguration\t→\tBP"},
    {"label": "BOOL_IND_BP3", "display": "BP3 DO", "origin": "Params\t→\tConfiguration\t→\tBP"},
    {"label": "BOOL_IND_BP4", "display": "BP4 DO", "origin": "Params\t→\tConfiguration\t→\tBP"},
    {"label": "BOOL_IND_BP5", "display": "BP5 DO", "origin": "Params\t→\tConfiguration\t→\tBP"},
    {"label": "BOOL_IND_BP6", "display": "BP6 DO", "origin": "Params\t→\tConfiguration\t→\tBP"},
    {"label": "BOOL_IND_BP7", "display": "BP7 DO", "origin": "Params\t→\tConfiguration\t→\tBP"},
    {"label": "BOOL_IND_BP8", "display": "BP8 DO", "origin": "Params\t→\tConfiguration\t→\tBP"},
    {"label": "BOOL_IND_BP9", "display": "BP9 DO", "origin": "Params\t→\tConfiguration\t→\tBP"},
    {"label": "BOOL_IND_BP10", "display": "BP10 DO", "origin": "Params\t→\tConfiguration\t→\tBP"},
    {"label": "BOOL_IND_BP11", "display": "BP11 DO", "origin": "Params\t→\tConfiguration\t→\tBP"},
    {"label": "BOOL_IND_BP12", "display": "BP12 DO", "origin": "Params\t→\tConfiguration\t→\tBP"},
    {"label": "BOOL_IND_RCV0", "display": "BOOL_IND_RCV0", "origin": "??"},
    {"label": "BOOL_IND_RCV1", "display": "BOOL_IND_RCV1", "origin": "??"},
    {"label": "BOOL_IND_RCV2", "display": "BOOL_IND_RCV2", "origin": "??"},
    {"label": "BOOL_IND_RCV3", "display": "BOOL_IND_RCV3", "origin": "??"},
    {"label": "BOOL_IND_RCV4", "display": "BOOL_IND_RCV4", "origin": "??"},
    {"label": "BOOL_IND_RCUM", "display": "RC UM DO", "origin": "Params\t→\tConfiguration\t→\tRadio Control OUT"},
    {"label": "BOOL_IND_RCLUP", "display": "RC LEFT UP DO", "origin": "Params\t→\tConfiguration\t→\tRadio Control OUT"},
    {"label": "BOOL_IND_RCLDOWN", "display": "RC LEFT DOWN DO", "origin": "Params\t→\tConfiguration\t→\tRadio Control OUT"},
    {"label": "BOOL_IND_RCRUP", "display": "RC RIGHT UP DO", "origin": "Params\t→\tConfiguration\t→\tRadio Control OUT"},
    {"label": "BOOL_IND_RCRDOWN", "display": "RC RIGHT DOWN DO", "origin": "Params\t→\tConfiguration\t→\tRadio Control OUT"},
    {"label": "BOOL_IND_RCBUP", "display": "RC BOTTOM UP DO", "origin": "Params\t→\tConfiguration\t→\tRadio Control OUT"},
    {"label": "BOOL_IND_RCBDOWN", "display": "RC BOTTOM DOWN DO", "origin": "Params\t→\tConfiguration\t→\tRadio Control OUT"},
    {"label": "BOOL_IND_RCTLEFT", "display": "RC TOP LEFT DO", "origin": "Params\t→\tConfiguration\t→\tRadio Control OUT"},
    {"label": "BOOL_IND_RCTRIGHT", "display": "RC TOP RIGHT DO", "origin": "Params\t→\tConfiguration\t→\tRadio Control OUT"},
    {"label": "BOOL_IND_EMGCYRESETBTN", "display": "EMGCY RESET BTN DO", "origin": "Params\t→\tConfiguration\t→\tSafety"},
    {"label": "BOOL_IND_RCALARM", "display": "RC ALARM DO", "origin": "Params\t→\tConfiguration\t→\tRadio Control OUT"},
    {"label": "BOOL_IND_EMGCYRESET", "display": "EMGCY RESET LIGHT DO", "origin": "Params\t→\tConfiguration\t→\tSafety"},
    {"label": "BOOL_IND_INVERTERRESET", "display": "BOOL_IND_INVERTERRESET", "origin": "??"},
    {"label": "BOOL_IND_INVERTERALARM", "display": "BOOL_IND_INVERTERALARM", "origin": "??"},
    {"label": "BOOL_IND_AUTOSTARTING", "display": "BOOL_IND_AUTOSTARTING", "origin": "??"},
    {"label": "BOOL_IND_PINCHPRESSFRONTREAR", "display": "PINC PRESS AR DO",
     "origin": "Params\t→\tConfiguration\t→\tPinch Preload"},
    {"label": "BOOL_IND_PINCHPRESSFRONTREAR2", "display": "PINC PRESS AR2 DO",
     "origin": "Params\t→\tConfiguration\t→\tPinch Preload"},
    {"label": "BOOL_IND_HOLDTORUNRC", "display": "BOOL_IND_HOLDTORUNRC", "origin": "??"},
    {"label": "BOOL_IND_PRELOADUP", "display": "BOOL_IND_PRELOADUP", "origin": "??"},
    {"label": "BOOL_IND_PRELOADPINCHDISABLED", "display": "BOOL_IND_PRELOADPINCHDISABLED", "origin": "??"},
    {"label": "BOOL_IND_PARTMAN", "display": "BOOL_IND_PARTMAN", "origin": "??"},
    {"label": "BOOL_IND_PARTMANBEGIN", "display": "BOOL_IND_PARTMANBEGIN", "origin": "??"},
    {"label": "BOOL_IND_FREE_118", "display": "BOOL_IND_FREE_118", "origin": "??"},
    {"label": "BOOL_IND_FREE_119", "display": "BOOL_IND_FREE_119", "origin": "??"},
    {"label": "BOOL_IND_FREE_120", "display": "BOOL_IND_FREE_120", "origin": "??"},
    {"label": "BOOL_IND_FREE_121", "display": "BOOL_IND_FREE_121", "origin": "??"},
    {"label": "BOOL_IND_FREE_122", "display": "BOOL_IND_FREE_122", "origin": "??"},
    {"label": "BOOL_IND_FREE_123", "display": "BOOL_IND_FREE_123", "origin": "??"},
    {"label": "BOOL_IND_FREE_124", "display": "BOOL_IND_FREE_124", "origin": "??"},
    {"label": "BOOL_IND_FREE_125", "display": "BOOL_IND_FREE_125", "origin": "??"},
    {"label": "BOOL_IND_FREE_126", "display": "BOOL_IND_FREE_126", "origin": "??"},
    {"label": "BOOL_IND_FREE_127", "display": "BOOL_IND_FREE_127", "origin": "??"},
    {"label": "BOOL_IND_FREE_128", "display": "BOOL_IND_FREE_128", "origin": "??"},
    {"label": "BOOL_IND_FREE_129", "display": "BOOL_IND_FREE_129", "origin": "??"},
    {"label": "BOOL_IND_FREE_130", "display": "BOOL_IND_FREE_130", "origin": "??"},
    {"label": "BOOL_IND_FREE_131", "display": "BOOL_IND_FREE_131", "origin": "??"},
    {"label": "BOOL_IND_FREE_132", "display": "BOOL_IND_FREE_132", "origin": "??"},
    {"label": "BOOL_IND_FREE_133", "display": "BOOL_IND_FREE_133", "origin": "??"},
    {"label": "BOOL_IND_FREE_134", "display": "BOOL_IND_FREE_134", "origin": "??"},
    {"label": "BOOL_IND_FREE_135", "display": "BOOL_IND_FREE_135", "origin": "??"},
    {"label": "BOOL_IND_FREE_136", "display": "SYNC LOAD OUT DO", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tSYNC IO"},
    {"label": "BOOL_IND_FREE_137", "display": "BOOL_IND_FREE_137", "origin": "??"},
    {"label": "BOOL_IND_FREE_138", "display": "SYNC UNLOAD OUT DO", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tSYNC IO"},
    {"label": "BOOL_IND_FREE_139", "display": "BOOL_IND_FREE_139", "origin": "??"},
    {"label": "BOOL_IND_FREE_140", "display": "SYNC START OUT DO", "origin": "Params\t→\tConfiguration\t→\tMain\t→\tSYNC IO"},
    {"label": "BOOL_IND_FREE_141", "display": "BOOL_IND_FREE_141", "origin": "??"},
    {"label": "BOOL_IND_FREE_142", "display": "BOOL_IND_FREE_142", "origin": "??"},
    {"label": "BOOL_IND_FREE_143", "display": "BOOL_IND_FREE_143", "origin": "??"}
]
OUT_IND_LABELS = [e["label"] for e in OUT_IND_MAP]  # retrocompatibilità

Config_Map = {
    "ParamInt": {
        "INT_SN": {"display": "INT_SN", "origin": "??"},
        "INT_MACHTYPE": {"display": "INT_MACHTYPE", "origin": "??"},
        "INT_CALCTYPE": {"display": "INT_CALCTYPE", "origin": "??"},
        "INT_CHECKTYPE": {"display": "INT_CHECKTYPE", "origin": "??"},
        "INT_PRESSPINCHTYPE": {"display": "INT_PRESSPINCHTYPE", "origin": "??"},
        "INT_REFTIME": {"display": "INT_REFTIME", "origin": "??"},
        "INT_HOLDTORUNTYPE": {"display": "INT_HOLDTORUNTYPE", "origin": "??"},
        "INT_NUMCICLIAVG": {"display": "INT_NUMCICLIAVG", "origin": "??"},
        "INT_DEFRADIUSTYPE": {"display": "INT_DEFRADIUSTYPE", "origin": "??"},
        "INT_DECPTYPE": {"display": "INT_DECPTYPE", "origin": "??"},
        "INT_SEPCHTYPE": {"display": "INT_SEPCHTYPE", "origin": "??"},
        "INT_PINCHTYPE": {"display": "INT_PINCHTYPE", "origin": "??"},
        "INT_HOLDTORUNTIMEOUT": {"display": "INT_HOLDTORUNTIMEOUT", "origin": "??"},
        "INT_HOLDTORUNTIMEOUT2": {"display": "INT_HOLDTORUNTIMEOUT2", "origin": "??"},
        "INT_BP1TIMEOUT": {"display": "INT_BP1TIMEOUT", "origin": "??"},
        "INT_BP2TIMEOUT": {"display": "INT_BP2TIMEOUT", "origin": "??"},
        "INT_BP3TIMEOUT": {"display": "INT_BP3TIMEOUT", "origin": "??"},
        "INT_BP4TIMEOUT": {"display": "INT_BP4TIMEOUT", "origin": "??"},
        "INT_BP5TIMEOUT": {"display": "INT_BP5TIMEOUT", "origin": "??"},
        "INT_BP6TIMEOUT": {"display": "INT_BP6TIMEOUT", "origin": "??"},
        "INT_BP7TIMEOUT": {"display": "INT_BP7TIMEOUT", "origin": "??"},
        "INT_BP8TIMEOUT": {"display": "INT_BP8TIMEOUT", "origin": "??"},
        "INT_BP9TIMEOUT": {"display": "INT_BP9TIMEOUT", "origin": "??"},
        "INT_BP10TIMEOUT": {"display": "INT_BP10TIMEOUT", "origin": "??"},
        "INT_BP11TIMEOUT": {"display": "INT_BP11TIMEOUT", "origin": "??"},
        "INT_BP12TIMEOUT": {"display": "INT_BP12TIMEOUT", "origin": "??"},
        "INT_ROLLIND": {"display": "INT_ROLLIND", "origin": "??"},
        "INT_GREASEPUMPSTART": {"display": "PUMP START DO", "origin": "Params\t→\tConfiguration\t→\tGrease", "type": [IO_DO]},
        "INT_GREASETIMEOUT1": {"display": "INT_GREASETIMEOUT1", "origin": "??"},
        "INT_GREASETIMEOUT2": {"display": "INT_GREASETIMEOUT2", "origin": "??"},
        "INT_GREASENUMFB": {"display": "INT_GREASENUMFB", "origin": "??"},
        "INT_GREASETR": {"display": "GREASE TR DI", "origin": "Params\t→\tConfiguration\t→\tGrease\t→\tGrease IN", "type": [IO_DI]},
        "INT_GREASEIN1": {"display": "GREASEIN1 DI", "origin": "Params\t→\tConfiguration\t→\tGrease\t→\tGrease IN", "type": [IO_DI]},
        "INT_GREASEIN2": {"display": "GREASEIN2 DI", "origin": "Params\t→\tConfiguration\t→\tGrease\t→\tGrease IN", "type": [IO_DI]},
        "INT_GREASEIN3": {"display": "GREASEIN3 DI", "origin": "Params\t→\tConfiguration\t→\tGrease\t→\tGrease IN", "type": [IO_DI]},
        "INT_GREASEIN4": {"display": "GREASEIN4 DI", "origin": "Params\t→\tConfiguration\t→\tGrease\t→\tGrease IN", "type": [IO_DI]},
        "INT_GREASEIN5": {"display": "GREASEIN5 DI", "origin": "Params\t→\tConfiguration\t→\tGrease\t→\tGrease IN", "type": [IO_DI]},
        "INT_GREASEIN6": {"display": "GREASEIN6 DI", "origin": "Params\t→\tConfiguration\t→\tGrease\t→\tGrease IN", "type": [IO_DI]},
        "INT_GREASEIN7": {"display": "GREASEIN7 DI", "origin": "Params\t→\tConfiguration\t→\tGrease\t→\tGrease IN", "type": [IO_DI]},
        "INT_GREASEIN8": {"display": "GREASEIN8 DI", "origin": "Params\t→\tConfiguration\t→\tGrease\t→\tGrease IN", "type": [IO_DI]},
        "INT_GREASEIN9": {"display": "GREASEIN9 DI", "origin": "Params\t→\tConfiguration\t→\tGrease\t→\tGrease IN", "type": [IO_DI]},
        "INT_GREASEIN10": {"display": "GREASEIN10 DI", "origin": "Params\t→\tConfiguration\t→\tGrease\t→\tGrease IN", "type": [IO_DI]},
        "INT_GREASEIN11": {"display": "GREASEIN11 DI", "origin": "Params\t→\tConfiguration\t→\tGrease\t→\tGrease IN", "type": [IO_DI]},
        "INT_GREASEIN12": {"display": "GREASEIN12 DI", "origin": "Params\t→\tConfiguration\t→\tGrease\t→\tGrease IN", "type": [IO_DI]},
        "INT_GREASEIN13": {"display": "GREASEIN13 DI", "origin": "Params\t→\tConfiguration\t→\tGrease\t→\tGrease IN", "type": [IO_DI]},
        "INT_GREASEIN15": {"display": "GREASEIN15 DI", "origin": "Params\t→\tConfiguration\t→\tGrease\t→\tGrease IN", "type": [IO_DI]},
        "INT_GREASEIN14": {"display": "GREASEIN14 DI", "origin": "Params\t→\tConfiguration\t→\tGrease\t→\tGrease IN", "type": [IO_DI]},
        "INT_GREASEIN16": {"display": "GREASEIN16 DI", "origin": "Params\t→\tConfiguration\t→\tGrease\t→\tGrease IN", "type": [IO_DI]},
        "INT_GREASEOUT1": {"display": "GREASEOUT1 DO", "origin": "Params\t→\tConfiguration\t→\tGrease\t→\tGrease OUT", "type": [IO_DO]},
        "INT_GREASEOUT2": {"display": "GREASEOUT2 DO", "origin": "Params\t→\tConfiguration\t→\tGrease\t→\tGrease OUT", "type": [IO_DO]},
        "INT_GREASEOUT3": {"display": "GREASEOUT3 DO", "origin": "Params\t→\tConfiguration\t→\tGrease\t→\tGrease OUT", "type": [IO_DO]},
        "INT_GREASEOUT4": {"display": "GREASEOUT4 DO", "origin": "Params\t→\tConfiguration\t→\tGrease\t→\tGrease OUT", "type": [IO_DO]},
        "INT_GREASEOUT5": {"display": "GREASEOUT5 DO", "origin": "Params\t→\tConfiguration\t→\tGrease\t→\tGrease OUT", "type": [IO_DO]},
        "INT_GREASEOUT6": {"display": "GREASEOUT6 DO", "origin": "Params\t→\tConfiguration\t→\tGrease\t→\tGrease OUT", "type": [IO_DO]},
        "INT_GREASEOUT7": {"display": "GREASEOUT7 DO", "origin": "Params\t→\tConfiguration\t→\tGrease\t→\tGrease OUT", "type": [IO_DO]},
        "INT_GREASEOUT8": {"display": "GREASEOUT8 DO", "origin": "Params\t→\tConfiguration\t→\tGrease\t→\tGrease OUT", "type": [IO_DO]},
        "INT_GREASEOUT9": {"display": "GREASEOUT9 DO", "origin": "Params\t→\tConfiguration\t→\tGrease\t→\tGrease OUT", "type": [IO_DO]},
        "INT_GREASEOUT10": {"display": "GREASEOUT10 DO", "origin": "Params\t→\tConfiguration\t→\tGrease\t→\tGrease OUT", "type": [IO_DO]},
        "INT_GREASEOUT11": {"display": "GREASEOUT11 DO", "origin": "Params\t→\tConfiguration\t→\tGrease\t→\tGrease OUT", "type": [IO_DO]},
        "INT_GREASEOUT12": {"display": "GREASEOUT12 DO", "origin": "Params\t→\tConfiguration\t→\tGrease\t→\tGrease OUT", "type": [IO_DO]},
        "INT_GREASEOUT13": {"display": "GREASEOUT13 DO", "origin": "Params\t→\tConfiguration\t→\tGrease\t→\tGrease OUT", "type": [IO_DO]},
        "INT_GREASEOUT14": {"display": "GREASEOUT14 DO", "origin": "Params\t→\tConfiguration\t→\tGrease\t→\tGrease OUT", "type": [IO_DO]},
        "INT_GREASEOUT15": {"display": "GREASEOUT15 DO", "origin": "Params\t→\tConfiguration\t→\tGrease\t→\tGrease OUT", "type": [IO_DO]},
        "INT_GREASEOUT16": {"display": "GREASEOUT16 DO", "origin": "Params\t→\tConfiguration\t→\tGrease\t→\tGrease OUT", "type": [IO_DO]},
        "INT_GREASENUMV": {"display": "INT_GREASENUMV", "origin": "??"},
        "INT_GREASEPUMPON": {"display": "PUMP ON DI", "origin": "Params\t→\tConfiguration\t→\tGrease", "type": [IO_DI]},
        "INT_RECYCVALVEIND": {"display": "INT_RECYCVALVEIND", "origin": "Motors", "type": [IO_DI]},
        "INT_RECYCVALVETIMEOUT": {"display": "INT_RECYCVALVETIMEOUT", "origin": "??"},
        "INT_PINCHPRESSSPEED": {"display": "INT_PINCHPRESSSPEED", "origin": "??"},
        "INT_RTTYPE": {"display": "INT_RTTYPE", "origin": "??"},
        "INT_AVGDT_IND": {"display": "INT_AVGDT_IND", "origin": "??"},
        "INT_NHDT_IND": {"display": "INT_NHDT_IND", "origin": "??"},
        "INT_RESETTYPE": {"display": "INT_RESETTYPE", "origin": "??"},
        "INT_ARCHIMETER_COMUSB": {"display": "INT_ARCHIMETER_COMUSB", "origin": "??"},
        "INT_ARCHIMETER_COMWIFI": {"display": "INT_ARCHIMETER_COMWIFI", "origin": "??"},
        "INT_ARCHIMETER_TIMEOUT": {"display": "INT_ARCHIMETER_TIMEOUT", "origin": "??"},
        "INT_RCTYPE": {"display": "INT_RCTYPE", "origin": "??"},
        "INT_RCSEL": {"display": "INT_RCSEL", "origin": "??"},
        "INT_ROLLERCHANGESEQ": {"display": "INT_ROLLERCHANGESEQ", "origin": "??"},
        "INT_ROLLNUM": {"display": "INT_ROLLNUM", "origin": "??"},
    }
}


def Config_Map_indexes():
    new_entries = {}
    for key, value in Config_Map.items():
        if isinstance(value, dict):
            new_entries[f'_{key}'] = {i: k for i, k in enumerate(value.keys())}
    return new_entries


Config_Map.update(Config_Map_indexes())

Type_AxisParam_Map = {
    "boolval": {
        "ASSE_BOOL_CONFIG": {"display": "CONFIG", "origin": "Axes\t→\t[{}]{}"},
        "ASSE_BOOL_BP1": {"display": "BP1", "origin": "Axes\t→\t[{}]{}\t→\tBP"},
        "ASSE_BOOL_BP2": {"display": "BP2", "origin": "Axes\t→\t[{}]{}\t→\tBP"},
        "ASSE_BOOL_BP3": {"display": "BP3", "origin": "Axes\t→\t[{}]{}\t→\tBP"},
        "ASSE_BOOL_BP4": {"display": "BP4", "origin": "Axes\t→\t[{}]{}\t→\tBP"},
        "ASSE_BOOL_BP5": {"display": "BP5", "origin": "Axes\t→\t[{}]{}\t→\tBP"},
        "ASSE_BOOL_BP6": {"display": "BP6", "origin": "Axes\t→\t[{}]{}\t→\tBP"},
        "ASSE_BOOL_BP7": {"display": "BP7", "origin": "Axes\t→\t[{}]{}\t→\tBP"},
        "ASSE_BOOL_BP8": {"display": "BP8", "origin": "Axes\t→\t[{}]{}\t→\tBP"},
        "ASSE_BOOL_BP9": {"display": "BP9", "origin": "Axes\t→\t[{}]{}\t→\tBP"},
        "ASSE_BOOL_BP10": {"display": "BP10", "origin": "Axes\t→\t[{}]{}\t→\tBP"},
        "ASSE_BOOL_BP11": {"display": "BP11", "origin": "Axes\t→\t[{}]{}\t→\tBP"},
        "ASSE_BOOL_BP12": {"display": "BP12", "origin": "Axes\t→\t[{}]{}\t→\tBP"},
        "ASSE_BOOL_FLAGCOUPMAX": {"display": "COUP MAX", "origin": "Axes\t→\t[{}]{}\t→\tSafety/Interlock"},
        "ASSE_BOOL_SHOWMAN": {"display": "SHOW MAN", "origin": "Axes\t→\t[{}]{}"},
        "ASSE_BOOL_SHOWAUTO": {"display": "SHOW AUTO", "origin": "Axes\t→\t[{}]{}"},
        "ASSE_BOOL_ENABAXIS": {"display": "ENABLE AXIS", "origin": "Axes\t→\t[{}]{}"},
        "ASSE_BOOL_ENABINTERP": {"display": "ENABLE INTERLP", "origin": "Axes\t→\t[{}]{}"},
        "ASSE_BOOL_ENABTEACH": {"display": "ENABLE TEACH", "origin": "Axes\t→\t[{}]{}"},
        "ASSE_BOOL_ENABSMAX": {"display": "MAX", "origin": "Axes\t→\t[{}]{}"},
        "ASSE_BOOL_ENABSMIN": {"display": "MIN", "origin": "Axes\t→\t[{}]{}"},
        "ASSE_BOOL_ENABSHH": {"display": "HH", "origin": "Axes\t→\t[{}]{}"},
        "ASSE_BOOL_ENABSH": {"display": "H", "origin": "Axes\t→\t[{}]{}"},
        "ASSE_BOOL_ENABSL": {"display": "L", "origin": "Axes\t→\t[{}]{}"},
        "ASSE_BOOL_ENABSLL": {"display": "LL", "origin": "Axes\t→\t[{}]{}"},
        "ASSE_BOOL_CONFIGUP": {"display": "CONFIG UP", "origin": "Axes\t→\t[{}]{}"},
        "ASSE_BOOL_CONFIGDOWN": {"display": "CONFIG DOWN", "origin": "Axes\t→\t[{}]{}"},
        "ASSE_BOOL_FLAGINV": {"display": "FLAG INV", "origin": "Axes\t→\t[{}]{}"},
        "ASSE_BOOL_CHECKSTOPDISABLED": {"display": "CHECK STOP DIS", "origin": "Axes\t→\t[{}]{}"},
        "ASSE_BOOL_SHOWDELTA": {"display": "SHOW DELTA", "origin": "Axes\t→\t[{}]{}"},
        "ASSE_BOOL_DISABLEDELTA": {"display": "DISABLE DELTA", "origin": "Axes\t→\t[{}]{}"},
        "ASSE_BOOL_ENABSH0": {"display": "H0", "origin": "Axes\t→\t[{}]{}"},
        "ASSE_BOOL_ENABSL0": {"display": "L0", "origin": "Axes\t→\t[{}]{}"},
        "ASSE_BOOL_MANSPUP": {"display": "MAN SP UP", "origin": "Axes\t→\t[{}]{}"},
        "ASSE_BOOL_MANSPDOWN": {"display": "MAN SP DOWN", "origin": "Axes\t→\t[{}]{}"},
        "ASSE_BOOL_SHOWDELTATAB": {"display": "SHOW DELTA TAB", "origin": "Axes\t→\t[{}]{}"},
        "ASSE_BOOL_NOMACHINESTARTED": {"display": "NO STARTED", "origin": "Axes\t→\t[{}]{}"},
        "ASSE_BOOL_AXISNOMOVE": {"display": "NO MOVE", "origin": "Axes\t→\t[{}]{}"},
        "ASSE_BOOL_COUPCALC": {"display": "COUP CALC", "origin": "Axes\t→\t[{}]{}\t→\tSafety/Interlock"},
        "ASSE_BOOL_FREE_39": {"display": "ASSE_BOOL_FREE_39", "origin": "??"},
        "ASSE_BOOL_FREE_40": {"display": "ASSE_BOOL_FREE_40", "origin": "??"},
    },
    "intval": {
        "ASSE_INT_MASTER": {"display": "MASTER", "origin": "Axes\t→\t[{}]{}", "type": [Type_Axis, Type_AxisParam]},
        "ASSE_INT_FEEDBACK": {"display": "FB", "origin": "Axes\t→\t[{}]{}", "type": [Type_Feedback, Type_FeedbackParam]},
        "ASSE_INT_INPUT": {"display": "INPUT1", "origin": "Axes\t→\t[{}]{}", "type": [Type_Input, Type_InputParam]},
        "ASSE_INT_INPUT2": {"display": "INPUT2", "origin": "Axes\t→\t[{}]{}", "type": [Type_Input, Type_InputParam]},
        "ASSE_INT_INPUT3": {"display": "INPUT3", "origin": "Axes\t→\t[{}]{}", "type": [Type_Input, Type_InputParam]},
        "ASSE_INT_INPUT4": {"display": "INPUT4", "origin": "Axes\t→\t[{}]{}", "type": [Type_Input, Type_InputParam]},
        "ASSE_INT_OUTPUT1": {"display": "OUTPUT1", "origin": "Axes\t→\t[{}]{}", "type": [Type_Output, Type_OutputParam]},
        "ASSE_INT_OUTPUT2": {"display": "OUTPUT2", "origin": "Axes\t→\t[{}]{}", "type": [Type_Output, Type_OutputParam]},
        "ASSE_INT_OUTPUT3": {"display": "OUTPUT3", "origin": "Axes\t→\t[{}]{}", "type": [Type_Output, Type_OutputParam]},
        "ASSE_INT_OUTPUT4": {"display": "OUTPUT4", "origin": "Axes\t→\t[{}]{}", "type": [Type_Output, Type_OutputParam]},
        "ASSE_INT_LABELTYPE": {"display": "ASSE_INT_LABELTYPE", "origin": "??"},
        "ASSE_INT_LABELROW": {"display": "ASSE_INT_LABELROW", "origin": "??"},
        "ASSE_INT_LABELCOL": {"display": "ASSE_INT_LABELCOL", "origin": "??"},
        "ASSE_INT_LABELNTOT": {"display": "ASSE_INT_LABELNTOT", "origin": "??"},
        "ASSE_INT_LABELNDEC": {"display": "ASSE_INT_LABELNDEC", "origin": "??"},
        "ASSE_INT_LABELROWIMP": {"display": "ASSE_INT_LABELROWIMP", "origin": "??"},
        "ASSE_INT_LABELCOLIMP": {"display": "ASSE_INT_LABELCOLIMP", "origin": "??"},
        "ASSE_INT_LABELNTOTIMP": {"display": "ASSE_INT_LABELNTOTIMP", "origin": "??"},
        "ASSE_INT_LABELNDECIMP": {"display": "ASSE_INT_LABELNDECIMP", "origin": "??"},
        "ASSE_INT_SUPLSIND": {"display": "SUP", "origin": "Axes\t→\t[{}]{}", "type": [IO_DI]},
        "ASSE_INT_INFLSIND": {"display": "INF", "origin": "Axes\t→\t[{}]{}", "type": [IO_DI]},
        "ASSE_INT_P1": {"display": "ASSE_INT_P1", "origin": "??"},
        "ASSE_INT_P2": {"display": "ASSE_INT_P2", "origin": "??"},
        "ASSE_INT_TIMEOUT1": {"display": "ASSE_INT_TIMEOUT1", "origin": "??"},
        "ASSE_INT_TIMEOUT2": {"display": "ASSE_INT_TIMEOUT2", "origin": "??"},
        "ASSE_INT_BOOSTVAL": {"display": "ASSE_INT_BOOSTVAL", "origin": "??"},
        "ASSE_INT_TIPOMISURA": {"display": "TIPOMISURA", "origin": "Axes\t→\t[{}]{}"},
        "ASSE_INT_DEFSPEED": {"display": "ASSE_INT_DEFSPEED", "origin": "??"},
        "ASSE_INT_MOVEMODE": {"display": "ASSE_INT_MOVEMODE", "origin": "??"},
        "ASSE_INT_INTERPGROUP": {"display": "GROUP", "origin": "Axes\t→\t[{}]{}"},
        "ASSE_INT_ALTFB": {"display": "ALTFB", "origin": "Axes\t→\t[{}]{}", "type": [Type_Feedback, Type_FeedbackParam]},
        "ASSE_INT_ALTFBDIG": {"display": "ALT FB DIG", "origin": "Axes\t→\t[{}]{}", "type": [IO_DI]},
        "ASSE_INT_INDSHH": {"display": "HH", "origin": "Axes\t→\t[{}]{}", "type": [IO_DI]},
        "ASSE_INT_INDSH": {"display": "H", "origin": "Axes\t→\t[{}]{}", "type": [IO_DI]},
        "ASSE_INT_INDSL": {"display": "L", "origin": "Axes\t→\t[{}]{}", "type": [IO_DI]},
        "ASSE_INT_INDSLL": {"display": "LL", "origin": "Axes\t→\t[{}]{}", "type": [IO_DI]},
        "ASSE_INT_SAFETYUPIND1": {"display": "SAFETY1 UP", "origin": "Axes\t→\t[{}]{}\t→\tSafety/Interlock", "type": [IO_DI]},
        "ASSE_INT_SAFETYUPIND2": {"display": "SAFETY2 UP", "origin": "Axes\t→\t[{}]{}\t→\tSafety/Interlock", "type": [IO_DI]},
        "ASSE_INT_SAFETYUPIND3": {"display": "SAFETY3 UP", "origin": "Axes\t→\t[{}]{}\t→\tSafety/Interlock", "type": [IO_DI]},
        "ASSE_INT_SAFETYUPIND4": {"display": "SAFETY4 UP", "origin": "Axes\t→\t[{}]{}\t→\tSafety/Interlock", "type": [IO_DI]},
        "ASSE_INT_SAFETYUPIND5": {"display": "SAFETY5 UP", "origin": "Axes\t→\t[{}]{}\t→\tSafety/Interlock", "type": [IO_DI]},
        "ASSE_INT_SAFETYUPIND6": {"display": "SAFETY6 UP", "origin": "Axes\t→\t[{}]{}\t→\tSafety/Interlock", "type": [IO_DI]},
        "ASSE_INT_INDSH0": {"display": "H0", "origin": "Axes\t→\t[{}]{}", "type": [IO_DI]},
        "ASSE_INT_INDSL0": {"display": "L0", "origin": "Axes\t→\t[{}]{}", "type": [IO_DI]},
        "ASSE_INT_INDMEM": {"display": "INDMEM", "origin": "Axes\t→\t[{}]{}\t→\tControl", "type": [IO_RI]},
        "ASSE_INT_PERACQ": {"display": "ASSE_INT_PERACQ", "origin": "??"},
        "ASSE_INT_NUMTIMEOUT": {"display": "ASSE_INT_NUMTIMEOUT", "origin": "??"},
        "ASSE_INT_PERVELAVG": {"display": "ASSE_INT_PERVELAVG", "origin": "??"},
        "ASSE_INT_SAFETYDOWNIND1": {"display": "SAFETY1 DOWN", "origin": "Axes\t→\t[{}]{}\t→\tSafety/Interlock", "type": [IO_DI]},
        "ASSE_INT_SAFETYDOWNIND2": {"display": "SAFETY2 DOWN", "origin": "Axes\t→\t[{}]{}\t→\tSafety/Interlock", "type": [IO_DI]},
        "ASSE_INT_SAFETYDOWNIND3": {"display": "SAFETY3 DOWN", "origin": "Axes\t→\t[{}]{}\t→\tSafety/Interlock", "type": [IO_DI]},
        "ASSE_INT_SAFETYDOWNIND4": {"display": "SAFETY4 DOWN", "origin": "Axes\t→\t[{}]{}\t→\tSafety/Interlock", "type": [IO_DI]},
        "ASSE_INT_SAFETYDOWNIND5": {"display": "SAFETY5 DOWN", "origin": "Axes\t→\t[{}]{}\t→\tSafety/Interlock", "type": [IO_DI]},
        "ASSE_INT_SAFETYDOWNIND6": {"display": "SAFETY6 DOWN", "origin": "Axes\t→\t[{}]{}\t→\tSafety/Interlock", "type": [IO_DI]},
        "ASSE_INT_DELAYUP": {"display": "ASSE_INT_DELAYUP", "origin": "??"},
        "ASSE_INT_DELAYDOWN": {"display": "ASSE_INT_DELAYDOWN", "origin": "??"},
        "ASSE_INT_MAXVELPERC": {"display": "ASSE_INT_MAXVELPERC", "origin": "??"},
        "ASSE_INT_DECOUPMASTER": {"display": "DECOUPLE 1 AUTO", "origin": "Axes\t→\t[{}]{}\t→\tSafety/Interlock", "type": [IO_DI]},
        "ASSE_INT_DECOUPMASTER2": {"display": "DECOUPLE 2 MAN", "origin": "Axes\t→\t[{}]{}\t→\tSafety/Interlock", "type": [IO_DI]},
        "ASSE_INT_DECOUPMASTER3": {"display": "DECOUPLE 3 MAN", "origin": "Axes\t→\t[{}]{}\t→\tSafety/Interlock", "type": [IO_DI]},
        "ASSE_INT_DECOUPMASTER4": {"display": "DECOUPLE 4 MAN", "origin": "Axes\t→\t[{}]{}\t→\tSafety/Interlock", "type": [IO_DI]},
        "ASSE_INT_DECOUPMASTER5": {"display": "DECOUPLE 5 MAN", "origin": "Axes\t→\t[{}]{}\t→\tSafety/Interlock", "type": [IO_DI]},
        "ASSE_INT_DECOUPMASTER6": {"display": "DECOUPLE 6 MAN", "origin": "Axes\t→\t[{}]{}\t→\tSafety/Interlock", "type": [IO_DI]},
        "ASSE_INT_PS": {"display": "PS1", "origin": "Axes\t→\t[{}]{}\t→\tPressure", "type": [IO_DI]},
        "ASSE_INT_BWVSLOW": {"display": "BWVSLOW", "origin": "Axes\t→\t[{}]{}"},
        "ASSE_INT_FWVSLOW": {"display": "FWVSLOW", "origin": "Axes\t→\t[{}]{}"},
        "ASSE_INT_PS2": {"display": "PS2", "origin": "Axes\t→\t[{}]{}\t→\tPressure", "type": [IO_DI]},
        "ASSE_INT_PS3": {"display": "PS3", "origin": "Axes\t→\t[{}]{}\t→\tPressure", "type": [IO_DI]},
        "ASSE_INT_AXISCOUPCHECK": {"display": "ASSE_INT_AXISCOUPCHECK", "origin": "??"},
        "ASSE_INT_TEACHMINMULT": {"display": "ASSE_INT_TEACHMINMULT", "origin": "??"},
        "ASSE_INT_FREE_70": {"display": "FREE 70 DI", "origin": "Axes\t→\t[{}]{}\t→\tControl", "type": [IO_DI]},
        "ASSE_INT_FREE_71": {"display": "FREE 71 DI", "origin": "Axes\t→\t[{}]{}\t→\tControl", "type": [IO_DI]},
        "ASSE_INT_PID": {"display": "PID", "origin": "Axes\t→\t[{}]{}"},
        "ASSE_INT_GRAFIND": {"display": "GRAFIND", "origin": "Axes\t→\t[{}]{}"},
        "ASSE_INT_DELTA1": {"display": "ASSE_INT_DELTA1", "origin": "??"},
        "ASSE_INT_OPTPARAMIND": {"display": "OPT PARAM AI", "origin": "Axes\t→\t[{}]{}\t→\tControl", "type": [IO_AI]},
        "ASSE_INT_DISABLEBP1": {"display": "ASSE_INT_DISABLEBP1", "origin": "Axes\t→\t[{}]{}\t→\tBP", "type": [IO_DI]},
        "ASSE_INT_DISABLEBP2": {"display": "ASSE_INT_DISABLEBP2", "origin": "Axes\t→\t[{}]{}\t→\tBP", "type": [IO_DI]},
        "ASSE_INT_DISABLEBP3": {"display": "ASSE_INT_DISABLEBP3", "origin": "Axes\t→\t[{}]{}\t→\tBP", "type": [IO_DI]},
        "ASSE_INT_DISABLEBP4": {"display": "ASSE_INT_DISABLEBP4", "origin": "Axes\t→\t[{}]{}\t→\tBP", "type": [IO_DI]},
        "ASSE_INT_DISABLEBP5": {"display": "ASSE_INT_DISABLEBP5", "origin": "Axes\t→\t[{}]{}\t→\tBP", "type": [IO_DI]},
        "ASSE_INT_DISABLEBP6": {"display": "ASSE_INT_DISABLEBP6", "origin": "Axes\t→\t[{}]{}\t→\tBP", "type": [IO_DI]},
        "ASSE_INT_DISABLEBP7": {"display": "ASSE_INT_DISABLEBP7", "origin": "Axes\t→\t[{}]{}\t→\tBP", "type": [IO_DI]},
        "ASSE_INT_DISABLEBP8": {"display": "ASSE_INT_DISABLEBP8", "origin": "Axes\t→\t[{}]{}\t→\tBP", "type": [IO_DI]},
        "ASSE_INT_DISABLEBP9": {"display": "ASSE_INT_DISABLEBP9", "origin": "Axes\t→\t[{}]{}\t→\tBP", "type": [IO_DI]},
        "ASSE_INT_DISABLEBP10": {"display": "ASSE_INT_DISABLEBP10", "origin": "Axes\t→\t[{}]{}\t→\tBP", "type": [IO_DI]},
        "ASSE_INT_DISABLEBP11": {"display": "ASSE_INT_DISABLEBP11", "origin": "Axes\t→\t[{}]{}\t→\tBP", "type": [IO_DI]},
        "ASSE_INT_DISABLEBP12": {"display": "ASSE_INT_DISABLEBP12", "origin": "Axes\t→\t[{}]{}\t→\tBP", "type": [IO_DI]},
        "ASSE_INT_OPTPARAM1": {"display": "OPTPARAM1 DI", "origin": "Axes\t→\t[{}]{}\t→\tControl", "type": [IO_DI]},
        "ASSE_INT_OPTPARAM2": {"display": "OPTPARAM2 DI", "origin": "Axes\t→\t[{}]{}\t→\tControl", "type": [IO_DI]},
        "ASSE_INT_OPTPARAM3": {"display": "OPTPARAM3 DI", "origin": "Axes\t→\t[{}]{}\t→\tControl", "type": [IO_DI]},
        "ASSE_INT_HOLDTORUNTYPE": {"display": "HOLDTORUNTYPE", "origin": "Axes\t→\t[{}]{}\t→\tControl"},
        "ASSE_INT_FREE_92": {"display": "ASSE_INT_FREE_92", "origin": "??"},
        "ASSE_INT_FREE_93": {"display": "ASSE_INT_FREE_93", "origin": "??"},
        "ASSE_INT_FREE_94": {"display": "ASSE_INT_FREE_94", "origin": "??"},
    },
    "realvalcfg": {
        "ASSE_REAL_SRTUP": {"display": "ASSE_REAL_SRTUP", "origin": "??"},
        "ASSE_REAL_SRTDOWN": {"display": "ASSE_REAL_SRTDOWN", "origin": "??"},
        "ASSE_REAL_COEFFUP": {"display": "ASSE_REAL_COEFFUP", "origin": "??"},
        "ASSE_REAL_COEFFDOWN": {"display": "ASSE_REAL_COEFFDOWN", "origin": "??"},
        "ASSE_REAL_P1UP": {"display": "ASSE_REAL_P1UP", "origin": "??"},
        "ASSE_REAL_P1DOWN": {"display": "ASSE_REAL_P1DOWN", "origin": "??"},
        "ASSE_REAL_P2UP": {"display": "ASSE_REAL_P2UP", "origin": "??"},
        "ASSE_REAL_P2DOWN": {"display": "ASSE_REAL_P2DOWN", "origin": "??"},
        "ASSE_REAL_SYSPRESSUP1": {"display": "ASSE_REAL_SYSPRESSUP1", "origin": "??"},
        "ASSE_REAL_SYSPRESSDOWN1": {"display": "ASSE_REAL_SYSPRESSDOWN1", "origin": "??"},
        "ASSE_REAL_SYSPRESSUP2": {"display": "ASSE_REAL_SYSPRESSUP2", "origin": "??"},
        "ASSE_REAL_SYSPRESSDOWN2": {"display": "ASSE_REAL_SYSPRESSDOWN2", "origin": "??"},
        "ASSE_REAL_SYSPRESSUP3": {"display": "ASSE_REAL_SYSPRESSUP3", "origin": "??"},
        "ASSE_REAL_SYSPRESSDOWN3": {"display": "ASSE_REAL_SYSPRESSDOWN3", "origin": "??"},
        "ASSE_REAL_BWVMAX": {"display": "ASSE_REAL_BWVMAX", "origin": "??"},
        "ASSE_REAL_DSMAXDOWN": {"display": "ASSE_REAL_DSMAXDOWN", "origin": "??"},
        "ASSE_REAL_DSMAXUP": {"display": "ASSE_REAL_DSMAXUP", "origin": "??"},
        "ASSE_REAL_FWVMAX": {"display": "ASSE_REAL_FWVMAX", "origin": "??"},
        "ASSE_REAL_SMAX": {"display": "ASSE_REAL_SMAX", "origin": "??"},
        "ASSE_REAL_SMIN": {"display": "ASSE_REAL_SMIN", "origin": "??"},
        "ASSE_REAL_SSUP": {"display": "ASSE_REAL_SSUP", "origin": "??"},
        "ASSE_REAL_SINF": {"display": "ASSE_REAL_SINF", "origin": "??"},
        "ASSE_REAL_VMINSTARTED": {"display": "ASSE_REAL_VMINSTARTED", "origin": "??"},
        "ASSE_REAL_SHH": {"display": "ASSE_REAL_SHH", "origin": "??"},
        "ASSE_REAL_SH": {"display": "ASSE_REAL_SH", "origin": "??"},
        "ASSE_REAL_SL": {"display": "ASSE_REAL_SL", "origin": "??"},
        "ASSE_REAL_SLL": {"display": "ASSE_REAL_SLL", "origin": "??"},
        "ASSE_REAL_TILTMAX": {"display": "ASSE_REAL_TILTMAX", "origin": "??"},
        "ASSE_REAL_MASTERMULT": {"display": "ASSE_REAL_MASTERMULT", "origin": "??"},
        "ASSE_REAL_MASTERDELTAMIN": {"display": "ASSE_REAL_MASTERDELTAMIN", "origin": "??"},
        "ASSE_REAL_MASTERKSRS": {"display": "ASSE_REAL_MASTERKSRS", "origin": "??"},
        "ASSE_REAL_SLAVEVRESET": {"display": "ASSE_REAL_SLAVEVRESET", "origin": "??"},
        "ASSE_REAL_SLAVEVMIN": {"display": "ASSE_REAL_SLAVEVMIN", "origin": "??"},
        "ASSE_REAL_SLAVEDELTATSTART": {"display": "ASSE_REAL_SLAVEDELTATSTART", "origin": "??"},
        "ASSE_REAL_OUTKP": {"display": "ASSE_REAL_OUTKP", "origin": "??"},
        "ASSE_REAL_OUTDELTAT": {"display": "ASSE_REAL_OUTDELTAT", "origin": "??"},
        "ASSE_REAL_SH0": {"display": "ASSE_REAL_SH0", "origin": "??"},
        "ASSE_REAL_SL0": {"display": "ASSE_REAL_SL0", "origin": "??"},
        "ASSE_REAL_TILTMAXDOWN": {"display": "ASSE_REAL_TILTMAXDOWN", "origin": "??"},
        "ASSE_REAL_FREE_39": {"display": "ASSE_REAL_FREE_39", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGUP": {"display": "ASSE_REAL_DELTAMOVINGUP", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGDOWN": {"display": "ASSE_REAL_DELTAMOVINGDOWN", "origin": "??"},
        "ASSE_REAL_DELTADIV": {"display": "ASSE_REAL_DELTADIV", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGSUPUP": {"display": "ASSE_REAL_DELTAMOVINGSUPUP", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGINFUP": {"display": "ASSE_REAL_DELTAMOVINGINFUP", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGSUPDOWN": {"display": "ASSE_REAL_DELTAMOVINGSUPDOWN", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGINFDOWN": {"display": "ASSE_REAL_DELTAMOVINGINFDOWN", "origin": "??"},
        "ASSE_REAL_DELTAAUTO": {"display": "ASSE_REAL_DELTAAUTO", "origin": "??"},
        "ASSE_REAL_BWACCMAX": {"display": "ASSE_REAL_BWACCMAX", "origin": "??"},
        "ASSE_REAL_FWACCMAX": {"display": "ASSE_REAL_FWACCMAX", "origin": "??"},
        "ASSE_REAL_OPTPARAM1": {"display": "ASSE_REAL_OPTPARAM1", "origin": "??"},
        "ASSE_REAL_OPTPARAM2": {"display": "ASSE_REAL_OPTPARAM2", "origin": "??"},
        "ASSE_REAL_OPTPARAM3": {"display": "ASSE_REAL_OPTPARAM3", "origin": "??"},
        "ASSE_REAL_AXISCOUPMIN": {"display": "ASSE_REAL_AXISCOUPMIN", "origin": "??"},
        "ASSE_REAL_FREE_54": {"display": "ASSE_REAL_FREE_54", "origin": "??"},

    },
    "realval": {
        "ASSE_REAL_SRTUP": {"display": "SRT UP (FW)", "origin": "Axes\t→\t[{}]{}\t→\tControl"},
        "ASSE_REAL_SRTDOWN": {"display": "SRT DOWN (BW)", "origin": "Axes\t→\t[{}]{}\t→\tControl"},
        "ASSE_REAL_COEFFUP": {"display": "COEFF UP (FW)", "origin": "Axes\t→\t[{}]{}\t→\tControl"},
        "ASSE_REAL_COEFFDOWN": {"display": "COEFF DOWN (BW)", "origin": "Axes\t→\t[{}]{}\t→\tControl"},
        "ASSE_REAL_P1UP": {"display": "P1 UP", "origin": "Axes\t→\t[{}]{}\t→\tPressure"},
        "ASSE_REAL_P1DOWN": {"display": "P1 DOWN", "origin": "Axes\t→\t[{}]{}\t→\tPressure"},
        "ASSE_REAL_P2UP": {"display": "P2 UP", "origin": "Axes\t→\t[{}]{}\t→\tPressure"},
        "ASSE_REAL_P2DOWN": {"display": "P2 DOWN", "origin": "Axes\t→\t[{}]{}\t→\tPressure"},
        "ASSE_REAL_SYSPRESSUP1": {"display": "SYSPRESS1 UP", "origin": "Axes\t→\t[{}]{}\t→\tPressure"},
        "ASSE_REAL_SYSPRESSDOWN1": {"display": "SYSPRESS1 DOWN", "origin": "Axes\t→\t[{}]{}\t→\tPressure"},
        "ASSE_REAL_SYSPRESSUP2": {"display": "SYSPRESS2 UP", "origin": "Axes\t→\t[{}]{}\t→\tPressure"},
        "ASSE_REAL_SYSPRESSDOWN2": {"display": "SYSPRESS2 DOWN", "origin": "Axes\t→\t[{}]{}\t→\tPressure"},
        "ASSE_REAL_SYSPRESSUP3": {"display": "SYSPRESS3 UP", "origin": "Axes\t→\t[{}]{}\t→\tPressure"},
        "ASSE_REAL_SYSPRESSDOWN3": {"display": "ASSE_REAL_SYSPRESS3 DOWN", "origin": "Axes\t→\t[{}]{}\t→\tPressure"},
        "ASSE_REAL_BWVMAX": {"display": "MAX SPEED (BW)", "origin": "Axes\t→\t[{}]{}\t→\tControl"},
        "ASSE_REAL_DSMAXDOWN": {"display": "ASSE_REAL_DSMAXDOWN", "origin": "??"},
        "ASSE_REAL_DSMAXUP": {"display": "ASSE_REAL_DSMAXUP", "origin": "Axes\t→\t[{}]{}\t→\tControl"},
        "ASSE_REAL_FWVMAX": {"display": "MAX SPEED (FW)", "origin": "Axes\t→\t[{}]{}\t→\tControl"},
        "ASSE_REAL_SMAX": {"display": "MAX", "origin": "Axes\t→\t[{}]{}\t→\tControl"},
        "ASSE_REAL_SMIN": {"display": "MIN", "origin": "Axes\t→\t[{}]{}\t→\tControl"},
        "ASSE_REAL_SSUP": {"display": "SUP", "origin": "Axes\t→\t[{}]{}\t→\tControl"},
        "ASSE_REAL_SINF": {"display": "INF", "origin": "Axes\t→\t[{}]{}\t→\tControl"},
        "ASSE_REAL_VMINSTARTED": {"display": "ASSE_REAL_VMINSTARTED", "origin": "??"},
        "ASSE_REAL_SHH": {"display": "HH", "origin": "Axes\t→\t[{}]{}\t→\tControl"},
        "ASSE_REAL_SH": {"display": "H", "origin": "Axes\t→\t[{}]{}\t→\tControl"},
        "ASSE_REAL_SL": {"display": "L", "origin": "Axes\t→\t[{}]{}\t→\tControl"},
        "ASSE_REAL_SLL": {"display": "LL", "origin": "Axes\t→\t[{}]{}\t→\tControl"},
        "ASSE_REAL_TILTMAX": {"display": "TILT MAX UP", "origin": "Axes\t→\t[{}]{}"},
        "ASSE_REAL_MASTERMULT": {"display": "MASTER MULT", "origin": "Axes\t→\t[{}]{}\t→\tControl"},
        "ASSE_REAL_MASTERDELTAMIN": {"display": "MASTER DELTAMIN", "origin": "Axes\t→\t[{}]{}\t→\tControl"},
        "ASSE_REAL_MASTERKSRS": {"display": "MASTER KSRS", "origin": "Axes\t→\t[{}]{}\t→\tControl"},
        "ASSE_REAL_SLAVEVRESET": {"display": "SLAVE VRESET", "origin": "Axes\t→\t[{}]{}\t→\tControl"},
        "ASSE_REAL_SLAVEVMIN": {"display": "SLAVE MIN", "origin": "Axes\t→\t[{}]{}\t→\tControl"},
        "ASSE_REAL_SLAVEDELTATSTART": {"display": "SLAVE DELTATSTART", "origin": "Axes\t→\t[{}]{}\t→\tControl"},
        "ASSE_REAL_OUTKP": {"display": "OUT KP", "origin": "Axes\t→\t[{}]{}\t→\tControl"},
        "ASSE_REAL_OUTDELTAT": {"display": "OUT DELTAT", "origin": "Axes\t→\t[{}]{}\t→\tControl"},
        "ASSE_REAL_SH0": {"display": "H0", "origin": "Axes\t→\t[{}]{}\t→\tControl"},
        "ASSE_REAL_SL0": {"display": "L0", "origin": "Axes\t→\t[{}]{}\t→\tControl"},
        "ASSE_REAL_TILTMAXDOWN": {"display": "TILT MAX DOWN", "origin": "Axes\t→\t[{}]{}"},
        "ASSE_REAL_FREE_39": {"display": "TILT MAX TEACH", "origin": "Axes\t→\t[{}]{}"},
        "ASSE_REAL_DELTAMOVINGUP": {"display": "DELTA MOVING (FW)", "origin": "Axes\t→\t[{}]{}\t→\tControl"},
        "ASSE_REAL_DELTAMOVINGDOWN": {"display": "DELTA MOVING (BW)", "origin": "Axes\t→\t[{}]{}\t→\tControl"},
        "ASSE_REAL_DELTADIV": {"display": "DELTA DIV", "origin": "Axes\t→\t[{}]{}\t→\tControl"},
        "ASSE_REAL_DELTAMOVINGSUPUP": {"display": "DELTA MOVING SUP (FW)", "origin": "Axes\t→\t[{}]{}\t→\tControl"},
        "ASSE_REAL_DELTAMOVINGINFUP": {"display": "DELTA MOVING INF (FW)", "origin": "Axes\t→\t[{}]{}\t→\tControl"},
        "ASSE_REAL_DELTAMOVINGSUPDOWN": {"display": "DELTA MOVING SUP (BW)", "origin": "Axes\t→\t[{}]{}\t→\tControl"},
        "ASSE_REAL_DELTAMOVINGINFDOWN": {"display": "DELTA MOVING INF (BW)", "origin": "Axes\t→\t[{}]{}\t→\tControl"},
        "ASSE_REAL_DELTAAUTO": {"display": "DELTA AUTO", "origin": "Axes\t→\t[{}]{}\t→\tControl"},
        "ASSE_REAL_BWACCMAX": {"display": "ASSE_REAL_BWACCMAX", "origin": "??"},
        "ASSE_REAL_FWACCMAX": {"display": "ASSE_REAL_FWACCMAX", "origin": "??"},
        "ASSE_REAL_OPTPARAM1": {"display": "OPTPARAM1", "origin": "Axes\t→\t[{}]{}\t→\tControl"},
        "ASSE_REAL_OPTPARAM2": {"display": "OPTPARAM2", "origin": "Axes\t→\t[{}]{}\t→\tControl"},
        "ASSE_REAL_OPTPARAM3": {"display": "OPTPARAM3", "origin": "Axes\t→\t[{}]{}\t→\tControl"},
        "ASSE_REAL_AXISCOUPMIN": {"display": "ASSE_REAL_AXISCOUPMIN", "origin": "??"},
        "ASSE_REAL_FREE_54": {"display": "ASSE_REAL_FREE_54", "origin": "??"},

    },
    "fcval": {
        "ASSE_REAL_SRTUP": {"label": "ASSE_REAL_SRTUP", "origin": "??"},
        "ASSE_REAL_SRTDOWN": {"label": "ASSE_REAL_SRTDOWN", "origin": "??"},
        "ASSE_REAL_COEFFUP": {"label": "ASSE_REAL_COEFFUP", "origin": "??"},
        "ASSE_REAL_COEFFDOWN": {"label": "ASSE_REAL_COEFFDOWN", "origin": "??"},
        "ASSE_REAL_P1UP": {"label": "ASSE_REAL_P1UP", "origin": "??"},
        "ASSE_REAL_P1DOWN": {"label": "ASSE_REAL_P1DOWN", "origin": "??"},
        "ASSE_REAL_P2UP": {"label": "ASSE_REAL_P2UP", "origin": "??"},
        "ASSE_REAL_P2DOWN": {"label": "ASSE_REAL_P2DOWN", "origin": "??"},
        "ASSE_REAL_SYSPRESSUP1": {"label": "ASSE_REAL_SYSPRESSUP1", "origin": "??"},
        "ASSE_REAL_SYSPRESSDOWN1": {"label": "ASSE_REAL_SYSPRESSDOWN1", "origin": "??"},
        "ASSE_REAL_SYSPRESSUP2": {"label": "ASSE_REAL_SYSPRESSUP2", "origin": "??"},
        "ASSE_REAL_SYSPRESSDOWN2": {"label": "ASSE_REAL_SYSPRESSDOWN2", "origin": "??"},
        "ASSE_REAL_SYSPRESSUP3": {"label": "ASSE_REAL_SYSPRESSUP3", "origin": "??"},
        "ASSE_REAL_SYSPRESSDOWN3": {"label": "ASSE_REAL_SYSPRESSDOWN3", "origin": "??"},
        "ASSE_REAL_BWVMAX": {"label": "ASSE_REAL_BWVMAX", "origin": "??"},
        "ASSE_REAL_DSMAXDOWN": {"label": "ASSE_REAL_DSMAXDOWN", "origin": "??"},
        "ASSE_REAL_DSMAXUP": {"label": "ASSE_REAL_DSMAXUP", "origin": "??"},
        "ASSE_REAL_FWVMAX": {"label": "ASSE_REAL_FWVMAX", "origin": "??"},
        "ASSE_REAL_SMAX": {"label": "ASSE_REAL_SMAX", "origin": "??"},
        "ASSE_REAL_SMIN": {"label": "ASSE_REAL_SMIN", "origin": "??"},
        "ASSE_REAL_SSUP": {"label": "ASSE_REAL_SSUP", "origin": "??"},
        "ASSE_REAL_SINF": {"label": "ASSE_REAL_SINF", "origin": "??"},
        "ASSE_REAL_VMINSTARTED": {"label": "ASSE_REAL_VMINSTARTED", "origin": "??"},
        "ASSE_REAL_SHH": {"label": "ASSE_REAL_SHH", "origin": "??"},
        "ASSE_REAL_SH": {"label": "ASSE_REAL_SH", "origin": "??"},
        "ASSE_REAL_SL": {"label": "ASSE_REAL_SL", "origin": "??"},
        "ASSE_REAL_SLL": {"label": "ASSE_REAL_SLL", "origin": "??"},
        "ASSE_REAL_TILTMAX": {"label": "ASSE_REAL_TILTMAX", "origin": "??"},
        "ASSE_REAL_MASTERMULT": {"label": "ASSE_REAL_MASTERMULT", "origin": "??"},
        "ASSE_REAL_MASTERDELTAMIN": {"label": "ASSE_REAL_MASTERDELTAMIN", "origin": "??"},
        "ASSE_REAL_MASTERKSRS": {"label": "ASSE_REAL_MASTERKSRS", "origin": "??"},
        "ASSE_REAL_SLAVEVRESET": {"label": "ASSE_REAL_SLAVEVRESET", "origin": "??"},
        "ASSE_REAL_SLAVEVMIN": {"label": "ASSE_REAL_SLAVEVMIN", "origin": "??"},
        "ASSE_REAL_SLAVEDELTATSTART": {"label": "ASSE_REAL_SLAVEDELTATSTART", "origin": "??"},
        "ASSE_REAL_OUTKP": {"label": "ASSE_REAL_OUTKP", "origin": "??"},
        "ASSE_REAL_OUTDELTAT": {"label": "ASSE_REAL_OUTDELTAT", "origin": "??"},
        "ASSE_REAL_SH0": {"label": "ASSE_REAL_SH0", "origin": "??"},
        "ASSE_REAL_SL0": {"label": "ASSE_REAL_SL0", "origin": "??"},
        "ASSE_REAL_TILTMAXDOWN": {"label": "ASSE_REAL_TILTMAXDOWN", "origin": "??"},
        "ASSE_REAL_FREE_39": {"label": "ASSE_REAL_FREE_39", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGUP": {"label": "ASSE_REAL_DELTAMOVINGUP", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGDOWN": {"label": "ASSE_REAL_DELTAMOVINGDOWN", "origin": "??"},
        "ASSE_REAL_DELTADIV": {"label": "ASSE_REAL_DELTADIV", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGSUPUP": {"label": "ASSE_REAL_DELTAMOVINGSUPUP", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGINFUP": {"label": "ASSE_REAL_DELTAMOVINGINFUP", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGSUPDOWN": {"label": "ASSE_REAL_DELTAMOVINGSUPDOWN", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGINFDOWN": {"label": "ASSE_REAL_DELTAMOVINGINFDOWN", "origin": "??"},
        "ASSE_REAL_DELTAAUTO": {"label": "ASSE_REAL_DELTAAUTO", "origin": "??"},
        "ASSE_REAL_BWACCMAX": {"label": "ASSE_REAL_BWACCMAX", "origin": "??"},
        "ASSE_REAL_FWACCMAX": {"label": "ASSE_REAL_FWACCMAX", "origin": "??"},
        "ASSE_REAL_OPTPARAM1": {"label": "ASSE_REAL_OPTPARAM1", "origin": "??"},
        "ASSE_REAL_OPTPARAM2": {"label": "ASSE_REAL_OPTPARAM2", "origin": "??"},
        "ASSE_REAL_OPTPARAM3": {"label": "ASSE_REAL_OPTPARAM3", "origin": "??"},
        "ASSE_REAL_AXISCOUPMIN": {"label": "ASSE_REAL_AXISCOUPMIN", "origin": "??"},
        "ASSE_REAL_FREE_54": {"label": "ASSE_REAL_FREE_54", "origin": "??"},

    },
    "offsetval": {
        "ASSE_REAL_SRTUP": {"display": "ASSE_REAL_SRTUP", "origin": "??"},
        "ASSE_REAL_SRTDOWN": {"display": "ASSE_REAL_SRTDOWN", "origin": "??"},
        "ASSE_REAL_COEFFUP": {"display": "ASSE_REAL_COEFFUP", "origin": "??"},
        "ASSE_REAL_COEFFDOWN": {"display": "ASSE_REAL_COEFFDOWN", "origin": "??"},
        "ASSE_REAL_P1UP": {"display": "ASSE_REAL_P1UP", "origin": "??"},
        "ASSE_REAL_P1DOWN": {"display": "ASSE_REAL_P1DOWN", "origin": "??"},
        "ASSE_REAL_P2UP": {"display": "ASSE_REAL_P2UP", "origin": "??"},
        "ASSE_REAL_P2DOWN": {"display": "ASSE_REAL_P2DOWN", "origin": "??"},
        "ASSE_REAL_SYSPRESSUP1": {"display": "ASSE_REAL_SYSPRESSUP1", "origin": "??"},
        "ASSE_REAL_SYSPRESSDOWN1": {"display": "ASSE_REAL_SYSPRESSDOWN1", "origin": "??"},
        "ASSE_REAL_SYSPRESSUP2": {"display": "ASSE_REAL_SYSPRESSUP2", "origin": "??"},
        "ASSE_REAL_SYSPRESSDOWN2": {"display": "ASSE_REAL_SYSPRESSDOWN2", "origin": "??"},
        "ASSE_REAL_SYSPRESSUP3": {"display": "ASSE_REAL_SYSPRESSUP3", "origin": "??"},
        "ASSE_REAL_SYSPRESSDOWN3": {"display": "ASSE_REAL_SYSPRESSDOWN3", "origin": "??"},
        "ASSE_REAL_BWVMAX": {"display": "ASSE_REAL_BWVMAX", "origin": "??"},
        "ASSE_REAL_DSMAXDOWN": {"display": "ASSE_REAL_DSMAXDOWN", "origin": "??"},
        "ASSE_REAL_DSMAXUP": {"display": "ASSE_REAL_DSMAXUP", "origin": "??"},
        "ASSE_REAL_FWVMAX": {"display": "ASSE_REAL_FWVMAX", "origin": "??"},
        "ASSE_REAL_SMAX": {"display": "ASSE_REAL_SMAX", "origin": "??"},
        "ASSE_REAL_SMIN": {"display": "ASSE_REAL_SMIN", "origin": "??"},
        "ASSE_REAL_SSUP": {"display": "ASSE_REAL_SSUP", "origin": "??"},
        "ASSE_REAL_SINF": {"display": "ASSE_REAL_SINF", "origin": "??"},
        "ASSE_REAL_VMINSTARTED": {"display": "ASSE_REAL_VMINSTARTED", "origin": "??"},
        "ASSE_REAL_SHH": {"display": "ASSE_REAL_SHH", "origin": "??"},
        "ASSE_REAL_SH": {"display": "ASSE_REAL_SH", "origin": "??"},
        "ASSE_REAL_SL": {"display": "ASSE_REAL_SL", "origin": "??"},
        "ASSE_REAL_SLL": {"display": "ASSE_REAL_SLL", "origin": "??"},
        "ASSE_REAL_TILTMAX": {"display": "ASSE_REAL_TILTMAX", "origin": "??"},
        "ASSE_REAL_MASTERMULT": {"display": "ASSE_REAL_MASTERMULT", "origin": "??"},
        "ASSE_REAL_MASTERDELTAMIN": {"display": "ASSE_REAL_MASTERDELTAMIN", "origin": "??"},
        "ASSE_REAL_MASTERKSRS": {"display": "ASSE_REAL_MASTERKSRS", "origin": "??"},
        "ASSE_REAL_SLAVEVRESET": {"display": "ASSE_REAL_SLAVEVRESET", "origin": "??"},
        "ASSE_REAL_SLAVEVMIN": {"display": "ASSE_REAL_SLAVEVMIN", "origin": "??"},
        "ASSE_REAL_SLAVEDELTATSTART": {"display": "ASSE_REAL_SLAVEDELTATSTART", "origin": "??"},
        "ASSE_REAL_OUTKP": {"display": "ASSE_REAL_OUTKP", "origin": "??"},
        "ASSE_REAL_OUTDELTAT": {"display": "ASSE_REAL_OUTDELTAT", "origin": "??"},
        "ASSE_REAL_SH0": {"display": "ASSE_REAL_SH0", "origin": "??"},
        "ASSE_REAL_SL0": {"display": "ASSE_REAL_SL0", "origin": "??"},
        "ASSE_REAL_TILTMAXDOWN": {"display": "ASSE_REAL_TILTMAXDOWN", "origin": "??"},
        "ASSE_REAL_FREE_39": {"display": "ASSE_REAL_FREE_39", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGUP": {"display": "ASSE_REAL_DELTAMOVINGUP", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGDOWN": {"display": "ASSE_REAL_DELTAMOVINGDOWN", "origin": "??"},
        "ASSE_REAL_DELTADIV": {"display": "ASSE_REAL_DELTADIV", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGSUPUP": {"display": "ASSE_REAL_DELTAMOVINGSUPUP", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGINFUP": {"display": "ASSE_REAL_DELTAMOVINGINFUP", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGSUPDOWN": {"display": "ASSE_REAL_DELTAMOVINGSUPDOWN", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGINFDOWN": {"display": "ASSE_REAL_DELTAMOVINGINFDOWN", "origin": "??"},
        "ASSE_REAL_DELTAAUTO": {"display": "ASSE_REAL_DELTAAUTO", "origin": "??"},
        "ASSE_REAL_BWACCMAX": {"display": "ASSE_REAL_BWACCMAX", "origin": "??"},
        "ASSE_REAL_FWACCMAX": {"display": "ASSE_REAL_FWACCMAX", "origin": "??"},
        "ASSE_REAL_OPTPARAM1": {"display": "ASSE_REAL_OPTPARAM1", "origin": "??"},
        "ASSE_REAL_OPTPARAM2": {"display": "ASSE_REAL_OPTPARAM2", "origin": "??"},
        "ASSE_REAL_OPTPARAM3": {"display": "ASSE_REAL_OPTPARAM3", "origin": "??"},
        "ASSE_REAL_AXISCOUPMIN": {"display": "ASSE_REAL_AXISCOUPMIN", "origin": "??"},
        "ASSE_REAL_FREE_54": {"display": "ASSE_REAL_FREE_54", "origin": "??"},

    },
    "typval": {
        "ASSE_REAL_SRTUP": {"display": "ASSE_REAL_SRTUP", "origin": "??"},
        "ASSE_REAL_SRTDOWN": {"display": "ASSE_REAL_SRTDOWN", "origin": "??"},
        "ASSE_REAL_COEFFUP": {"display": "ASSE_REAL_COEFFUP", "origin": "??"},
        "ASSE_REAL_COEFFDOWN": {"display": "ASSE_REAL_COEFFDOWN", "origin": "??"},
        "ASSE_REAL_P1UP": {"display": "ASSE_REAL_P1UP", "origin": "??"},
        "ASSE_REAL_P1DOWN": {"display": "ASSE_REAL_P1DOWN", "origin": "??"},
        "ASSE_REAL_P2UP": {"display": "ASSE_REAL_P2UP", "origin": "??"},
        "ASSE_REAL_P2DOWN": {"display": "ASSE_REAL_P2DOWN", "origin": "??"},
        "ASSE_REAL_SYSPRESSUP1": {"display": "ASSE_REAL_SYSPRESSUP1", "origin": "??"},
        "ASSE_REAL_SYSPRESSDOWN1": {"display": "ASSE_REAL_SYSPRESSDOWN1", "origin": "??"},
        "ASSE_REAL_SYSPRESSUP2": {"display": "ASSE_REAL_SYSPRESSUP2", "origin": "??"},
        "ASSE_REAL_SYSPRESSDOWN2": {"display": "ASSE_REAL_SYSPRESSDOWN2", "origin": "??"},
        "ASSE_REAL_SYSPRESSUP3": {"display": "ASSE_REAL_SYSPRESSUP3", "origin": "??"},
        "ASSE_REAL_SYSPRESSDOWN3": {"display": "ASSE_REAL_SYSPRESSDOWN3", "origin": "??"},
        "ASSE_REAL_BWVMAX": {"display": "ASSE_REAL_BWVMAX", "origin": "??"},
        "ASSE_REAL_DSMAXDOWN": {"display": "ASSE_REAL_DSMAXDOWN", "origin": "??"},
        "ASSE_REAL_DSMAXUP": {"display": "ASSE_REAL_DSMAXUP", "origin": "??"},
        "ASSE_REAL_FWVMAX": {"display": "ASSE_REAL_FWVMAX", "origin": "??"},
        "ASSE_REAL_SMAX": {"display": "ASSE_REAL_SMAX", "origin": "??"},
        "ASSE_REAL_SMIN": {"display": "ASSE_REAL_SMIN", "origin": "??"},
        "ASSE_REAL_SSUP": {"display": "ASSE_REAL_SSUP", "origin": "??"},
        "ASSE_REAL_SINF": {"display": "ASSE_REAL_SINF", "origin": "??"},
        "ASSE_REAL_VMINSTARTED": {"display": "ASSE_REAL_VMINSTARTED", "origin": "??"},
        "ASSE_REAL_SHH": {"display": "ASSE_REAL_SHH", "origin": "??"},
        "ASSE_REAL_SH": {"display": "ASSE_REAL_SH", "origin": "??"},
        "ASSE_REAL_SL": {"display": "ASSE_REAL_SL", "origin": "??"},
        "ASSE_REAL_SLL": {"display": "ASSE_REAL_SLL", "origin": "??"},
        "ASSE_REAL_TILTMAX": {"display": "ASSE_REAL_TILTMAX", "origin": "??"},
        "ASSE_REAL_MASTERMULT": {"display": "ASSE_REAL_MASTERMULT", "origin": "??"},
        "ASSE_REAL_MASTERDELTAMIN": {"display": "ASSE_REAL_MASTERDELTAMIN", "origin": "??"},
        "ASSE_REAL_MASTERKSRS": {"display": "ASSE_REAL_MASTERKSRS", "origin": "??"},
        "ASSE_REAL_SLAVEVRESET": {"display": "ASSE_REAL_SLAVEVRESET", "origin": "??"},
        "ASSE_REAL_SLAVEVMIN": {"display": "ASSE_REAL_SLAVEVMIN", "origin": "??"},
        "ASSE_REAL_SLAVEDELTATSTART": {"display": "ASSE_REAL_SLAVEDELTATSTART", "origin": "??"},
        "ASSE_REAL_OUTKP": {"display": "ASSE_REAL_OUTKP", "origin": "??"},
        "ASSE_REAL_OUTDELTAT": {"display": "ASSE_REAL_OUTDELTAT", "origin": "??"},
        "ASSE_REAL_SH0": {"display": "ASSE_REAL_SH0", "origin": "??"},
        "ASSE_REAL_SL0": {"display": "ASSE_REAL_SL0", "origin": "??"},
        "ASSE_REAL_TILTMAXDOWN": {"display": "ASSE_REAL_TILTMAXDOWN", "origin": "??"},
        "ASSE_REAL_FREE_39": {"display": "ASSE_REAL_FREE_39", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGUP": {"display": "ASSE_REAL_DELTAMOVINGUP", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGDOWN": {"display": "ASSE_REAL_DELTAMOVINGDOWN", "origin": "??"},
        "ASSE_REAL_DELTADIV": {"display": "ASSE_REAL_DELTADIV", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGSUPUP": {"display": "ASSE_REAL_DELTAMOVINGSUPUP", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGINFUP": {"display": "ASSE_REAL_DELTAMOVINGINFUP", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGSUPDOWN": {"display": "ASSE_REAL_DELTAMOVINGSUPDOWN", "origin": "??"},
        "ASSE_REAL_DELTAMOVINGINFDOWN": {"display": "ASSE_REAL_DELTAMOVINGINFDOWN", "origin": "??"},
        "ASSE_REAL_DELTAAUTO": {"display": "ASSE_REAL_DELTAAUTO", "origin": "??"},
        "ASSE_REAL_BWACCMAX": {"display": "ASSE_REAL_BWACCMAX", "origin": "??"},
        "ASSE_REAL_FWACCMAX": {"display": "ASSE_REAL_FWACCMAX", "origin": "??"},
        "ASSE_REAL_OPTPARAM1": {"display": "ASSE_REAL_OPTPARAM1", "origin": "??"},
        "ASSE_REAL_OPTPARAM2": {"display": "ASSE_REAL_OPTPARAM2", "origin": "??"},
        "ASSE_REAL_OPTPARAM3": {"display": "ASSE_REAL_OPTPARAM3", "origin": "??"},
        "ASSE_REAL_AXISCOUPMIN": {"display": "ASSE_REAL_AXISCOUPMIN", "origin": "??"},
        "ASSE_REAL_FREE_54": {"display": "ASSE_REAL_FREE_54", "origin": "??"},

    }
}


def axisparam_map_indexes():
    new_entries = {}
    for key, value in Type_AxisParam_Map.items():
        if isinstance(value, dict):
            new_entries[f'_{key}'] = {i: k for i, k in enumerate(value.keys())}
    return new_entries


Type_AxisParam_Map.update(axisparam_map_indexes())

Type_IOParam_Map = {
    "boolval": {
        "IO_BOOL_BDEFVAL": {"display": "IO_BOOL_BDEFVAL", "origin": ""},
        "IO_BOOL_PROG": {"display": "IO_BOOL_PROG", "origin": ""},
        "IO_BOOL_SIM": {"display": "IO_BOOL_SIM", "origin": ""},
        "IO_BOOL_SIMVAL": {"display": "IO_BOOL_SIMVAL", "origin": ""},
    },
    "intval": {
        "IO_INT_ADDRTYPE": {"display": "ADDRESS", "origin": ""},
        "IO_INT_ADDR1": {"display": "ADDR1", "origin": ""},
        "IO_INT_ADDR2": {"display": "ADDR2", "origin": ""},
        "IO_INT_NBYTES": {"display": "IO_INT_NBYTES", "origin": ""},
        "IO_INT_TIPOMISURA": {"display": "IO_INT_TIPOMISURA", "origin": ""},
        "IO_INT_MEMTYPE": {"display": "MEMTYPE", "origin": ""},
        "IO_INT_MEMIND": {"display": "MEMIND", "origin": ""},
        "IO_INT_TIMEOUT": {"display": "TIMEOUT", "origin": ""},
        "IO_INT_ININD": {"display": "IO_INT_ININD", "origin": ""},
    },
    "dintval": {
        "IO_DINT_DDEFVAL": {"display": "IO_DINT_DDEFVAL", "origin": ""},
        "IO_DINT_SIMVAL": {"display": "IO_DINT_SIMVAL", "origin": ""},
    },
    "realvalcfg": {
        "IO_REAL_RDEFVAL": {"display": "IO_REAL_RDEFVAL", "origin": ""},
        "IO_REAL_DEADBAND": {"display": "IO_REAL_DEADBAND", "origin": ""},
        "IO_REAL_TOTDELTAMAX": {"display": "IO_REAL_TOTDELTAMAX", "origin": ""},
        "IO_REAL_COEFFMULT": {"display": "IO_REAL_COEFFMULT", "origin": ""},
    },
    "realval": {
        "IO_REAL_RDEFVAL": {"display": "IO_REAL_RDEFVAL", "origin": ""},
        "IO_REAL_DEADBAND": {"display": "IO_REAL_DEADBAND", "origin": ""},
        "IO_REAL_TOTDELTAMAX": {"display": "IO_REAL_TOTDELTAMAX", "origin": ""},
        "IO_REAL_COEFFMULT": {"display": "IO_REAL_COEFFMULT", "origin": ""},
    },
    "exprintval": {
        # 0: {"display": "typ + (not, opnd, oper) x 8", "origin": ""},

   },
    "exprrealval": {
        "": {"display": "", "origin": ""},
    },
}

Type_AlarmParam_Map = {
    "boolval": {
        "ALARM_BOOL_CONFIG": {"display": "CONFIG", "origin": "Alarms/Maint\t→\tAlarms\t→\t[{}]"},
        "ALARM_BOOL_FLAGOUT": {"display": "INV OUT", "origin": "Alarms/Maint\t→\tAlarms\t→\t[{}]"},
    },
    "intval": {
        "ALARM_INT_MODE": {"display": "ALARM_INT_MODE", "origin": "Alarms/Maint\t→\tAlarms\t→\t[{}] {}", "type": []},
        "ALARM_INT_INDIN": {"display": "IN", "origin": "Alarms/Maint\t→\tAlarms\t→\t[{}] {}", "type": [IO_DI]},
        "ALARM_INT_INDOUT": {"display": "OUT", "origin": "Alarms/Maint\t→\tAlarms\t→\t[{}] {}", "type": [IO_DO]},
        "ALARM_INT_COD": {"display": "COD", "origin": "Alarms/Maint\t→\tAlarms\t→\t[{}] {}"},
        "ALARM_INT_INDENAB": {"display": "ENAB", "origin": "Alarms/Maint\t→\tAlarms\t→\t[{}] {}", "type": [IO_DI]},
        "ALARM_INT_INDDISAB": {"display": "DISAB", "origin": "Alarms/Maint\t→\tAlarms\t→\t[{}] {}", "type": [IO_DI]},
        "ALARM_INT_INDREQACK": {"display": "REQ ACK", "origin": "Alarms/Maint\t→\tAlarms\t→\t[{}] {}", "type": [IO_DI]},
        "ALARM_INT_INDACK": {"display": "ACK", "origin": "Alarms/Maint\t→\tAlarms\t→\t[{}] {}", "type": [IO_DI]},
        "ALARM_INT_TIMEOUT": {"display": "TIMEOUT", "origin": "Alarms/Maint\t→\tAlarms\t→\t[{}] {}", "type": [IO_DI]},
        "ALARM_INT_FREE_9": {"display": "ALARM_INT_FREE_9", "origin": "Alarms/Maint\t→\tAlarms\t→\t[{}] {}", "type": [IO_DI]},
    }
}


def alarmparam_map_indexes():
    new_entries = {}
    for key, value in Type_AlarmParam_Map.items():
        if isinstance(value, dict):
            new_entries[f'_{key}'] = {i: k for i, k in enumerate(value.keys())}
    return new_entries


Type_AlarmParam_Map.update(alarmparam_map_indexes())

Type_MaintParam_Map = {
    "boolval": {
        "MAINT_BOOL_CONFIG": {"display": "CONFIG", "origin": "Alarms/Maint\t→\tMaintenance\t→\t[{}] {}"},
        "MAINT_BOOL_FLAGOUT": {"display": "INV OUT", "origin": "Alarms/Maint\t→\tMaintenance\t→\t[{} {}]"},
    },
    "intval": {
        "MAINT_INT_CHECKTYPE": {"display": "MAINT_INT_CHECKTYPE", "origin": "", "type": []},
        "MAINT_INT_MAXVAL": {"display": "MAINT_INT_MAXVAL", "origin": "", "type": []},
        "MAINT_INT_YYYY": {"display": "MAINT_INT_YYYY", "origin": "", "type": []},
        "MAINT_INT_MM": {"display": "MAINT_INT_MM", "origin": "", "type": []},
        "MAINT_INT_DD": {"display": "MAINT_INT_DD", "origin": "", "type": []},
        "MAINT_INT_HH": {"display": "MAINT_INT_HH", "origin": "", "type": []},
        "MAINT_INT_NN": {"display": "MAINT_INT_NN", "origin": "", "type": []},
        "MAINT_INT_COD": {"display": "MAINT_INT_COD", "origin": "", "type": []},
        "MAINT_INT_INDENAB": {"display": "ENAB", "origin": "Alarms/Maint\t→\tMaintenance\t→\t[{}] {}", "type": [IO_DI]},
        "MAINT_INT_INDDISAB": {"display": "DISAB", "origin": "Alarms/Maint\t→\tMaintenance\t→\t[{}] {}", "type": [IO_DI]},
    }
}


def maintparam_map_indexes():
    new_entries = {}
    for key, value in Type_MaintParam_Map.items():
        if isinstance(value, dict):
            new_entries[f'_{key}'] = {i: k for i, k in enumerate(value.keys())}
    return new_entries


Type_MaintParam_Map.update(maintparam_map_indexes())


Type_InputParam_Map = {
    "boolval": {
        "INPUT_BOOL_HOLDTORUNENAB": {"display": "INPUT_BOOL_HOLDTORUNENAB", "origin": "Input\t→\t[{}]", "type": []},
        "INPUT_BOOL_FREE": {"display": "INPUT_BOOL_FREE", "origin": "Input\t→\t[{}]", "type": []},
    },
    "intval": {
        "INPUT_INT_TIPO": {"display": "TIPO", "origin": "Input\t→\t[{}]", "type": []},
        "INPUT_INT_TIPOMISURA": {"display": "TIPOMISURA", "origin": "Input\t→\t[{}]", "type": []},
        "INPUT_INT_ANAIND": {"display": "ANA", "origin": "Input\t→\t[{}]", "type": [IO_AI]},
        "INPUT_INT_UPIND": {"display": "DIGUP1", "origin": "Input\t→\t[{}]", "type": [IO_DI]},
        "INPUT_INT_DOWNIND": {"display": "DIGDOWN1", "origin": "Input\t→\t[{}]", "type": [IO_DI]},
        "INPUT_INT_K": {"display": "K", "origin": "Input\t→\t[{}]", "type": []},
        "INPUT_INT_UP2IND": {"display": "DIGUP2", "origin": "Input\t→\t[{}]", "type": [IO_DI]},
        "INPUT_INT_DOWN2IND": {"display": "DIGDOWN2", "origin": "Input\t→\t[{}]", "type": [IO_DI]},
        "INPUT_INT_K2": {"display": "K2", "origin": "Input\t→\t[{}]", "type": []},
        "INPUT_INT_ACTIND": {"display": "ACT", "origin": "Input\t→\t[{}]", "type": [IO_DI]},
        "INPUT_INT_ENABIND": {"display": "ENAB", "origin": "Input\t→\t[{}]", "type": [IO_DI]},
        "INPUT_INT_ENAB2IND": {"display": "ENAB2", "origin": "Input\t→\t[{}]", "type": [IO_DI]},
        "INPUT_INT_ENAB3IND": {"display": "ENAB3", "origin": "Input\t→\t[{}]", "type": [IO_DI]},
        "INPUT_INT_SUPIND": {"display": "SUP", "origin": "Input\t→\t[{}]", "type": [IO_AI]},
        "INPUT_INT_SEQID": {"display": "INPUT_INT_SEQID", "origin": "??", "type": []},
    },
    "dintvalcfg": {
        "INPUT_DINT_VMIN": {"display": "INPUT_DINT_VMIN", "origin": "??", "type": []},
        "INPUT_DINT_VMAX": {"display": "INPUT_DINT_VMAX", "origin": "??", "type": []},
        "INPUT_DINT_VMIN2": {"display": "INPUT_DINT_VMIN2", "origin": "??", "type": []},
        "INPUT_DINT_VMAX2": {"display": "INPUT_DINT_VMAX2", "origin": "??", "type": []},
    },
    "dintval": {
        "INPUT_DINT_VMIN": {"display": "INPUT_DINT_VMIN", "origin": "??", "type": []},
        "INPUT_DINT_VMAX": {"display": "INPUT_DINT_VMAX", "origin": "??", "type": []},
        "INPUT_DINT_VMIN2": {"display": "INPUT_DINT_VMIN2", "origin": "??", "type": []},
        "INPUT_DINT_VMAX2": {"display": "INPUT_DINT_VMAX2", "origin": "??", "type": []},
    },
}


def inputparam_map_indexes():
    new_entries = {}
    for key, value in Type_InputParam_Map.items():
        if isinstance(value, dict):
            new_entries[f'_{key}'] = {i: k for i, k in enumerate(value.keys())}
    return new_entries


Type_InputParam_Map.update(inputparam_map_indexes())


Type_OutputParam_Map = {
    "intval": {  # tipi custom non rinominare indice
        "OUTPUT_INT_TIPO": {"display": "TIPO", "origin": "??", "type": []},
        "OUTPUT_INT_ANA1IND": {"display": "ANA1", "origin": "Output\t→\t[{}]", "type": [IO_AO]},
        "OUTPUT_INT_ANA2IND": {"display": "ANA2", "origin": "Output\t→\t[{}]", "type": [IO_AO]},
        "OUTPUT_INT_DIG1IND": {"display": "DIG1", "origin": "Output\t→\t[{}]", "type": [IO_DO]},
        "OUTPUT_INT_DIG2IND": {"display": "DIG2", "origin": "Output\t→\t[{}]", "type": [IO_DO]},
        "OUTPUT_INT_CCIND": {"display": "CC", "origin": "Output\t→\t[{}]", "type": [IO_DO]},
        "OUTPUT_INT_ADDPARAM1": {"display": "ADDPARAM1", "origin": "Output\t→\t[{}]", "type": []},
        "OUTPUT_INT_ADDPARAM2": {"display": "ADDPARAM2", "origin": "Output\t→\t[{}]", "type": []},
        "OUTPUT_INT_ADDPARAM3": {"display": "ADDPARAM3", "origin": "Output\t→\t[{}]", "type": []},
        "OUTPUT_INT_ADDPARAM4": {"display": "ADDPARAM4", "origin": "Output\t→\t[{}]", "type": []},
        "OUTPUT_INT_ACTIND": {"display": "ACT", "origin": "??", "type": [IO_DI]},
        "OUTPUT_INT_ENAB": {"display": "ENAB", "origin": "Output\t→\t[{}]", "type": [IO_DI]},
        "OUTPUT_INT_ENAB2": {"display": "ENAB2", "origin": "Output\t→\t[{}]", "type": [IO_DI]},
        "OUTPUT_INT_ENAB3": {"display": "ENAB3", "origin": "Output\t→\t[{}]", "type": [IO_DI]},
    },
    "dintval": {
        "OUTPUT_DINT_SCALEMIN1": {"display": "OUTPUT_DINT_SCALEMIN1", "origin": "??", "type": []},
        "OUTPUT_DINT_SCALEMAX1": {"display": "OUTPUT_DINT_SCALEMAX1", "origin": "??", "type": []},
        "OUTPUT_DINT_SCALEMIN2": {"display": "OUTPUT_DINT_SCALEMIN2", "origin": "??", "type": []},
        "OUTPUT_DINT_SCALEMAX2": {"display": "OUTPUT_DINT_SCALEMAX2", "origin": "??", "type": []},
        "OUTPUT_DINT_SCALEMIN1H": {"display": "OUTPUT_DINT_SCALEMIN1H", "origin": "??", "type": []},
        "OUTPUT_DINT_SCALEMAX1H": {"display": "OUTPUT_DINT_SCALEMAX1H", "origin": "??", "type": []},
        "OUTPUT_DINT_SCALEMIN2H": {"display": "OUTPUT_DINT_SCALEMIN2H", "origin": "??", "type": []},
        "OUTPUT_DINT_SCALEMAX2H": {"display": "OUTPUT_DINT_SCALEMAX2H", "origin": "??", "type": []},
    },
    "realval": {
        "OUTPUT_REAL_VALMIN1": {"display": "OUTPUT_REAL_VALMIN1", "origin": "??", "type": []},
        "OUTPUT_REAL_VALMAX1": {"display": "OUTPUT_REAL_VALMAX1", "origin": "??", "type": []},
        "OUTPUT_REAL_VALMIN2": {"display": "OUTPUT_REAL_VALMIN2", "origin": "??", "type": []},
        "OUTPUT_REAL_VALMAX2": {"display": "OUTPUT_REAL_VALMAX2", "origin": "??", "type": []},
        "OUTPUT_REAL_VIN0": {"display": "OUTPUT_REAL_VIN0", "origin": "??", "type": []},
        "OUTPUT_REAL_VOUT0": {"display": "OUTPUT_REAL_VOUT0", "origin": "??", "type": []},
        "OUTPUT_REAL_VIN1": {"display": "OUTPUT_REAL_VIN1", "origin": "??", "type": []},
        "OUTPUT_REAL_VOUT1": {"display": "OUTPUT_REAL_VOUT1", "origin": "??", "type": []},
        "OUTPUT_REAL_VIN2": {"display": "OUTPUT_REAL_VIN2", "origin": "??", "type": []},
        "OUTPUT_REAL_VOUT2": {"display": "OUTPUT_REAL_VOUT2", "origin": "??", "type": []},
        "OUTPUT_REAL_VIN3": {"display": "OUTPUT_REAL_VIN3", "origin": "??", "type": []},
        "OUTPUT_REAL_VOUT3": {"display": "OUTPUT_REAL_VOUT3", "origin": "??", "type": []},
        "OUTPUT_REAL_VIN4": {"display": "OUTPUT_REAL_VIN4", "origin": "??", "type": []},
        "OUTPUT_REAL_VOUT4": {"display": "OUTPUT_REAL_VOUT4", "origin": "??", "type": []},
        "OUTPUT_REAL_VIN5": {"display": "OUTPUT_REAL_VIN5", "origin": "??", "type": []},
        "OUTPUT_REAL_VOUT5": {"display": "OUTPUT_REAL_VOUT5", "origin": "??", "type": []},
        "OUTPUT_REAL_V2IN0": {"display": "OUTPUT_REAL_V2IN0", "origin": "??", "type": []},
        "OUTPUT_REAL_V2OUT0": {"display": "OUTPUT_REAL_V2OUT0", "origin": "??", "type": []},
        "OUTPUT_REAL_V2IN1": {"display": "OUTPUT_REAL_V2IN1", "origin": "??", "type": []},
        "OUTPUT_REAL_V2OUT1": {"display": "OUTPUT_REAL_V2OUT1", "origin": "??", "type": []},
        "OUTPUT_REAL_V2IN2": {"display": "OUTPUT_REAL_V2IN2", "origin": "??", "type": []},
        "OUTPUT_REAL_V2OUT2": {"display": "OUTPUT_REAL_V2OUT2", "origin": "??", "type": []},
        "OUTPUT_REAL_V2IN3": {"display": "OUTPUT_REAL_V2IN3", "origin": "??", "type": []},
        "OUTPUT_REAL_V2OUT3": {"display": "OUTPUT_REAL_V2OUT3", "origin": "??", "type": []},
        "OUTPUT_REAL_V2IN4": {"display": "OUTPUT_REAL_V2IN4", "origin": "??", "type": []},
        "OUTPUT_REAL_V2OUT4": {"display": "OUTPUT_REAL_V2OUT4", "origin": "??", "type": []},
        "OUTPUT_REAL_V2IN5": {"display": "OUTPUT_REAL_V2IN5", "origin": "??", "type": []},
        "OUTPUT_REAL_V2OUT5": {"display": "OUTPUT_REAL_V2OUT5", "origin": "??", "type": []},

    }
}


def outputparam_map_indexes():
    new_entries = {}
    for key, value in Type_OutputParam_Map.items():
        if isinstance(value, dict):
            new_entries[f'_{key}'] = {i: k for i, k in enumerate(value.keys())}
    return new_entries


Type_OutputParam_Map.update(outputparam_map_indexes())


Type_FeedbackParam_Map = {
    "intval": {
        "FB_INT_TIPO": {"display": "FB_INT_TIPO", "origin": "Feedback\t→\t[{}]", "type": []},
        "FB_INT_TIPOMISURA": {"display": "FB_INT_TIPOMISURA", "origin": "Feedback\t→\t[{}]", "type": []},
        "FB_INT_RESETIND": {"display": "FB_INT_RESETIND", "origin": "Feedback\t→\t[{}]", "type": []},
        "FB_INT_ININD": {"display": "FB_INT_ININD", "origin": "Feedback\t→\t[{}]", "type": []},
        "FB_INT_ERRIND": {"display": "FB_INT_ERRIND", "origin": "Feedback\t→\t[{}]", "type": []},
    },
    "dintval": {
        # ...
        # ...
    },
    "realvalcfg": {
        "FB_REAL_DEADBAND": {"display": "FB_REAL_DEADBAND", "origin": "Feedback\t→\t[{}]", "type": []},
        "FB_REAL_RATIO": {"display": "FB_REAL_RATIO", "origin": "Feedback\t→\t[{}]", "type": []},
        "FB_REAL_SCALESUP": {"display": "FB_REAL_SCALESUP", "origin": "Feedback\t→\t[{}]", "type": []},
        "FB_REAL_SCALEINF": {"display": "FB_REAL_SCALEINF", "origin": "Feedback\t→\t[{}]", "type": []},
    },
    "realval": {
        "FB_REAL_DEADBAND": {"display": "FB_REAL_DEADBAND", "origin": "Feedback\t→\t[{}]", "type": []},
        "FB_REAL_RATIO": {"display": "FB_REAL_RATIO", "origin": "Feedback\t→\t[{}]", "type": []},
        "FB_REAL_SCALESUP": {"display": "FB_REAL_SCALESUP", "origin": "Feedback\t→\t[{}]", "type": []},
        "FB_REAL_SCALEINF": {"display": "FB_REAL_SCALEINF", "origin": "Feedback\t→\t[{}]", "type": []},
    }
}


def feedbackparam_map_indexes():
    new_entries = {}
    for key, value in Type_FeedbackParam_Map.items():
        if isinstance(value, dict):
            new_entries[f'_{key}'] = {i: k for i, k in enumerate(value.keys())}
    return new_entries


Type_FeedbackParam_Map.update(feedbackparam_map_indexes())
