"""
STRUTTURE:
per config 0.25.40
- header: [...]
- ifm:
    - card: [TYPE,DITHERFREQ,DITHERVAL]
    - exc: [EXCTYPE,EXCDITHERFREQ,EXCDITHERVAL]
- axind: [...]
- in: [AUTOSEL,TEACHSEL,CYCLESEL,STARTRESET,REMOTESEL,EMGCYPB,CONSOLE2SEL,CHROLLSEL,x,DEBALNOTPRESS,CONSOLE1SEL,SINGLEMOVSEL,STARTIN,STOPIN,MACSTARTEDIN,HOLDTORUN,RTCOUPLED,RCLEFTSEL,PINCHPRESS,RCRIGHTSEL,STARTSENSORIN,MAINTRESET,MANSEL,TESTSEL,SEMIAUTOSEL,HOLDTORUN2,BPDISABLE1,BPDISABLE2,BPDISABLE3,BPDISABLE4,BPDISABLE5,BPDISABLE6,BPDISABLE7,BPDISABLE8,BPDISABLE9,BPDISABLE10,BPDISABLE11,BPDISABLE12,AUTOMODE,AUTOCYCLEMODE,AUTOSTEPMODE,SEMIAUTOMODE,TEACHMODE,MANMODE,CONSOLE1MODE,CONSOLE2MODE,REMOTEMODE,CHROLLMODE,SINGLEMOVMODE,MACHINESTERTED,x,PUMPONCALC,GREASEALARMCALC,PUMPALARMCALC,x,x,ALARMON,x,ALARMSTOP,MAINTON,RTFWDISABLED,RCLEFTMEM,x,RCRIGHTMEM,HOLDTORUNERROR,x,x,x,MICROSEL,x,QUALITYEND,AUTOSTARTBLINK,QUALITYGOOD,PARTEND,x,PARTBEGIN,x,TILTDISABLED,x,x,x,x,x,x,x,x,x,x,x,x,x,RCV0,RCV1,RCV2,RCV3,RCV4,x,x,x,x,x,x,x,x,x,EMGCYRESETBTN,x,x,INVERTERRESET,INVERTERALARM,AUTOSTARTING,x,x,HOLDTORUNRC,PRELOADUP,PRELOADPINCHDISAB,x,x,x,x,UNBALLEFT,UNBALRIGHT,INVERTEROVERLOAD,LEFTSUPPINTERL,GREASELEVEL,GREASETR,STARTSENSOR2IN,HOLDTORUNRC2,ROLLTILTBALANCED,x,x,x,RIGHTSUPPINTERL,x,x,x]
    per il print:
    AUTOSEL,TEACHSEL,CYCLESEL,REMOTESEL,CONSOLE2SEL,CHROLLSEL,CONSOLE1SEL,SINGLEMOVSEL,MANSEL,TESTSEL,SEMIAUTOSEL,MICROSEL si trovano in config>main>selio
    AUTOMODE,AUTOCYCLEMODE,AUTOSTEPMODE,SEMIAUTOMODE,TEACHMODE,MANMODE,CONSOLE1MODE,CONSOLE2MODE,REMOTEMODE,CHROLLMODE,SINGLEMOVMODE si trovano in config>main>modeio
    DEBALNOTPRESS,MACSTARTEDIN/MACHINESTERTED,ROLLTILTBALANCED,STARTSENSORIN,STARTSENSOR2IN,AUTOSTARTING,AUTOSTARTBLINK,RTFWDISABLED,INVERTERRESET,INVERTERALARM,INVERTEROVERLOAD,LEFTSUPPINTERL,RIGHTSUPPINTERL si trovano in config>main>statusio
    STARTRESET,STARTIN,STOPIN,MAINTRESET,UNBALLEFT,UNBALRIGHT,TILTDISABLED si trovano in config>main>cmdio
    MACHINESTARTED,ALARMON,ALARMSTOP,MAINTON,QUALITYEND,QUALITYGOOD,PARTEND,PARTBEGIN si trovano in config>main>rsmio
    EMGCYRESETBTN,EMGCYPB,HOLDTORUN,HOLDTORUN2,HOLDTORUNRC,HOLDTORUNRC2,HOLDTORUNERROR si trovano in config>safety
    PINCHPRESS,PRELOADUP,PRELOADPINCHDISAB si trovano in config>pinchpreload
    RTCOUPLED si trova in config>rt
    BPDISABLE* si trovano in config>bp
    PUMPONCALC,GREASEALARMCALC,PUMPALARMCALC,GREASETR,GREASELEVEL si trovano in config>grease
    RCV* (0..4),RCLEFTSEL,RCRIGHTSEL,RCLEFTMEM,RCRIGHTMEM si trovano in config>radiocontrol
- out: ["x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","MACSTARTLIGHT_DO","x","x","x","x","MACREADYLIGHT_DO","x","x","STARTCMD_DO","x","x","x","x","STOPCMD_DO","x","x","x","x","x","x","x","x","x","x","EYEBENDON_DO","BP1_DO","BP2_DO","BP3_DO","BP4_DO","BP5_DO","BP6_DO","BP7_DO","BP8_DO","BP9_DO","BP10_DO","BP11_DO","BP12_DO","x","x","x","x","x","RCUM_DO","RCLEFTUP_DO","RCLEFTDOWN_DO","RCRIGHTUP_DO","RCRIGHTDOWN_DO","RCBOTTONUP_DO","RCBOTTOMDOWN_DO","RCTOPLEFT_DO","RCTOPRIGHT_DO","RCALARM_DO","EMGCYRESETBTN_DO","EMGCYRESETLIGHT_DO","x","PINCHPRESSAR_DO","PINCHPRESSAR2_DO","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x"]
    per il print
    MACSTARTLIGHT_DO,MACREADYLIGHT_DO,STARTCMD_DO,STOPCMD_DO  si trovano in config>main>cmdio
    EMGCYRESETLIGHT_DO,EMGCYRESETBTN_DO  si trovano in config>safety
    PINCHPRESSAR_DO,PINCHPRESSAR2_DO si trovano in config>pinchprelaod
    BP*_DO si trovano in config>bp
    EYEBEND_DO si trova in config>checkmeasurement
    RCUM_DO,RCLEFTUP_DO,RCLEFTDOWN_DO,RCRIGHTUP_DO,RCRIGHTDOWN_DO,RCBOTTOMUP_DO,RCBOTTOMDOWN_DO,RCTOPLEFT_DO,RCTOPRIGHT_DO,RCALARM_DO si trovano in config>radiocontrol>in

- param:
    - pstring: [MODEL,COSTUMER,x,x]
    - pbool: [0...MAX_PARAMBOOL]
    - pint: [SN,MACHTYPE,CALCTYPE,CHECKTYPE,PRESSPINCHTYPE,REFTIME,HOLDTORUNTYPE,NUMCICLIAVG,DEFRADIUSTYPE,SEPCHTYPE,PINCHTYPE,HOLDTORUNTIMEOUT,HOLDTORUNTIMEOUT2,BP1TIMEOUT,BP2TIMEOUT,BP3TIMEOUT,BP4TIMEOUT,BP5TIMEOUT,BP6TIMEOUT,BP7TIMEOUT,BP8TIMEOUT,BP9TIMEOUT,BP10TIMEOUT,BP11TIMEOUT,BP12TIMEOUT,ROLLIND,GRESEPUMPSTART,GREASETIMEOUT1,GREASETIMEOUT2,GRESENUMFB,FREE31,GREASEIN1,GREASEIN2,GREASEIN3,GREASEIN4,GREASEIN5,GREASEIN6,GREASEIN7,GREASEIN8,GREASEIN9,GREASEIN10,GREASEIN11,GREASEIN12,GREASEIN13,GREASEIN14,GREASEIN15,GREASEIN16,GREASEOUT1,GREASEOUT2,GREASEOUT3,GREASEOUT4,GREASEOUT5,GREASEOUT6,GREASEOUT7,GREASEOUT8,GREASEOUT9,GREASEOUT10,GREASEOUT11,GREASEOUT12,GREASEOUT13,GREASEOUT14,GREASEOUT15,GREASEOUT16,GREASENUMV,GREASEPUMPON,RECYCVALVEIND,RECYCVALVETIMEOUT,PINCHPRESSSPEED,RTTYPE,AVGDIND,NHDTIND,RESETTYPE,ARCHIMETERCOMUSB,ARCHIMETERCOMWIFI,ARCHIMETERTIMEOUT,RCTYPE,RCSELAI,ROLLCHSEQ,ROLLNUM]
    - preal: [...]
    - ptype: [...]
- io:
    - di: [NAME,BOOL_DEFAULT_VALUE,x,SIM,BOOL_SIM_VALUE,ADDRESS,IO_CAMPO_1,CAMPO_2,x,UM,MEMTYPE,MEMIND,TIMEOUT,IN,x,x,x,x,x,EXPRTYPE,EXPR_OPERAND,EXPR_ADDRESS,EXPR_OPERATOR,EXPR_OPERAND,EXPR_ADDRESS,EXPR_OPERATOR,EXPR_OPERAND,EXPR_ADDRESS,EXPR_OPERATOR,EXPR_OPERAND,EXPR_ADDRESS,EXPR_OPERATOR,EXPR_OPERAND,EXPR_ADDRESS,EXPR_OPERATOR,EXPR_OPERAND,EXPR_ADDRESS,EXPR_OPERATOR]
        (EXPR_OPERAND,EXPR_ADDRESS,EXPR_OPERATOR) si attivano se EXPRTYPE != -1 se no non ci sono proprio
    - ai: [NAME,BOOL_DEFAULT_VALUE,x,SIM,BOOL_SIM_VALUE,ADDRESS,IO_CAMPO_1,CAMPO_2,NBYTES,UM,MEMTYPE,MEMIND,TIMEOUT,IN,DINTDEFAULTVALUE,DINTSIMVALUE,DEADBAND,x,TOTDELTAMAX,COEFFMULT,x]
    - ao: [NAME,BOOL_DEFAULT_VALUE,PROG,SIM,BOOL_SIM_VALUE,ADDRESS,IO_CAMPO_1,CAMPO_2,NBYTES,UM,MEMTYPE,MEMIND,IN,AODUAL,DINTDEFAULTVALUE,DINTSIMVALUE,x,x,x,AOPRIORITY,x]
    - do: [NAME,BOOL_DEFAULT_VALUE,x,SIM,BOOL_SIM_VALUE,ADDRESS,IO_CAMPO_1,CAMPO_2,x,UM,MEMTYPE,MEMIND,TIMEOUT,IN,x,x,x,x,x,x,x]
    - ri: [NAME,x,x,x,x,ADDRESS,x,CAMPO_2,ENABLED,x,x,x,RESET,IN,x,x,x,x,x,x,x]
    - ao: [NAME,x,x,x,x,x,IO_CAMPO_1,x,x,x,x,x,AODUAL,IN,x,x,x,x,x,x,x]
- obj:
    - axis: [NAME]
        bool: [x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x]
        int: ["x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","x","SUP","INF","x","x","x","x","x","x","x","x","x","x","ALTFBDIG","HH","H","L","LL","SAFETYUP1","SAFETYUP2","SAFETYUP3","SAFETYUP4","SAFETYUP5","SAFETYUP6","H0","L0","x","x","x","x","x","x","x","x","SAFETYDOWN1","SAFETYDOWN2","SAFETYDOWN3","SAFETYDOWN4","SAFETYDOWN5","SAFETYDOWN6","x","x","x","DECOUPLE1AUTO","DECOUPLE2MAN","DECOUPLE3MAN","DECOUPLE4MAN","DECOUPLE5MAN","DECOUPLE6MAN","PS1","x","x","PS2","PS3","x","x","x","x","x","FREE70","FREE71","x","x","x","x","x","x","x","BPDISABLE1","BPDISABLE2","BPDISABLE3","BPDISABLE4","BPDISABLE5","BPDISABLE6","BPDISABLE7","BPDISABLE8","BPDISABLE9","BPDISABLE10","BPDISABLE11","BPDISABLE12","OPTPARAM1","OPTPARAM2","OPTPARAM3"]
        type: [x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x]
    - input: [HOLDTORUNENAB,x,INPUT_TYPE,INPUT_MESURETYPE,ANA,DIGUP1,DIGDOWN1,K,DIGUP2,DIGDOWN2,K2,ACT,ENAB1,ENAB2,ENAB3,SUP,SEQ,VMIN,VMAX,VMIN2,VMAX2]
    - fb: [FB_TYPE,FB_MESURETYPE,RESETIND,ININD,FB_ERR_DEPRECATED,INFUNDERFLOW,SUPOVERFLOW,DEADBAND,RATIO,x,x]
    - output: [OUTPUT_TYPE,ANA1,ANA2,DIG1,DIG2,CC,RPM,TIMEOUTBRKADV,ADVDEFSIDE,FREE,ACT,ENAB1,ENAB2,ENAB3,SCALEMIN1,SCALEMAX1,SCALEMIN2,SCALEMAX2,SCALEMIN1H,SCALEMAX1H,SCALEMIN2H,SCALEMAX2H,VALMIN1,VALMAX1,VALMIN2,VALMAX2,VIN0,VOUT0,VIN1,VOUT1,VIN2,VOUT2,VIN3,VOUT3,VIN4,VOUT4,VIN5,VOUT5,V2IN0,V2OUT0,V2IN1,V2OUT1,V2IN2,V2OUT2,V2IN3,V2OUT3,V2IN4,V2OUT4,V2IN5,V2OUT5]
        se OUTPUT_TYPE = ADV
        ANA1 = ADVIND
        ANA2 = ADVSTART
        DIG1 = ADVENABLE
        DIG2 = BRAKE
        se OUTPUT_TYPE = PSLCAN
        RPM = CTRL1PSLCAN
        TIMEOUTBRKADV = STATUS1PSLCAN
        ADVDEFSIDE = CTRL2PSLCAN
        FREE = STATUS2PSLCAN
        se OUTPUT_TYPE = ATV340
        RPM = RPMATV
        se OUTPUT_TYPE = SELSLOW
        ANA1 = DIG1ADD
        ANA2 = DIG2ADD
    - mot: [CONFIG,SELECTABLE,SEQ,OPT,DEFAULT,LSSTOP,LS2START,TR,CMD,STAT,TIMEOUT,CMD1,CMD2,CMD3,TIMEOUT2,MOT_TYPE,TIMEOUTBTN,TR2,STARTING]
    - alarm: [NAME,CONFIG,INVOUT,MODE,IN,OUT,COD,ENAB,DISAB,REQACK,ACK,TIMEOUT,FREE]
    - maint [...]
"""

"""
Variabili di sistema
TYPE: (IDX_SYSTEM)
    INDEX = 1
    AXIS = 2
    FEEDBACK = 3
    INPUT = 4
    OUTPUT = 5
    MOTOR = 6
    PID = 7
    TOOLSET = 8
    ALARM = 9
    MAINT = 10
    AXISREAL = 11
in base al tipo partendo da 0 che è axis[0] e incrementando
AXIS: 
    MOVING (2048=0, 2049=1, ...)
    UP (2112=0, ...)
    DOWN (2176=0, ...)
    MAX (2240=0, ...)
    MIN (2304=0, ...)
    SUPLS (2368=0, ...)
    INFLS (2432=0, ...)
    HH (2496=0, ...)
    H (2560=0, ...)
    L (2624=0, ...)
    LL (2688=0, ...)
    H0 (2752=0, ...)
    L0 (2816=0, ...)
    SAF (2880=0, ...)
    ALTFB (2944=0, ...)
    BAD (3008=0, ...)
    TILT (3072=0, ...)
    P1UP (3136=0, ...)
    P1DOWN (3200=0, ...)
    P2UP (3264=0, ...)
    P2DOWN (3328=0, ...)
    SLOW (3392=0, ...)
    FAST (3456=0, ...)
FEEDBACK:
    ERR
    RESET
INPUT:
    ACT
    ENAB1
    ENAB2
    ENAB3
    ENAB
OUTPUT:
    ACT
    ENAB1
    ENAB2
    ENAB3
    ENAB
MOTOR:
    STAT
    CMD
    STOP
    START
    TR
    TR2
    CMD1
    CMD2
    CMD3
    STARTING
    SEL
    SEQ
    OPT
    DEF
TOOLSET:
    SELECTED
ALARM:
    VAL (16384=0, ..)
    ENAB (16640=0, ..)
    DISAB (16896=0, ..)
    REQ (17152=0, ..)
    ACK (17408=0, ..)
    IN (17664=0, ..)
MAINT:
    VAL
    ENAB
    DISAB
AXISREAL:
    POS
    SPEED
    DELTA
    SUP
"""
'''
NOTE: dentro gli -ao se tipo = PNET o CAN, trovo in IN e AO_DUAL gli -ai
'''