#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from __future__ import annotations

import argparse
from http.server import HTTPServer, BaseHTTPRequestHandler
from urllib.parse import urlparse, parse_qs
from pathlib import Path
import mimetypes
import ssl
import sys

DEFAULT_NAME = "config.yaml"
DUMMY_CONFIG = b"# dummy config generated by server_test.py\nheader:\n  type: test\n"

def find_default_config() -> Path | None:
    # 1) working dir (Run config di PyCharm)
    cand = Path.cwd() / DEFAULT_NAME
    if cand.exists():
        return cand
    # 2) cartella dove sta lo script
    cand2 = Path(__file__).resolve().parent / DEFAULT_NAME
    if cand2.exists():
        return cand2
    return None

def make_handler(config_path: Path | None, served_name: str = DEFAULT_NAME):
    class Handler(BaseHTTPRequestHandler):
        def do_GET(self):
            try:
                parsed = urlparse(self.path)
                path = parsed.path
                qs = parse_qs(parsed.query)

                if path == "/ping":
                    return self._send_text(200, "ok\n")

                if path == "/UserFiles":
                    name = qs.get("Name", [""])[0]
                    action = qs.get("Action", [""])[0]
                    if name == served_name and action.upper() == "DOWNLOAD":
                        return self._send_config(served_name)

                    return self._send_text(400, "Bad request: query non valida.\n")

                if path.strip("/") == served_name:
                    return self._send_config(served_name)

                return self._send_text(404, "Not found.\n")

            except Exception as e:
                return self._send_text(500, f"Internal server error: {e}\n")

        # -------- helpers ----------
        def _send_config(self, download_as: str):
            data: bytes
            # Se ho un file reale lo invio, altrimenti mando il dummy
            if config_path and config_path.exists():
                data = config_path.read_bytes()
            else:
                data = DUMMY_CONFIG

            ctype, _ = mimetypes.guess_type(download_as)
            if not ctype:
                ctype = "application/octet-stream"

            self.send_response(200)
            self.send_header("Content-Type", ctype)
            self.send_header("Content-Disposition", f'attachment; filename="{download_as}"')
            self.send_header("Content-Length", str(len(data)))
            self.end_headers()
            self.wfile.write(data)

        def _send_text(self, code: int, msg: str):
            data = msg.encode("utf-8", errors="replace")
            self.send_response(code)
            self.send_header("Content-Type", "text/plain; charset=utf-8")
            self.send_header("Content-Length", str(len(data)))
            self.end_headers()
            self.wfile.write(data)

        def log_message(self, fmt, *args):
            sys.stdout.write("%s - - [%s] %s\n" % (self.address_string(),
                                                   self.log_date_time_string(),
                                                   fmt % args))
    return Handler

def main():
    ap = argparse.ArgumentParser(description="Server test per servire config.yaml")
    ap.add_argument("--file", help="Percorso al file config.yaml da servire (opzionale)")
    ap.add_argument("--port", type=int, default=80, help="Porta di ascolto (default: 8000)")
    ap.add_argument("--host", default="0.0.0.0", help="Host bind (default: 0.0.0.0)")
    ap.add_argument("--name", default=DEFAULT_NAME, help="Nome file esposto (default: config.yaml)")
    ap.add_argument("--cert", help="Certificato PEM per HTTPS (opzionale)")
    ap.add_argument("--key", help="Chiave privata PEM per HTTPS (opzionale)")
    args = ap.parse_args()

    cfg_path: Path | None
    if args.file:
        cfg_path = Path(args.file).resolve()
        if not cfg_path.exists():
            print(f"⚠️  --file indicato ma non trovato: {cfg_path} — userò un config finto.")
            cfg_path = None
    else:
        cfg_path = find_default_config()
        if cfg_path:
            print(f"📄 Trovato config: {cfg_path}")
        else:
            print("ℹ️  Nessun config.yaml trovato: servirò un config finto.")

    handler = make_handler(cfg_path, served_name=args.name)
    httpd = HTTPServer((args.host, args.port), handler)

    scheme = "http"
    if args.cert and args.key:
        context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
        context.load_cert_chain(certfile=args.cert, keyfile=args.key)
        httpd.socket = context.wrap_socket(httpd.socket, server_side=True)
        scheme = "https"

    print(f"🚀 Server su {scheme}://{args.host}:{args.port}")
    print(f"   - /UserFiles?Name={args.name}&Action=DOWNLOAD")
    print(f"   - /{args.name}")
    print(f"   - /ping")
    print(f"   Servendo: {cfg_path if cfg_path else '(config finto in memoria)'}")
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print("\n🛑 Stop server")

if __name__ == "__main__":
    main()
